// Code generated by protoc-gen-go.
// source: gearman.proto
// DO NOT EDIT!

/*
Package gearman is a generated protocol buffer package.

It is generated from these files:
	gearman.proto

It has these top-level messages:
	GearmanOperation
	Auth
*/
package gearman

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import ci "github.com/appscode/api/ci"
import kubernetes "github.com/appscode/api/kubernetes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Next Id: 11
type GearmanOpType int32

const (
	GearmanOpType_UNKNOWN          GearmanOpType = 0
	GearmanOpType_CLUSTER_CREATE   GearmanOpType = 1
	GearmanOpType_CLUSTER_SCALE    GearmanOpType = 2
	GearmanOpType_CLUSTER_DELETE   GearmanOpType = 3
	GearmanOpType_NAMESPACE_CREATE GearmanOpType = 4
	GearmanOpType_SLAVE_CREATE     GearmanOpType = 5
	GearmanOpType_SLAVE_DELETE     GearmanOpType = 6
)

var GearmanOpType_name = map[int32]string{
	0: "UNKNOWN",
	1: "CLUSTER_CREATE",
	2: "CLUSTER_SCALE",
	3: "CLUSTER_DELETE",
	4: "NAMESPACE_CREATE",
	5: "SLAVE_CREATE",
	6: "SLAVE_DELETE",
}
var GearmanOpType_value = map[string]int32{
	"UNKNOWN":          0,
	"CLUSTER_CREATE":   1,
	"CLUSTER_SCALE":    2,
	"CLUSTER_DELETE":   3,
	"NAMESPACE_CREATE": 4,
	"SLAVE_CREATE":     5,
	"SLAVE_DELETE":     6,
}

func (x GearmanOpType) String() string {
	return proto.EnumName(GearmanOpType_name, int32(x))
}
func (GearmanOpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Next Id: 10
type GearmanOperation struct {
	Phid string        `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	Type GearmanOpType `protobuf:"varint,2,opt,name=type,enum=gearman.GearmanOpType" json:"type,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*GearmanOperation_ClusterCreateRequest
	//	*GearmanOperation_ClusterScaleRequest
	//	*GearmanOperation_ClusterDeleteRequest
	//	*GearmanOperation_CiSlaveCreateRequest
	//	*GearmanOperation_CiSlaveDeleteRequest
	Request     isGearmanOperation_Request `protobuf_oneof:"request"`
	Auth        *Auth                      `protobuf:"bytes,8,opt,name=auth" json:"auth,omitempty"`
	RequestTime int64                      `protobuf:"varint,9,opt,name=request_time" json:"request_time,omitempty"`
}

func (m *GearmanOperation) Reset()                    { *m = GearmanOperation{} }
func (m *GearmanOperation) String() string            { return proto.CompactTextString(m) }
func (*GearmanOperation) ProtoMessage()               {}
func (*GearmanOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isGearmanOperation_Request interface {
	isGearmanOperation_Request()
}

type GearmanOperation_ClusterCreateRequest struct {
	ClusterCreateRequest *kubernetes.ClusterCreateRequest `protobuf:"bytes,3,opt,name=cluster_create_request,oneof"`
}
type GearmanOperation_ClusterScaleRequest struct {
	ClusterScaleRequest *kubernetes.ClusterScaleRequest `protobuf:"bytes,4,opt,name=cluster_scale_request,oneof"`
}
type GearmanOperation_ClusterDeleteRequest struct {
	ClusterDeleteRequest *kubernetes.ClusterDeleteRequest `protobuf:"bytes,5,opt,name=cluster_delete_request,oneof"`
}
type GearmanOperation_CiSlaveCreateRequest struct {
	CiSlaveCreateRequest *ci.SlaveCreateRequest `protobuf:"bytes,6,opt,name=ci_slave_create_request,oneof"`
}
type GearmanOperation_CiSlaveDeleteRequest struct {
	CiSlaveDeleteRequest *ci.SlaveDeleteRequest `protobuf:"bytes,7,opt,name=ci_slave_delete_request,oneof"`
}

func (*GearmanOperation_ClusterCreateRequest) isGearmanOperation_Request() {}
func (*GearmanOperation_ClusterScaleRequest) isGearmanOperation_Request()  {}
func (*GearmanOperation_ClusterDeleteRequest) isGearmanOperation_Request() {}
func (*GearmanOperation_CiSlaveCreateRequest) isGearmanOperation_Request() {}
func (*GearmanOperation_CiSlaveDeleteRequest) isGearmanOperation_Request() {}

func (m *GearmanOperation) GetRequest() isGearmanOperation_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *GearmanOperation) GetClusterCreateRequest() *kubernetes.ClusterCreateRequest {
	if x, ok := m.GetRequest().(*GearmanOperation_ClusterCreateRequest); ok {
		return x.ClusterCreateRequest
	}
	return nil
}

func (m *GearmanOperation) GetClusterScaleRequest() *kubernetes.ClusterScaleRequest {
	if x, ok := m.GetRequest().(*GearmanOperation_ClusterScaleRequest); ok {
		return x.ClusterScaleRequest
	}
	return nil
}

func (m *GearmanOperation) GetClusterDeleteRequest() *kubernetes.ClusterDeleteRequest {
	if x, ok := m.GetRequest().(*GearmanOperation_ClusterDeleteRequest); ok {
		return x.ClusterDeleteRequest
	}
	return nil
}

func (m *GearmanOperation) GetCiSlaveCreateRequest() *ci.SlaveCreateRequest {
	if x, ok := m.GetRequest().(*GearmanOperation_CiSlaveCreateRequest); ok {
		return x.CiSlaveCreateRequest
	}
	return nil
}

func (m *GearmanOperation) GetCiSlaveDeleteRequest() *ci.SlaveDeleteRequest {
	if x, ok := m.GetRequest().(*GearmanOperation_CiSlaveDeleteRequest); ok {
		return x.CiSlaveDeleteRequest
	}
	return nil
}

func (m *GearmanOperation) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GearmanOperation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GearmanOperation_OneofMarshaler, _GearmanOperation_OneofUnmarshaler, _GearmanOperation_OneofSizer, []interface{}{
		(*GearmanOperation_ClusterCreateRequest)(nil),
		(*GearmanOperation_ClusterScaleRequest)(nil),
		(*GearmanOperation_ClusterDeleteRequest)(nil),
		(*GearmanOperation_CiSlaveCreateRequest)(nil),
		(*GearmanOperation_CiSlaveDeleteRequest)(nil),
	}
}

func _GearmanOperation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GearmanOperation)
	// request
	switch x := m.Request.(type) {
	case *GearmanOperation_ClusterCreateRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClusterCreateRequest); err != nil {
			return err
		}
	case *GearmanOperation_ClusterScaleRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClusterScaleRequest); err != nil {
			return err
		}
	case *GearmanOperation_ClusterDeleteRequest:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClusterDeleteRequest); err != nil {
			return err
		}
	case *GearmanOperation_CiSlaveCreateRequest:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CiSlaveCreateRequest); err != nil {
			return err
		}
	case *GearmanOperation_CiSlaveDeleteRequest:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CiSlaveDeleteRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GearmanOperation.Request has unexpected type %T", x)
	}
	return nil
}

func _GearmanOperation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GearmanOperation)
	switch tag {
	case 3: // request.cluster_create_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kubernetes.ClusterCreateRequest)
		err := b.DecodeMessage(msg)
		m.Request = &GearmanOperation_ClusterCreateRequest{msg}
		return true, err
	case 4: // request.cluster_scale_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kubernetes.ClusterScaleRequest)
		err := b.DecodeMessage(msg)
		m.Request = &GearmanOperation_ClusterScaleRequest{msg}
		return true, err
	case 5: // request.cluster_delete_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kubernetes.ClusterDeleteRequest)
		err := b.DecodeMessage(msg)
		m.Request = &GearmanOperation_ClusterDeleteRequest{msg}
		return true, err
	case 6: // request.ci_slave_create_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ci.SlaveCreateRequest)
		err := b.DecodeMessage(msg)
		m.Request = &GearmanOperation_CiSlaveCreateRequest{msg}
		return true, err
	case 7: // request.ci_slave_delete_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ci.SlaveDeleteRequest)
		err := b.DecodeMessage(msg)
		m.Request = &GearmanOperation_CiSlaveDeleteRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GearmanOperation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GearmanOperation)
	// request
	switch x := m.Request.(type) {
	case *GearmanOperation_ClusterCreateRequest:
		s := proto.Size(x.ClusterCreateRequest)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GearmanOperation_ClusterScaleRequest:
		s := proto.Size(x.ClusterScaleRequest)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GearmanOperation_ClusterDeleteRequest:
		s := proto.Size(x.ClusterDeleteRequest)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GearmanOperation_CiSlaveCreateRequest:
		s := proto.Size(x.CiSlaveCreateRequest)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GearmanOperation_CiSlaveDeleteRequest:
		s := proto.Size(x.CiSlaveDeleteRequest)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Auth struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Token     string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *Auth) Reset()                    { *m = Auth{} }
func (m *Auth) String() string            { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()               {}
func (*Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*GearmanOperation)(nil), "gearman.GearmanOperation")
	proto.RegisterType((*Auth)(nil), "gearman.Auth")
	proto.RegisterEnum("gearman.GearmanOpType", GearmanOpType_name, GearmanOpType_value)
}

var fileDescriptor0 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x6e, 0x94, 0x40,
	0x14, 0xed, 0x16, 0x76, 0x29, 0xb7, 0x4b, 0x83, 0x13, 0x5d, 0x49, 0x8d, 0xb1, 0x69, 0x7c, 0x30,
	0x3e, 0xb0, 0x49, 0x7d, 0xd2, 0x27, 0x29, 0x9d, 0x68, 0x22, 0x52, 0xb3, 0x6c, 0xf5, 0x91, 0x4c,
	0xe9, 0x8d, 0x25, 0xcb, 0x02, 0x32, 0x83, 0x89, 0x9f, 0xe1, 0x3f, 0xf9, 0x61, 0xce, 0x0e, 0xb0,
	0x20, 0xb1, 0x8f, 0x73, 0xee, 0x39, 0xe7, 0x9e, 0x7b, 0xef, 0x80, 0xf5, 0x1d, 0x59, 0xb5, 0x65,
	0xb9, 0x5b, 0x56, 0x85, 0x28, 0x88, 0xd1, 0x3e, 0x4f, 0x09, 0x2b, 0xd3, 0x65, 0x92, 0x2e, 0x79,
	0xc6, 0x7e, 0x62, 0x53, 0x3c, 0x7d, 0xbe, 0xc3, 0x36, 0xf5, 0x2d, 0x56, 0x39, 0x0a, 0xe4, 0xcb,
	0x24, 0xab, 0xb9, 0xc0, 0x8a, 0x37, 0xe5, 0xf3, 0x3f, 0x1a, 0xd8, 0x1f, 0x1a, 0xf9, 0x75, 0x89,
	0x15, 0x13, 0x69, 0x91, 0x93, 0x39, 0xe8, 0xe5, 0x7d, 0x7a, 0xe7, 0x4c, 0xce, 0x26, 0xaf, 0x4c,
	0xf2, 0x12, 0x74, 0xf1, 0xab, 0x44, 0xe7, 0x50, 0xbe, 0x4e, 0x2e, 0x16, 0x6e, 0xd7, 0x7c, 0x2f,
	0x5b, 0xcb, 0x2a, 0xb9, 0x84, 0x45, 0x6b, 0x1d, 0x27, 0x15, 0x32, 0x81, 0x71, 0x85, 0x3f, 0x6a,
	0xe4, 0xc2, 0xd1, 0xa4, 0xee, 0xf8, 0xe2, 0xcc, 0xed, 0x43, 0xb8, 0x7e, 0xc3, 0xf4, 0x15, 0x71,
	0xd5, 0xf0, 0x3e, 0x1e, 0x90, 0xf7, 0xf0, 0xa4, 0xf3, 0xe0, 0x09, 0xcb, 0x7a, 0x0b, 0x5d, 0x59,
	0xbc, 0xf8, 0x8f, 0x45, 0xb4, 0xe3, 0xf5, 0x0e, 0x83, 0x14, 0x77, 0x98, 0xe1, 0x20, 0xc5, 0xf4,
	0xc1, 0x14, 0x57, 0x8a, 0xd8, 0x7b, 0xbc, 0x85, 0xa7, 0x49, 0x1a, 0xab, 0x1d, 0x8e, 0x47, 0x99,
	0x29, 0x93, 0x85, 0x9b, 0xa4, 0x6e, 0xb4, 0xab, 0x8f, 0x07, 0x18, 0x4a, 0x47, 0xfd, 0x8d, 0x91,
	0x74, 0xdc, 0xf5, 0x19, 0xe8, 0xac, 0x16, 0xf7, 0xce, 0x91, 0xe2, 0x59, 0xfb, 0x2d, 0x7b, 0x12,
	0x24, 0x8f, 0x61, 0xde, 0xfa, 0xc4, 0x22, 0xdd, 0xa2, 0x63, 0x4a, 0x92, 0x76, 0x69, 0x82, 0xd1,
	0xa2, 0xe7, 0xef, 0x40, 0x57, 0xc4, 0x47, 0x60, 0xe6, 0x6c, 0x8b, 0xbc, 0x64, 0x09, 0xb6, 0xe7,
	0xb3, 0xe1, 0xa8, 0xe6, 0x72, 0x64, 0x09, 0xab, 0x13, 0x9a, 0xc4, 0x82, 0xa9, 0x28, 0x36, 0x98,
	0xab, 0xcb, 0x98, 0xaf, 0x7f, 0x4f, 0xc0, 0xfa, 0xf7, 0x96, 0xc7, 0x60, 0xdc, 0x84, 0x9f, 0xc2,
	0xeb, 0x6f, 0xa1, 0x7d, 0x40, 0x08, 0x9c, 0xf8, 0xc1, 0x4d, 0xb4, 0xa6, 0xab, 0xd8, 0x5f, 0x51,
	0x6f, 0x4d, 0xed, 0x89, 0x6c, 0x63, 0x75, 0x58, 0xe4, 0x7b, 0x01, 0xb5, 0x0f, 0x87, 0xb4, 0x2b,
	0x1a, 0x50, 0x49, 0xd3, 0x64, 0x6c, 0x3b, 0xf4, 0x3e, 0xd3, 0xe8, 0x8b, 0xe7, 0xd3, 0x4e, 0xac,
	0xcb, 0x40, 0xf3, 0x28, 0xf0, 0xbe, 0xee, 0x91, 0x69, 0x8f, 0xb4, 0xca, 0xd9, 0xed, 0x4c, 0xfd,
	0xce, 0x37, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xbe, 0x6a, 0x11, 0xea, 0x02, 0x00, 0x00,
}
