jobs:
  - name: build-binary
    docker:
      image: appscode/protoc-agent:3.0.0-beta-4
    script: |
      mkdir -p $GOPATH/src/appscode.com/api
      cp -a . $GOPATH/src/appscode.com/api
      cd $GOPATH/src/appscode.com/api
      python ./hack/schema.py deps
      ./hack/gen.sh
