// Code generated by protoc-gen-go.
// source: charge.proto
// DO NOT EDIT!

/*
Package billing is a generated protocol buffer package.

It is generated from these files:
	charge.proto
	subscription.proto

It has these top-level messages:
	ChargeCalculateRequest
	ChargeCalculateResponse
	SubscriptionDescribeRequest
	SubscriptionDescribeResponse
	Subscription
	SubscriptionOpenRequest
	SubscriptionCloseRequest
	SubscriptionCreateRequest
	Quota
	PhabricatorQuota
	CIQuota
	ArtifactoryQuota
	ClusterQuota
	DBQuota
	SubscriptionQoutaRequest
	SubscriptionAlterRequest
	SubscriptionQutaResponse
*/
package billing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ChargeCalculateRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *ChargeCalculateRequest) Reset()                    { *m = ChargeCalculateRequest{} }
func (m *ChargeCalculateRequest) String() string            { return proto.CompactTextString(m) }
func (*ChargeCalculateRequest) ProtoMessage()               {}
func (*ChargeCalculateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ChargeCalculateResponse struct {
	Status  *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	CostUsd string         `protobuf:"bytes,2,opt,name=cost_usd" json:"cost_usd,omitempty"`
}

func (m *ChargeCalculateResponse) Reset()                    { *m = ChargeCalculateResponse{} }
func (m *ChargeCalculateResponse) String() string            { return proto.CompactTextString(m) }
func (*ChargeCalculateResponse) ProtoMessage()               {}
func (*ChargeCalculateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChargeCalculateResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*ChargeCalculateRequest)(nil), "billing.ChargeCalculateRequest")
	proto.RegisterType((*ChargeCalculateResponse)(nil), "billing.ChargeCalculateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Charge service

type ChargeClient interface {
	Calculate(ctx context.Context, in *ChargeCalculateRequest, opts ...grpc.CallOption) (*ChargeCalculateResponse, error)
}

type chargeClient struct {
	cc *grpc.ClientConn
}

func NewChargeClient(cc *grpc.ClientConn) ChargeClient {
	return &chargeClient{cc}
}

func (c *chargeClient) Calculate(ctx context.Context, in *ChargeCalculateRequest, opts ...grpc.CallOption) (*ChargeCalculateResponse, error) {
	out := new(ChargeCalculateResponse)
	err := grpc.Invoke(ctx, "/billing.Charge/Calculate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Charge service

type ChargeServer interface {
	Calculate(context.Context, *ChargeCalculateRequest) (*ChargeCalculateResponse, error)
}

func RegisterChargeServer(s *grpc.Server, srv ChargeServer) {
	s.RegisterService(&_Charge_serviceDesc, srv)
}

func _Charge_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeCalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargeServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Charge/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargeServer).Calculate(ctx, req.(*ChargeCalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Charge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Charge",
	HandlerType: (*ChargeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Charge_Calculate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0x48, 0x2c,
	0x4a, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xca, 0xcc, 0xc9, 0xc9, 0xcc,
	0x4b, 0x97, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc,
	0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x93, 0x12, 0x03, 0x09, 0xa7,
	0x94, 0x54, 0x16, 0xa4, 0x16, 0xeb, 0x83, 0x49, 0x88, 0xb8, 0x92, 0x1a, 0x97, 0x98, 0x33, 0xd8,
	0x38, 0xe7, 0xc4, 0x9c, 0xe4, 0xd2, 0x9c, 0xc4, 0x92, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2,
	0x12, 0x21, 0x1e, 0x2e, 0x16, 0x90, 0x42, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x4e, 0x25, 0x6f, 0x2e,
	0x71, 0x0c, 0x75, 0xc5, 0x05, 0x40, 0xf3, 0x53, 0x85, 0xe4, 0xb8, 0xd8, 0x8a, 0x81, 0x96, 0x95,
	0x16, 0x83, 0x95, 0x72, 0x1b, 0xf1, 0xe9, 0x41, 0xec, 0xd1, 0x0b, 0x06, 0x8b, 0x0a, 0x09, 0x70,
	0x71, 0x24, 0xe7, 0x17, 0x97, 0xc4, 0x97, 0x16, 0xa7, 0x48, 0x30, 0x81, 0x0c, 0x33, 0x2a, 0xe3,
	0x62, 0x83, 0x18, 0x26, 0x94, 0xc3, 0xc5, 0x09, 0x37, 0x50, 0x48, 0x5e, 0x0f, 0xea, 0x17, 0x3d,
	0xec, 0x4e, 0x92, 0x52, 0xc0, 0xad, 0x00, 0xe2, 0x16, 0x25, 0x99, 0xa6, 0xcb, 0x4f, 0x26, 0x33,
	0x89, 0x09, 0x89, 0xe8, 0x43, 0x55, 0xea, 0x97, 0x19, 0xe8, 0x19, 0xea, 0x43, 0x42, 0x2c, 0x89,
	0x0d, 0xec, 0x67, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x5c, 0xe7, 0x25, 0x42, 0x01,
	0x00, 0x00,
}
