// Code generated by protoc-gen-go.
// source: purchase.proto
// DO NOT EDIT!

package billing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PurchaseBeginRequest struct {
	ProductSku string `protobuf:"bytes,1,opt,name=product_sku,json=productSku" json:"product_sku,omitempty"`
	Count      int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *PurchaseBeginRequest) Reset()                    { *m = PurchaseBeginRequest{} }
func (m *PurchaseBeginRequest) String() string            { return proto.CompactTextString(m) }
func (*PurchaseBeginRequest) ProtoMessage()               {}
func (*PurchaseBeginRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type PurchaseBeginResponse struct {
	Status   *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	PhidList []string       `protobuf:"bytes,2,rep,name=phid_list,json=phidList" json:"phid_list,omitempty"`
}

func (m *PurchaseBeginResponse) Reset()                    { *m = PurchaseBeginResponse{} }
func (m *PurchaseBeginResponse) String() string            { return proto.CompactTextString(m) }
func (*PurchaseBeginResponse) ProtoMessage()               {}
func (*PurchaseBeginResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *PurchaseBeginResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type PurchaseCompleteRequest struct {
	Phid       string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	ObjectPhid string `protobuf:"bytes,2,opt,name=object_phid,json=objectPhid" json:"object_phid,omitempty"`
	Failed     bool   `protobuf:"varint,3,opt,name=failed" json:"failed,omitempty"`
}

func (m *PurchaseCompleteRequest) Reset()                    { *m = PurchaseCompleteRequest{} }
func (m *PurchaseCompleteRequest) String() string            { return proto.CompactTextString(m) }
func (*PurchaseCompleteRequest) ProtoMessage()               {}
func (*PurchaseCompleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type PurchaseCloseRequest struct {
	ObjectPhid string `protobuf:"bytes,1,opt,name=object_phid,json=objectPhid" json:"object_phid,omitempty"`
}

func (m *PurchaseCloseRequest) Reset()                    { *m = PurchaseCloseRequest{} }
func (m *PurchaseCloseRequest) String() string            { return proto.CompactTextString(m) }
func (*PurchaseCloseRequest) ProtoMessage()               {}
func (*PurchaseCloseRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func init() {
	proto.RegisterType((*PurchaseBeginRequest)(nil), "billing.PurchaseBeginRequest")
	proto.RegisterType((*PurchaseBeginResponse)(nil), "billing.PurchaseBeginResponse")
	proto.RegisterType((*PurchaseCompleteRequest)(nil), "billing.PurchaseCompleteRequest")
	proto.RegisterType((*PurchaseCloseRequest)(nil), "billing.PurchaseCloseRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Purchase service

type PurchaseClient interface {
	Begin(ctx context.Context, in *PurchaseBeginRequest, opts ...grpc.CallOption) (*PurchaseBeginResponse, error)
	Complete(ctx context.Context, in *PurchaseCompleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Close(ctx context.Context, in *PurchaseCloseRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
}

type purchaseClient struct {
	cc *grpc.ClientConn
}

func NewPurchaseClient(cc *grpc.ClientConn) PurchaseClient {
	return &purchaseClient{cc}
}

func (c *purchaseClient) Begin(ctx context.Context, in *PurchaseBeginRequest, opts ...grpc.CallOption) (*PurchaseBeginResponse, error) {
	out := new(PurchaseBeginResponse)
	err := grpc.Invoke(ctx, "/billing.Purchase/Begin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseClient) Complete(ctx context.Context, in *PurchaseCompleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/billing.Purchase/Complete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseClient) Close(ctx context.Context, in *PurchaseCloseRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/billing.Purchase/Close", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Purchase service

type PurchaseServer interface {
	Begin(context.Context, *PurchaseBeginRequest) (*PurchaseBeginResponse, error)
	Complete(context.Context, *PurchaseCompleteRequest) (*dtypes.VoidResponse, error)
	Close(context.Context, *PurchaseCloseRequest) (*dtypes.VoidResponse, error)
}

func RegisterPurchaseServer(s *grpc.Server, srv PurchaseServer) {
	s.RegisterService(&_Purchase_serviceDesc, srv)
}

func _Purchase_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Purchase/Begin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServer).Begin(ctx, req.(*PurchaseBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Purchase_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Purchase/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServer).Complete(ctx, req.(*PurchaseCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Purchase_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Purchase/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServer).Close(ctx, req.(*PurchaseCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Purchase_serviceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Purchase",
	HandlerType: (*PurchaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _Purchase_Begin_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Purchase_Complete_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Purchase_Close_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor3 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4a, 0xeb, 0x40,
	0x18, 0x25, 0xe9, 0x6d, 0x6f, 0x3a, 0x85, 0x2e, 0x86, 0xde, 0xde, 0x92, 0xfb, 0x63, 0x89, 0x28,
	0xa5, 0x42, 0xa2, 0x15, 0x11, 0x5c, 0xda, 0xad, 0x42, 0x49, 0xc1, 0x95, 0x50, 0xd2, 0x64, 0x9a,
	0x8e, 0x8d, 0x99, 0xb1, 0x33, 0x29, 0x14, 0x71, 0xe3, 0x2b, 0xf8, 0x68, 0xbe, 0x82, 0x0b, 0x1f,
	0xc3, 0xf9, 0x49, 0xb4, 0xd4, 0x16, 0xba, 0x09, 0x99, 0xf3, 0x7d, 0x73, 0xce, 0x77, 0xce, 0x37,
	0xa0, 0x4e, 0xb3, 0x79, 0x38, 0x0d, 0x18, 0x72, 0xe9, 0x9c, 0x70, 0x02, 0x7f, 0x8e, 0x71, 0x92,
	0xe0, 0x34, 0xb6, 0xff, 0xc6, 0x84, 0xc4, 0x09, 0xf2, 0x02, 0x8a, 0xbd, 0x20, 0x4d, 0x09, 0x0f,
	0x38, 0x26, 0x29, 0xd3, 0x6d, 0x76, 0x53, 0xc2, 0x11, 0x5f, 0x52, 0xc4, 0x3c, 0xf5, 0xd5, 0xb8,
	0x73, 0x0d, 0x1a, 0x83, 0x9c, 0xf0, 0x12, 0xc5, 0x38, 0xf5, 0xd1, 0x43, 0x86, 0x18, 0x87, 0x7b,
	0xa0, 0x26, 0x1a, 0xa2, 0x2c, 0xe4, 0x23, 0x36, 0xcb, 0x5a, 0x46, 0xdb, 0xe8, 0x54, 0x7d, 0x90,
	0x43, 0xc3, 0x59, 0x06, 0x1b, 0xa0, 0x1c, 0x92, 0x2c, 0xe5, 0x2d, 0x53, 0x94, 0x4a, 0xbe, 0x3e,
	0x38, 0xb7, 0xe0, 0xd7, 0x1a, 0x1d, 0xa3, 0x62, 0x08, 0x04, 0x0f, 0x41, 0x85, 0x89, 0x89, 0x32,
	0xa6, 0xa8, 0x6a, 0xbd, 0xba, 0xab, 0x87, 0x71, 0x87, 0x0a, 0xf5, 0xf3, 0x2a, 0xfc, 0x03, 0xaa,
	0x74, 0x8a, 0xa3, 0x51, 0x82, 0x99, 0xa4, 0x2e, 0x09, 0x55, 0x4b, 0x02, 0x57, 0xe2, 0xec, 0x4c,
	0xc0, 0xef, 0x82, 0xbd, 0x4f, 0xee, 0x69, 0x82, 0x38, 0x2a, 0xe6, 0x85, 0xe0, 0x87, 0x6c, 0xcb,
	0x07, 0x55, 0xff, 0xd2, 0x03, 0x19, 0xdf, 0x21, 0x61, 0x41, 0x95, 0x4c, 0xed, 0x41, 0x43, 0x03,
	0xd9, 0xd0, 0x04, 0x95, 0x49, 0x80, 0x13, 0x14, 0xb5, 0x4a, 0xa2, 0x66, 0xf9, 0xf9, 0xc9, 0x39,
	0xff, 0x0a, 0xa5, 0x9f, 0x10, 0x86, 0x56, 0x42, 0x59, 0x25, 0x34, 0xd6, 0x09, 0x7b, 0xef, 0x26,
	0xb0, 0x8a, 0x9b, 0x70, 0x01, 0xca, 0x2a, 0x03, 0xf8, 0xcf, 0xcd, 0x77, 0xe4, 0x6e, 0x8a, 0xda,
	0xfe, 0xbf, 0xad, 0xac, 0xa3, 0x73, 0xdc, 0xe7, 0xd7, 0xb7, 0x17, 0xb3, 0xe3, 0xec, 0x8b, 0xd5,
	0x52, 0x16, 0x92, 0x48, 0xef, 0x38, 0xbf, 0xe4, 0x2d, 0x8e, 0xdd, 0x13, 0xaf, 0x78, 0x14, 0x17,
	0x46, 0x17, 0x2e, 0x81, 0x55, 0xa4, 0x03, 0xdb, 0xdf, 0xb8, 0xd7, 0x82, 0xb3, 0x1b, 0xc5, 0x22,
	0x6e, 0x08, 0x8e, 0x3e, 0x35, 0xcf, 0x94, 0xa6, 0x67, 0x77, 0x77, 0xd0, 0xf4, 0x1e, 0x65, 0x1a,
	0x4f, 0x52, 0x1a, 0x83, 0xb2, 0x0a, 0x6c, 0x83, 0xe5, 0xd5, 0x20, 0xb7, 0x88, 0x1e, 0x29, 0xd1,
	0x83, 0xee, 0x2e, 0x46, 0xc7, 0x15, 0xf5, 0x7e, 0x4f, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2a,
	0xa2, 0xba, 0x20, 0x10, 0x03, 0x00, 0x00,
}
