// Code generated by protoc-gen-go.
// source: subscription.proto
// DO NOT EDIT!

package billing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Resource int32

const (
	Resource_USER    Resource = 0
	Resource_CLUSTER Resource = 1
	Resource_NODE    Resource = 2
	Resource_DB      Resource = 3
	Resource_CI      Resource = 4
)

var Resource_name = map[int32]string{
	0: "USER",
	1: "CLUSTER",
	2: "NODE",
	3: "DB",
	4: "CI",
}
var Resource_value = map[string]int32{
	"USER":    0,
	"CLUSTER": 1,
	"NODE":    2,
	"DB":      3,
	"CI":      4,
}

func (x Resource) String() string {
	return proto.EnumName(Resource_name, int32(x))
}
func (Resource) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type SubscriptionDescribeRequest struct {
	Time string `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
}

func (m *SubscriptionDescribeRequest) Reset()                    { *m = SubscriptionDescribeRequest{} }
func (m *SubscriptionDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionDescribeRequest) ProtoMessage()               {}
func (*SubscriptionDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type SubscriptionDescribeResponse struct {
	Status        *dtypes.Status  `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Subscriptions []*Subscription `protobuf:"bytes,2,rep,name=subscriptions" json:"subscriptions,omitempty"`
}

func (m *SubscriptionDescribeResponse) Reset()                    { *m = SubscriptionDescribeResponse{} }
func (m *SubscriptionDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionDescribeResponse) ProtoMessage()               {}
func (*SubscriptionDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *SubscriptionDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SubscriptionDescribeResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type Subscription struct {
	Author      string `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	ProductSku  string `protobuf:"bytes,3,opt,name=product_sku" json:"product_sku,omitempty"`
	Quota       *Quota `protobuf:"bytes,4,opt,name=quota" json:"quota,omitempty"`
	DateStarted string `protobuf:"bytes,5,opt,name=date_started" json:"date_started,omitempty"`
	DateEnded   string `protobuf:"bytes,6,opt,name=date_ended" json:"date_ended,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Subscription) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

type SubscriptionOpenRequest struct {
	ProductType      string `protobuf:"bytes,1,opt,name=product_type" json:"product_type,omitempty"`
	AuthorPhid       string `protobuf:"bytes,2,opt,name=author_phid" json:"author_phid,omitempty"`
	ObjectPhid       string `protobuf:"bytes,3,opt,name=object_phid" json:"object_phid,omitempty"`
	SubscriptionPhid string `protobuf:"bytes,4,opt,name=subscription_phid" json:"subscription_phid,omitempty"`
	Metadata         string `protobuf:"bytes,5,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *SubscriptionOpenRequest) Reset()                    { *m = SubscriptionOpenRequest{} }
func (m *SubscriptionOpenRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionOpenRequest) ProtoMessage()               {}
func (*SubscriptionOpenRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type SubscriptionCloseRequest struct {
	ProductType string `protobuf:"bytes,1,opt,name=product_type" json:"product_type,omitempty"`
	ObjectPhid  string `protobuf:"bytes,2,opt,name=object_phid" json:"object_phid,omitempty"`
}

func (m *SubscriptionCloseRequest) Reset()                    { *m = SubscriptionCloseRequest{} }
func (m *SubscriptionCloseRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionCloseRequest) ProtoMessage()               {}
func (*SubscriptionCloseRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type SubscriptionCreateRequest struct {
	AuthorPhid  string `protobuf:"bytes,1,opt,name=author_phid" json:"author_phid,omitempty"`
	ProductPhid string `protobuf:"bytes,2,opt,name=product_phid" json:"product_phid,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *SubscriptionCreateRequest) Reset()                    { *m = SubscriptionCreateRequest{} }
func (m *SubscriptionCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionCreateRequest) ProtoMessage()               {}
func (*SubscriptionCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type Quota struct {
	User        int64             `protobuf:"varint,1,opt,name=user" json:"user,omitempty"`
	Phabricator *PhabricatorQuota `protobuf:"bytes,2,opt,name=phabricator" json:"phabricator,omitempty"`
	Artifact    *ArtifactoryQuota `protobuf:"bytes,3,opt,name=artifact" json:"artifact,omitempty"`
	Kube        *ClusterQuota     `protobuf:"bytes,4,opt,name=kube" json:"kube,omitempty"`
	Ci          *CIQuota          `protobuf:"bytes,5,opt,name=ci" json:"ci,omitempty"`
	Db          *DBQuota          `protobuf:"bytes,6,opt,name=db" json:"db,omitempty"`
}

func (m *Quota) Reset()                    { *m = Quota{} }
func (m *Quota) String() string            { return proto.CompactTextString(m) }
func (*Quota) ProtoMessage()               {}
func (*Quota) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Quota) GetPhabricator() *PhabricatorQuota {
	if m != nil {
		return m.Phabricator
	}
	return nil
}

func (m *Quota) GetArtifact() *ArtifactoryQuota {
	if m != nil {
		return m.Artifact
	}
	return nil
}

func (m *Quota) GetKube() *ClusterQuota {
	if m != nil {
		return m.Kube
	}
	return nil
}

func (m *Quota) GetCi() *CIQuota {
	if m != nil {
		return m.Ci
	}
	return nil
}

func (m *Quota) GetDb() *DBQuota {
	if m != nil {
		return m.Db
	}
	return nil
}

type PhabricatorQuota struct {
	DiskSize   int64 `protobuf:"varint,1,opt,name=disk_size" json:"disk_size,omitempty"`
	Repository int64 `protobuf:"varint,2,opt,name=repository" json:"repository,omitempty"`
}

func (m *PhabricatorQuota) Reset()                    { *m = PhabricatorQuota{} }
func (m *PhabricatorQuota) String() string            { return proto.CompactTextString(m) }
func (*PhabricatorQuota) ProtoMessage()               {}
func (*PhabricatorQuota) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type CIQuota struct {
	Agent     int64 `protobuf:"varint,1,opt,name=agent" json:"agent,omitempty"`
	Executors int64 `protobuf:"varint,2,opt,name=executors" json:"executors,omitempty"`
	Jobs      int64 `protobuf:"varint,3,opt,name=jobs" json:"jobs,omitempty"`
}

func (m *CIQuota) Reset()                    { *m = CIQuota{} }
func (m *CIQuota) String() string            { return proto.CompactTextString(m) }
func (*CIQuota) ProtoMessage()               {}
func (*CIQuota) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type ArtifactoryQuota struct {
	DiskSize   int64 `protobuf:"varint,1,opt,name=disk_size" json:"disk_size,omitempty"`
	Repository int64 `protobuf:"varint,2,opt,name=repository" json:"repository,omitempty"`
}

func (m *ArtifactoryQuota) Reset()                    { *m = ArtifactoryQuota{} }
func (m *ArtifactoryQuota) String() string            { return proto.CompactTextString(m) }
func (*ArtifactoryQuota) ProtoMessage()               {}
func (*ArtifactoryQuota) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type ClusterQuota struct {
	Cluster int64 `protobuf:"varint,1,opt,name=cluster" json:"cluster,omitempty"`
	Nodes   int64 `protobuf:"varint,2,opt,name=nodes" json:"nodes,omitempty"`
}

func (m *ClusterQuota) Reset()                    { *m = ClusterQuota{} }
func (m *ClusterQuota) String() string            { return proto.CompactTextString(m) }
func (*ClusterQuota) ProtoMessage()               {}
func (*ClusterQuota) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type DBQuota struct {
	Postgres      int64 `protobuf:"varint,1,opt,name=postgres" json:"postgres,omitempty"`
	Elasticsearch int64 `protobuf:"varint,2,opt,name=elasticsearch" json:"elasticsearch,omitempty"`
	Influxdb      int64 `protobuf:"varint,3,opt,name=influxdb" json:"influxdb,omitempty"`
}

func (m *DBQuota) Reset()                    { *m = DBQuota{} }
func (m *DBQuota) String() string            { return proto.CompactTextString(m) }
func (*DBQuota) ProtoMessage()               {}
func (*DBQuota) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type SubscriptionQutaRequest struct {
	Resource    Resource `protobuf:"varint,1,opt,name=resource,enum=billing.Resource" json:"resource,omitempty"`
	Subresource string   `protobuf:"bytes,2,opt,name=subresource" json:"subresource,omitempty"`
	ObjectPhid  string   `protobuf:"bytes,3,opt,name=object_phid" json:"object_phid,omitempty"`
	Count       int64    `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
}

func (m *SubscriptionQutaRequest) Reset()                    { *m = SubscriptionQutaRequest{} }
func (m *SubscriptionQutaRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionQutaRequest) ProtoMessage()               {}
func (*SubscriptionQutaRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type SubscriptionQutaResponse struct {
	Status           *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	SubscriptionPhid string         `protobuf:"bytes,3,opt,name=subscription_phid" json:"subscription_phid,omitempty"`
}

func (m *SubscriptionQutaResponse) Reset()                    { *m = SubscriptionQutaResponse{} }
func (m *SubscriptionQutaResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionQutaResponse) ProtoMessage()               {}
func (*SubscriptionQutaResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *SubscriptionQutaResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscriptionDescribeRequest)(nil), "billing.SubscriptionDescribeRequest")
	proto.RegisterType((*SubscriptionDescribeResponse)(nil), "billing.SubscriptionDescribeResponse")
	proto.RegisterType((*Subscription)(nil), "billing.Subscription")
	proto.RegisterType((*SubscriptionOpenRequest)(nil), "billing.SubscriptionOpenRequest")
	proto.RegisterType((*SubscriptionCloseRequest)(nil), "billing.SubscriptionCloseRequest")
	proto.RegisterType((*SubscriptionCreateRequest)(nil), "billing.SubscriptionCreateRequest")
	proto.RegisterType((*Quota)(nil), "billing.Quota")
	proto.RegisterType((*PhabricatorQuota)(nil), "billing.PhabricatorQuota")
	proto.RegisterType((*CIQuota)(nil), "billing.CIQuota")
	proto.RegisterType((*ArtifactoryQuota)(nil), "billing.ArtifactoryQuota")
	proto.RegisterType((*ClusterQuota)(nil), "billing.ClusterQuota")
	proto.RegisterType((*DBQuota)(nil), "billing.DBQuota")
	proto.RegisterType((*SubscriptionQutaRequest)(nil), "billing.SubscriptionQutaRequest")
	proto.RegisterType((*SubscriptionQutaResponse)(nil), "billing.SubscriptionQutaResponse")
	proto.RegisterEnum("billing.Resource", Resource_name, Resource_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Subscriptions service

type SubscriptionsClient interface {
	Create(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Describe(ctx context.Context, in *SubscriptionDescribeRequest, opts ...grpc.CallOption) (*SubscriptionDescribeResponse, error)
	Subscribe(ctx context.Context, in *SubscriptionOpenRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	UnSubscribe(ctx context.Context, in *SubscriptionCloseRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Quota(ctx context.Context, in *SubscriptionQutaRequest, opts ...grpc.CallOption) (*SubscriptionQutaResponse, error)
}

type subscriptionsClient struct {
	cc *grpc.ClientConn
}

func NewSubscriptionsClient(cc *grpc.ClientConn) SubscriptionsClient {
	return &subscriptionsClient{cc}
}

func (c *subscriptionsClient) Create(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) Describe(ctx context.Context, in *SubscriptionDescribeRequest, opts ...grpc.CallOption) (*SubscriptionDescribeResponse, error) {
	out := new(SubscriptionDescribeResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) Subscribe(ctx context.Context, in *SubscriptionOpenRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) UnSubscribe(ctx context.Context, in *SubscriptionCloseRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/UnSubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) Quota(ctx context.Context, in *SubscriptionQutaRequest, opts ...grpc.CallOption) (*SubscriptionQutaResponse, error) {
	out := new(SubscriptionQutaResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Quota", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Subscriptions service

type SubscriptionsServer interface {
	Create(context.Context, *SubscriptionCreateRequest) (*dtypes.VoidResponse, error)
	Describe(context.Context, *SubscriptionDescribeRequest) (*SubscriptionDescribeResponse, error)
	Subscribe(context.Context, *SubscriptionOpenRequest) (*dtypes.VoidResponse, error)
	UnSubscribe(context.Context, *SubscriptionCloseRequest) (*dtypes.VoidResponse, error)
	Quota(context.Context, *SubscriptionQutaRequest) (*SubscriptionQutaResponse, error)
}

func RegisterSubscriptionsServer(s *grpc.Server, srv SubscriptionsServer) {
	s.RegisterService(&_Subscriptions_serviceDesc, srv)
}

func _Subscriptions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Create(ctx, req.(*SubscriptionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Describe(ctx, req.(*SubscriptionDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionOpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Subscribe(ctx, req.(*SubscriptionOpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_UnSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).UnSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/UnSubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).UnSubscribe(ctx, req.(*SubscriptionCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_Quota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionQutaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Quota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Quota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Quota(ctx, req.(*SubscriptionQutaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Subscriptions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Subscriptions",
	HandlerType: (*SubscriptionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Subscriptions_Create_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Subscriptions_Describe_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _Subscriptions_Subscribe_Handler,
		},
		{
			MethodName: "UnSubscribe",
			Handler:    _Subscriptions_UnSubscribe_Handler,
		},
		{
			MethodName: "Quota",
			Handler:    _Subscriptions_Quota_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor1 = []byte{
	// 868 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x95, 0xcf, 0x6f, 0xdc, 0x44,
	0x14, 0xc7, 0xf1, 0xfe, 0xca, 0xe6, 0x6d, 0x12, 0x9c, 0xa1, 0x85, 0x8d, 0x09, 0x90, 0x38, 0x44,
	0x82, 0x04, 0xd9, 0x10, 0x0e, 0xa8, 0x80, 0x84, 0x48, 0x36, 0x87, 0x4a, 0x88, 0xd2, 0xa4, 0xe1,
	0x1a, 0xf9, 0xc7, 0x74, 0x33, 0x8d, 0xeb, 0x71, 0x3d, 0x63, 0x68, 0xa8, 0x72, 0xe9, 0x01, 0x24,
	0x0e, 0x5c, 0xf8, 0xd3, 0xfa, 0x2f, 0xf0, 0x87, 0xf0, 0x3c, 0x33, 0xde, 0x9d, 0x6d, 0x37, 0xdb,
	0xaa, 0x97, 0x64, 0xfd, 0xe6, 0xeb, 0xef, 0xfb, 0xbc, 0xf7, 0x66, 0xc6, 0x40, 0x44, 0x15, 0x8b,
	0xa4, 0x64, 0x85, 0x64, 0x3c, 0x0f, 0x8a, 0x92, 0x4b, 0x4e, 0x96, 0x62, 0x96, 0x65, 0x2c, 0x1f,
	0x7b, 0x9b, 0x63, 0xce, 0xc7, 0x19, 0x0d, 0xa3, 0x82, 0x85, 0x51, 0x9e, 0x73, 0x19, 0xd5, 0x2a,
	0xa1, 0x65, 0xde, 0xfb, 0x75, 0x38, 0x95, 0x57, 0x05, 0x15, 0xa1, 0xfa, 0xab, 0xe3, 0xfe, 0x3e,
	0x7c, 0x78, 0x6a, 0x99, 0x8e, 0x68, 0xfd, 0x33, 0xa6, 0x27, 0xf4, 0x49, 0x45, 0x85, 0x24, 0x2b,
	0xd0, 0x91, 0xec, 0x31, 0x1d, 0x3a, 0x5b, 0xce, 0x67, 0xcb, 0x7e, 0x06, 0x9b, 0xf3, 0xc5, 0xa2,
	0xc0, 0x4c, 0x94, 0x7c, 0x0c, 0x3d, 0x81, 0x69, 0x2b, 0xa1, 0xf4, 0x83, 0x83, 0xb5, 0x40, 0x67,
	0x0c, 0x4e, 0x55, 0x94, 0x7c, 0x01, 0xab, 0x76, 0x05, 0x62, 0xd8, 0xda, 0x6a, 0xa3, 0xec, 0x76,
	0x60, 0x6a, 0x08, 0x6c, 0x77, 0xff, 0x6f, 0x07, 0x56, 0xec, 0x00, 0x59, 0x83, 0x5e, 0x54, 0xc9,
	0x0b, 0x5e, 0x6a, 0x1c, 0x05, 0x87, 0xf6, 0xe8, 0x52, 0x3f, 0xbd, 0x07, 0x03, 0x2c, 0x29, 0xad,
	0x12, 0x79, 0x2e, 0x2e, 0xab, 0x61, 0x5b, 0x05, 0x3f, 0x82, 0xee, 0x93, 0x0a, 0x5b, 0x31, 0xec,
	0x18, 0xa0, 0x26, 0xd3, 0xfd, 0x3a, 0x4a, 0x6e, 0xc1, 0x4a, 0x1a, 0x49, 0x7a, 0x8e, 0xd4, 0xa5,
	0xa4, 0xe9, 0xb0, 0xab, 0x5e, 0x22, 0x00, 0x2a, 0x4a, 0xf3, 0x14, 0x63, 0x3d, 0x55, 0xfa, 0x9f,
	0x0e, 0x7c, 0x60, 0xc3, 0xdc, 0x2b, 0x68, 0xde, 0x34, 0x09, 0x5d, 0x9a, 0xcc, 0x8a, 0xc7, 0x69,
	0x78, 0x34, 0xed, 0x79, 0x71, 0xc1, 0xd2, 0x29, 0x24, 0x8f, 0x1f, 0x51, 0x54, 0xaa, 0xa0, 0x86,
	0xdc, 0x80, 0x75, 0xbb, 0x2d, 0x7a, 0xa9, 0xa3, 0x96, 0x5c, 0xe8, 0x3f, 0xa6, 0x32, 0x42, 0x9c,
	0x48, 0xc3, 0xf9, 0xc7, 0x30, 0xb4, 0x39, 0x8e, 0x32, 0x2e, 0xe8, 0x6b, 0x41, 0xec, 0x9c, 0x0a,
	0xc4, 0x7f, 0x00, 0x1b, 0x33, 0x36, 0x25, 0xc5, 0x8a, 0x1b, 0x9f, 0x97, 0xd0, 0xb5, 0x8d, 0x65,
	0x6e, 0x15, 0xd4, 0xcc, 0x40, 0x55, 0xe2, 0xbf, 0x70, 0xa0, 0xab, 0x3b, 0x8b, 0xf1, 0x4a, 0x50,
	0x3d, 0xa9, 0x36, 0x09, 0x70, 0x36, 0x17, 0x51, 0x5c, 0xb2, 0x24, 0x92, 0x38, 0xbe, 0x96, 0x1a,
	0xc6, 0xc6, 0x64, 0x18, 0xbf, 0x4c, 0xd7, 0xf4, 0xdb, 0xfb, 0xd0, 0xc7, 0x81, 0xb0, 0x87, 0x51,
	0x22, 0x95, 0xb3, 0x2d, 0xfe, 0xd1, 0x2c, 0xf0, 0xf2, 0x4a, 0x8b, 0x77, 0xa0, 0x73, 0x59, 0xc5,
	0xd4, 0x8c, 0x78, 0xba, 0x99, 0x8e, 0xb2, 0x4a, 0x48, 0x6a, 0x1c, 0x37, 0xa1, 0x95, 0x30, 0xd5,
	0xc2, 0xc1, 0x81, 0x3b, 0x95, 0xdc, 0x9d, 0xac, 0xa6, 0xb1, 0x9a, 0xb4, 0xbd, 0x3a, 0x3a, 0x54,
	0xab, 0xfe, 0x1d, 0x70, 0x5f, 0x21, 0x5c, 0x87, 0xe5, 0x94, 0x89, 0xcb, 0x73, 0xc1, 0xfe, 0xa0,
	0xa6, 0x48, 0xdc, 0x36, 0x25, 0x2d, 0xb8, 0x60, 0x35, 0x9a, 0xaa, 0xb1, 0x8d, 0xaf, 0x2e, 0x35,
	0x39, 0x56, 0xa1, 0x1b, 0x8d, 0x69, 0x2e, 0x8d, 0x1a, 0x0d, 0xe8, 0x53, 0x9a, 0x54, 0x28, 0x16,
	0x5a, 0x5c, 0xf7, 0xec, 0x11, 0x8f, 0x85, 0xaa, 0xb8, 0x7e, 0xd5, 0x7d, 0xa5, 0xd4, 0x37, 0xcc,
	0x1a, 0xc0, 0xca, 0x4c, 0xf1, 0xef, 0xc2, 0x52, 0xa2, 0x9f, 0xcd, 0x4b, 0xc8, 0x92, 0xf3, 0x94,
	0x9a, 0xc4, 0xfe, 0x08, 0x96, 0x4c, 0xad, 0xf5, 0x86, 0x43, 0x33, 0x39, 0x2e, 0xa9, 0x30, 0xda,
	0xdb, 0xb0, 0x4a, 0xb3, 0x48, 0x48, 0x96, 0x08, 0x1a, 0x95, 0xc9, 0x85, 0x81, 0x45, 0x21, 0xcb,
	0x1f, 0x66, 0xd5, 0x53, 0x6c, 0x9c, 0x06, 0xfe, 0x7d, 0xf6, 0x84, 0xdc, 0xaf, 0x64, 0xd4, 0x6c,
	0xa8, 0x1d, 0xe8, 0xa3, 0x21, 0xaf, 0xca, 0x44, 0x63, 0xaf, 0x1d, 0xac, 0x4f, 0xba, 0x7c, 0x62,
	0x16, 0xea, 0x5d, 0x87, 0xc7, 0x60, 0xa2, 0x5b, 0x70, 0x60, 0x10, 0x3f, 0xe1, 0x15, 0xb6, 0xb2,
	0xab, 0x12, 0x9f, 0xcd, 0x1e, 0x09, 0x9d, 0xf8, 0x0d, 0xaf, 0xa4, 0xb9, 0x67, 0x4f, 0x65, 0xd9,
	0xfb, 0x0e, 0xfa, 0x13, 0xb6, 0x3e, 0x74, 0xce, 0x4e, 0x8f, 0x4f, 0xdc, 0x77, 0xc8, 0x00, 0x27,
	0xfa, 0xd3, 0xd9, 0xe9, 0x03, 0x7c, 0x70, 0xea, 0xf0, 0xcf, 0xf7, 0x46, 0xc7, 0x6e, 0x8b, 0xf4,
	0xa0, 0x35, 0x3a, 0x74, 0xdb, 0xf5, 0xff, 0xa3, 0xbb, 0x6e, 0xe7, 0xe0, 0x9f, 0x2e, 0xac, 0xda,
	0x50, 0x82, 0x30, 0xe8, 0xe9, 0x53, 0x46, 0xfc, 0xb9, 0xf7, 0xdd, 0xcc, 0x11, 0xf4, 0x6e, 0x35,
	0x9c, 0xbf, 0x72, 0x96, 0x36, 0xd5, 0xf8, 0xbb, 0xcf, 0x5f, 0xfc, 0xf7, 0x6f, 0xeb, 0x13, 0xcf,
	0x0b, 0x8d, 0x43, 0xf8, 0xdb, 0x97, 0xc1, 0x57, 0xa1, 0x5d, 0xc1, 0xb7, 0xce, 0x1e, 0x79, 0xee,
	0x40, 0xbf, 0xb9, 0x9c, 0xc9, 0xa7, 0x73, 0xb3, 0xbd, 0x74, 0xd1, 0x7b, 0xbb, 0xaf, 0x51, 0x19,
	0x80, 0xcf, 0x15, 0xc0, 0x0e, 0xd9, 0xbe, 0x19, 0x20, 0x7c, 0x56, 0x7f, 0x31, 0xae, 0xc9, 0x5f,
	0x0e, 0x2c, 0x1b, 0x2f, 0xa4, 0xd8, 0x9a, 0xeb, 0x6f, 0xdd, 0xa2, 0x37, 0x54, 0x7c, 0xa8, 0x12,
	0x7e, 0xef, 0x7d, 0xb3, 0x28, 0xa1, 0x7d, 0xe9, 0x5d, 0x87, 0xcf, 0xac, 0x0d, 0x73, 0x5d, 0xb7,
	0x03, 0x49, 0x06, 0x67, 0xf9, 0x94, 0x65, 0x7b, 0x7e, 0xff, 0xad, 0x9b, 0xf4, 0x06, 0x98, 0x1f,
	0x14, 0xcc, 0x9d, 0xbd, 0xb7, 0x85, 0x21, 0x57, 0xcd, 0xf5, 0x38, 0xbf, 0x1d, 0xd6, 0x91, 0xf1,
	0xb6, 0x17, 0x28, 0x0c, 0xce, 0xbe, 0xc2, 0xd9, 0xf5, 0xb7, 0x16, 0xe0, 0xa8, 0xaf, 0x1f, 0x36,
	0x21, 0xee, 0xa9, 0xef, 0xfd, 0xd7, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x62, 0xee, 0x17,
	0x44, 0x08, 0x00, 0x00,
}
