// Code generated by protoc-gen-go.
// source: subscription.proto
// DO NOT EDIT!

package billing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Resource int32

const (
	Resource_USER    Resource = 0
	Resource_CLUSTER Resource = 1
	Resource_NODE    Resource = 2
	Resource_DB      Resource = 3
	Resource_CI      Resource = 4
)

var Resource_name = map[int32]string{
	0: "USER",
	1: "CLUSTER",
	2: "NODE",
	3: "DB",
	4: "CI",
}
var Resource_value = map[string]int32{
	"USER":    0,
	"CLUSTER": 1,
	"NODE":    2,
	"DB":      3,
	"CI":      4,
}

func (x Resource) String() string {
	return proto.EnumName(Resource_name, int32(x))
}
func (Resource) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type SubscriptionCreateRequest struct {
	Phid string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
}

func (m *SubscriptionCreateRequest) Reset()                    { *m = SubscriptionCreateRequest{} }
func (m *SubscriptionCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionCreateRequest) ProtoMessage()               {}
func (*SubscriptionCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type SubscriptionDescribeRequest struct {
}

func (m *SubscriptionDescribeRequest) Reset()                    { *m = SubscriptionDescribeRequest{} }
func (m *SubscriptionDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionDescribeRequest) ProtoMessage()               {}
func (*SubscriptionDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type SubscriptionDescribeResponse struct {
	Status        *dtypes.Status  `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Subscriptions []*Subscription `protobuf:"bytes,2,rep,name=subscriptions" json:"subscriptions,omitempty"`
}

func (m *SubscriptionDescribeResponse) Reset()                    { *m = SubscriptionDescribeResponse{} }
func (m *SubscriptionDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionDescribeResponse) ProtoMessage()               {}
func (*SubscriptionDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *SubscriptionDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SubscriptionDescribeResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type Subscription struct {
	Author       string `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Type         string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	ProductSku   string `protobuf:"bytes,3,opt,name=product_sku" json:"product_sku,omitempty"`
	PricingModel string `protobuf:"bytes,4,opt,name=pricing_model" json:"pricing_model,omitempty"`
	ProductType  string `protobuf:"bytes,5,opt,name=product_type" json:"product_type,omitempty"`
	Quota        *Quota `protobuf:"bytes,6,opt,name=quota" json:"quota,omitempty"`
	DateStarted  string `protobuf:"bytes,7,opt,name=date_started" json:"date_started,omitempty"`
	DateEnded    string `protobuf:"bytes,8,opt,name=date_ended" json:"date_ended,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *Subscription) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

type Quota struct {
	User        int64             `protobuf:"varint,1,opt,name=user" json:"user,omitempty"`
	Phabricator *PhabricatorQuota `protobuf:"bytes,2,opt,name=phabricator" json:"phabricator,omitempty"`
	Artifact    *ArtifactoryQuota `protobuf:"bytes,3,opt,name=artifact" json:"artifact,omitempty"`
	Kube        *ClusterQuota     `protobuf:"bytes,4,opt,name=kube" json:"kube,omitempty"`
	Ci          *CIQuota          `protobuf:"bytes,5,opt,name=ci" json:"ci,omitempty"`
	Db          *DBQuota          `protobuf:"bytes,6,opt,name=db" json:"db,omitempty"`
}

func (m *Quota) Reset()                    { *m = Quota{} }
func (m *Quota) String() string            { return proto.CompactTextString(m) }
func (*Quota) ProtoMessage()               {}
func (*Quota) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *Quota) GetPhabricator() *PhabricatorQuota {
	if m != nil {
		return m.Phabricator
	}
	return nil
}

func (m *Quota) GetArtifact() *ArtifactoryQuota {
	if m != nil {
		return m.Artifact
	}
	return nil
}

func (m *Quota) GetKube() *ClusterQuota {
	if m != nil {
		return m.Kube
	}
	return nil
}

func (m *Quota) GetCi() *CIQuota {
	if m != nil {
		return m.Ci
	}
	return nil
}

func (m *Quota) GetDb() *DBQuota {
	if m != nil {
		return m.Db
	}
	return nil
}

type PhabricatorQuota struct {
	DiskSize   int64 `protobuf:"varint,1,opt,name=disk_size" json:"disk_size,omitempty"`
	Repository int64 `protobuf:"varint,2,opt,name=repository" json:"repository,omitempty"`
}

func (m *PhabricatorQuota) Reset()                    { *m = PhabricatorQuota{} }
func (m *PhabricatorQuota) String() string            { return proto.CompactTextString(m) }
func (*PhabricatorQuota) ProtoMessage()               {}
func (*PhabricatorQuota) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

type CIQuota struct {
	Agent     int64 `protobuf:"varint,1,opt,name=agent" json:"agent,omitempty"`
	Executors int64 `protobuf:"varint,2,opt,name=executors" json:"executors,omitempty"`
	Jobs      int64 `protobuf:"varint,3,opt,name=jobs" json:"jobs,omitempty"`
}

func (m *CIQuota) Reset()                    { *m = CIQuota{} }
func (m *CIQuota) String() string            { return proto.CompactTextString(m) }
func (*CIQuota) ProtoMessage()               {}
func (*CIQuota) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

type ArtifactoryQuota struct {
	DiskSize   int64 `protobuf:"varint,1,opt,name=disk_size" json:"disk_size,omitempty"`
	Repository int64 `protobuf:"varint,2,opt,name=repository" json:"repository,omitempty"`
}

func (m *ArtifactoryQuota) Reset()                    { *m = ArtifactoryQuota{} }
func (m *ArtifactoryQuota) String() string            { return proto.CompactTextString(m) }
func (*ArtifactoryQuota) ProtoMessage()               {}
func (*ArtifactoryQuota) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

type ClusterQuota struct {
	Cluster int64 `protobuf:"varint,1,opt,name=cluster" json:"cluster,omitempty"`
	Nodes   int64 `protobuf:"varint,2,opt,name=nodes" json:"nodes,omitempty"`
}

func (m *ClusterQuota) Reset()                    { *m = ClusterQuota{} }
func (m *ClusterQuota) String() string            { return proto.CompactTextString(m) }
func (*ClusterQuota) ProtoMessage()               {}
func (*ClusterQuota) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

type DBQuota struct {
	Postgres      int64 `protobuf:"varint,1,opt,name=postgres" json:"postgres,omitempty"`
	Elasticsearch int64 `protobuf:"varint,2,opt,name=elasticsearch" json:"elasticsearch,omitempty"`
	Influxdb      int64 `protobuf:"varint,3,opt,name=influxdb" json:"influxdb,omitempty"`
}

func (m *DBQuota) Reset()                    { *m = DBQuota{} }
func (m *DBQuota) String() string            { return proto.CompactTextString(m) }
func (*DBQuota) ProtoMessage()               {}
func (*DBQuota) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

type SubscriptionQoutaRequest struct {
	Resource    Resource `protobuf:"varint,1,opt,name=resource,enum=billing.Resource" json:"resource,omitempty"`
	Subresource string   `protobuf:"bytes,2,opt,name=subresource" json:"subresource,omitempty"`
	ObjectPhid  string   `protobuf:"bytes,3,opt,name=object_phid" json:"object_phid,omitempty"`
	Count       int64    `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
}

func (m *SubscriptionQoutaRequest) Reset()                    { *m = SubscriptionQoutaRequest{} }
func (m *SubscriptionQoutaRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionQoutaRequest) ProtoMessage()               {}
func (*SubscriptionQoutaRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

type SubscriptionQutaResponse struct {
	Status      *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	ProductPhid string         `protobuf:"bytes,3,opt,name=product_phid" json:"product_phid,omitempty"`
}

func (m *SubscriptionQutaResponse) Reset()                    { *m = SubscriptionQutaResponse{} }
func (m *SubscriptionQutaResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionQutaResponse) ProtoMessage()               {}
func (*SubscriptionQutaResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *SubscriptionQutaResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscriptionCreateRequest)(nil), "billing.SubscriptionCreateRequest")
	proto.RegisterType((*SubscriptionDescribeRequest)(nil), "billing.SubscriptionDescribeRequest")
	proto.RegisterType((*SubscriptionDescribeResponse)(nil), "billing.SubscriptionDescribeResponse")
	proto.RegisterType((*Subscription)(nil), "billing.Subscription")
	proto.RegisterType((*Quota)(nil), "billing.Quota")
	proto.RegisterType((*PhabricatorQuota)(nil), "billing.PhabricatorQuota")
	proto.RegisterType((*CIQuota)(nil), "billing.CIQuota")
	proto.RegisterType((*ArtifactoryQuota)(nil), "billing.ArtifactoryQuota")
	proto.RegisterType((*ClusterQuota)(nil), "billing.ClusterQuota")
	proto.RegisterType((*DBQuota)(nil), "billing.DBQuota")
	proto.RegisterType((*SubscriptionQoutaRequest)(nil), "billing.SubscriptionQoutaRequest")
	proto.RegisterType((*SubscriptionQutaResponse)(nil), "billing.SubscriptionQutaResponse")
	proto.RegisterEnum("billing.Resource", Resource_name, Resource_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Subscriptions service

type SubscriptionsClient interface {
	Create(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Alter(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Describe(ctx context.Context, in *SubscriptionDescribeRequest, opts ...grpc.CallOption) (*SubscriptionDescribeResponse, error)
	Quota(ctx context.Context, in *SubscriptionQoutaRequest, opts ...grpc.CallOption) (*SubscriptionQutaResponse, error)
}

type subscriptionsClient struct {
	cc *grpc.ClientConn
}

func NewSubscriptionsClient(cc *grpc.ClientConn) SubscriptionsClient {
	return &subscriptionsClient{cc}
}

func (c *subscriptionsClient) Create(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) Alter(ctx context.Context, in *SubscriptionCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Alter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) Describe(ctx context.Context, in *SubscriptionDescribeRequest, opts ...grpc.CallOption) (*SubscriptionDescribeResponse, error) {
	out := new(SubscriptionDescribeResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) Quota(ctx context.Context, in *SubscriptionQoutaRequest, opts ...grpc.CallOption) (*SubscriptionQutaResponse, error) {
	out := new(SubscriptionQutaResponse)
	err := grpc.Invoke(ctx, "/billing.Subscriptions/Quota", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Subscriptions service

type SubscriptionsServer interface {
	Create(context.Context, *SubscriptionCreateRequest) (*dtypes.VoidResponse, error)
	Alter(context.Context, *SubscriptionCreateRequest) (*dtypes.VoidResponse, error)
	Describe(context.Context, *SubscriptionDescribeRequest) (*SubscriptionDescribeResponse, error)
	Quota(context.Context, *SubscriptionQoutaRequest) (*SubscriptionQutaResponse, error)
}

func RegisterSubscriptionsServer(s *grpc.Server, srv SubscriptionsServer) {
	s.RegisterService(&_Subscriptions_serviceDesc, srv)
}

func _Subscriptions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Create(ctx, req.(*SubscriptionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_Alter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Alter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Alter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Alter(ctx, req.(*SubscriptionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Describe(ctx, req.(*SubscriptionDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_Quota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionQoutaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Quota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.Subscriptions/Quota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Quota(ctx, req.(*SubscriptionQoutaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Subscriptions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Subscriptions",
	HandlerType: (*SubscriptionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Subscriptions_Create_Handler,
		},
		{
			MethodName: "Alter",
			Handler:    _Subscriptions_Alter_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Subscriptions_Describe_Handler,
		},
		{
			MethodName: "Quota",
			Handler:    _Subscriptions_Quota_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor3 = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x53, 0x13, 0x4d,
	0x10, 0x7e, 0xf3, 0x1d, 0x3a, 0x09, 0xef, 0x32, 0x2f, 0xbc, 0x15, 0x22, 0x58, 0xb8, 0x68, 0x29,
	0x88, 0x1b, 0x8d, 0x17, 0x3f, 0x4e, 0x40, 0x38, 0x50, 0x65, 0x29, 0x10, 0xf1, 0x9a, 0xda, 0x8f,
	0x21, 0x59, 0x58, 0x77, 0x96, 0x9d, 0x59, 0x0a, 0xf4, 0xe6, 0x45, 0xef, 0x9e, 0xfc, 0x25, 0xfe,
	0x10, 0xfe, 0x82, 0x3f, 0xc4, 0x9e, 0xd9, 0xdd, 0x64, 0x81, 0x58, 0xc6, 0xf2, 0x92, 0x64, 0x7b,
	0x9e, 0xee, 0xe7, 0x79, 0x7a, 0x7b, 0x3a, 0x40, 0x78, 0x64, 0x71, 0x3b, 0x74, 0x03, 0xe1, 0x32,
	0xdf, 0x08, 0x42, 0x26, 0x18, 0xa9, 0x58, 0xae, 0xe7, 0xb9, 0xfe, 0xa0, 0xb5, 0x34, 0x60, 0x6c,
	0xe0, 0xd1, 0xb6, 0x19, 0xb8, 0x6d, 0xd3, 0xf7, 0x99, 0x30, 0x25, 0x8a, 0xc7, 0xb0, 0xd6, 0xff,
	0x32, 0xec, 0x88, 0x8b, 0x80, 0xf2, 0xb6, 0xfa, 0x8c, 0xe3, 0xfa, 0x1a, 0x2c, 0xf6, 0x32, 0x45,
	0xb7, 0x43, 0x6a, 0x0a, 0x7a, 0x40, 0x4f, 0x23, 0xca, 0x05, 0xa9, 0x43, 0x31, 0x18, 0xba, 0x4e,
	0x33, 0xb7, 0x92, 0x7b, 0x30, 0xa3, 0x2f, 0xc3, 0xad, 0x2c, 0xb4, 0x4b, 0xe5, 0x4f, 0x2b, 0x05,
	0xeb, 0x1e, 0x2c, 0x4d, 0x3e, 0xe6, 0x01, 0xca, 0xa0, 0xe4, 0x36, 0x94, 0x39, 0x6a, 0x8a, 0xb8,
	0x2a, 0x57, 0xeb, 0xcc, 0x1a, 0xb1, 0x1c, 0xa3, 0xa7, 0xa2, 0x64, 0x03, 0x1a, 0x59, 0x7b, 0xbc,
	0x99, 0x5f, 0x29, 0x20, 0x6c, 0xc1, 0x48, 0x0c, 0x1a, 0xd9, 0xea, 0xfa, 0xf7, 0x1c, 0xd4, 0xb3,
	0x01, 0x32, 0x0b, 0x65, 0x33, 0x12, 0x43, 0x16, 0xc6, 0x6a, 0xa5, 0x76, 0x59, 0x1e, 0xab, 0xc8,
	0xa7, 0xff, 0xa0, 0x86, 0x7e, 0x9d, 0xc8, 0x16, 0x7d, 0x7e, 0x12, 0x35, 0x0b, 0x2a, 0xb8, 0x00,
	0x8d, 0x20, 0x74, 0x6d, 0xac, 0xdd, 0x7f, 0xcf, 0x1c, 0xea, 0x35, 0x8b, 0x2a, 0x3c, 0x0f, 0xf5,
	0x14, 0xab, 0x2a, 0x94, 0x54, 0x74, 0x19, 0x4a, 0xa7, 0x11, 0x36, 0xb5, 0x59, 0x4e, 0xd4, 0xa7,
	0xb2, 0xf6, 0x65, 0x54, 0x26, 0x39, 0xd8, 0xb9, 0x3e, 0x5a, 0x0c, 0x05, 0x75, 0x9a, 0x15, 0x95,
	0x44, 0x00, 0x54, 0x94, 0xfa, 0x0e, 0xc6, 0xaa, 0xaa, 0x8d, 0x97, 0x39, 0x28, 0xc5, 0x39, 0x28,
	0x31, 0xe2, 0x34, 0x16, 0x5c, 0x20, 0x06, 0x4a, 0x1c, 0x9a, 0x16, 0x0a, 0x32, 0x05, 0xba, 0xc8,
	0x2b, 0x9a, 0xc5, 0x11, 0xcd, 0xde, 0xf8, 0x2c, 0xce, 0x7e, 0x08, 0x55, 0xa4, 0x72, 0x8f, 0x4c,
	0x5b, 0x28, 0x3f, 0x59, 0xf0, 0x66, 0x72, 0xc0, 0xc2, 0x8b, 0x18, 0xbc, 0x0a, 0xc5, 0x93, 0xc8,
	0xa2, 0xca, 0x61, 0xb6, 0xa7, 0xdb, 0x5e, 0xc4, 0x05, 0x4d, 0x2a, 0x2e, 0x41, 0xde, 0x76, 0x95,
	0xdd, 0x5a, 0x47, 0x1b, 0x43, 0x76, 0x47, 0xa7, 0x8e, 0x95, 0xb8, 0x1f, 0x9f, 0x76, 0xb7, 0xd4,
	0xa9, 0xfe, 0x1c, 0xb4, 0x1b, 0x0a, 0xe7, 0x60, 0xc6, 0x71, 0xf9, 0x49, 0x9f, 0xbb, 0x1f, 0x68,
	0x62, 0x12, 0x1b, 0x12, 0xd2, 0x80, 0x71, 0x57, 0x4a, 0x53, 0x1e, 0x0b, 0x98, 0x5a, 0x49, 0x39,
	0x1a, 0x50, 0x32, 0x07, 0xd4, 0x17, 0x09, 0x1a, 0x0b, 0xd0, 0x73, 0x6a, 0x47, 0x08, 0xe6, 0x31,
	0x58, 0xf6, 0xec, 0x98, 0x59, 0x5c, 0x39, 0x96, 0xa9, 0xda, 0x0d, 0xab, 0x53, 0xb2, 0x1a, 0x50,
	0xbf, 0x62, 0xfe, 0x5f, 0xa8, 0xd8, 0xf1, 0x73, 0x92, 0x84, 0x5a, 0x7c, 0x9c, 0x8a, 0x84, 0x58,
	0xef, 0x42, 0x25, 0xf1, 0x4a, 0x34, 0xa8, 0x62, 0x31, 0x31, 0x08, 0x29, 0x4f, 0xb0, 0x38, 0x49,
	0xd4, 0x33, 0xb9, 0x70, 0x6d, 0x4e, 0xcd, 0xd0, 0x1e, 0x26, 0x62, 0x11, 0xe8, 0xfa, 0x47, 0x5e,
	0x74, 0x8e, 0x8d, 0x8b, 0x05, 0x9f, 0x43, 0x33, 0x3b, 0xb5, 0xfb, 0x2c, 0x12, 0x66, 0x7a, 0xdb,
	0x56, 0xa1, 0x8a, 0x15, 0x59, 0x14, 0xda, 0xb1, 0xee, 0xd9, 0xce, 0xdc, 0xa8, 0xcd, 0x07, 0xc9,
	0x81, 0x1c, 0x64, 0xbc, 0x25, 0x23, 0xdc, 0x68, 0xba, 0x99, 0x75, 0x4c, 0x71, 0x60, 0xd5, 0x75,
	0x8d, 0xa7, 0x1b, 0xf5, 0xdb, 0x2c, 0xc2, 0x5e, 0x96, 0x14, 0xf3, 0xde, 0x35, 0x66, 0x45, 0x3c,
	0xe5, 0xd5, 0xcc, 0xdc, 0x88, 0x31, 0xc1, 0xfa, 0x4b, 0xa8, 0x8e, 0x64, 0x55, 0xa1, 0x78, 0xd8,
	0xdb, 0x39, 0xd0, 0xfe, 0x21, 0x35, 0x7c, 0x9b, 0xaf, 0x0e, 0x7b, 0x6f, 0xf1, 0x21, 0x27, 0xc3,
	0xaf, 0xdf, 0x74, 0x77, 0xb4, 0x3c, 0x29, 0x43, 0xbe, 0xbb, 0xa5, 0x15, 0xe4, 0xf7, 0xf6, 0xae,
	0x56, 0xec, 0x7c, 0x2b, 0x42, 0x23, 0xab, 0x87, 0x93, 0x33, 0x28, 0xc7, 0xdb, 0x87, 0xe8, 0x13,
	0xaf, 0xfc, 0x95, 0xd5, 0xd4, 0x9a, 0x4f, 0x25, 0xbe, 0x63, 0xae, 0x93, 0x1a, 0xd1, 0x3b, 0x9f,
	0x2e, 0x7f, 0x7c, 0xcd, 0x6f, 0xb4, 0xee, 0xe3, 0x16, 0x0c, 0xb8, 0x8d, 0xaf, 0x4f, 0xad, 0xc3,
	0xa4, 0x5c, 0xfb, 0xec, 0xb1, 0xf1, 0xa4, 0x9d, 0x5d, 0x32, 0x2f, 0x72, 0xeb, 0xe4, 0x23, 0x94,
	0x36, 0x3d, 0x7c, 0xed, 0x7f, 0x41, 0xfb, 0x4c, 0xd1, 0x76, 0xf4, 0x47, 0x53, 0xd2, 0xb6, 0x4d,
	0x49, 0x28, 0xc9, 0xbf, 0xe4, 0xa0, 0x9a, 0x6e, 0x4a, 0x72, 0x77, 0xa2, 0x80, 0x6b, 0x7b, 0xb6,
	0x75, 0xef, 0x37, 0xa8, 0x44, 0x53, 0x5b, 0x69, 0x5a, 0x23, 0xd3, 0xb6, 0x82, 0x7c, 0x1e, 0xed,
	0xa5, 0x3b, 0x13, 0x19, 0xb2, 0xb3, 0xda, 0xfa, 0x05, 0x24, 0x33, 0x54, 0x7f, 0xde, 0x14, 0xb5,
	0x5e, 0xb1, 0x29, 0x56, 0x59, 0xfd, 0x35, 0x3d, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x85, 0x25,
	0x8c, 0x5b, 0xef, 0x06, 0x00, 0x00,
}
