// Code generated by protoc-gen-go.
// source: build.proto
// DO NOT EDIT!

/*
Package ci is a generated protocol buffer package.

It is generated from these files:
	build.proto
	job.proto
	master.proto
	slave.proto

It has these top-level messages:
	BuildDescribeRequest
	BuildDescribeResponse
	BuildListRequest
	BuildListResponse
	Build
	JobListResponse
	JobBuildRequest
	JobDescribeRequest
	JobDescribeResponse
	JobDeleteRequest
	JobCreateRequest
	JobCopyRequest
	Job
	MasterCreateRequest
	MasterCreateResponse
	SlaveListResponse
	Slave
	SlaveCreateRequest
	SlaveDescribeRequest
	SlaveDescribeResponse
	SlaveDeleteRequest
	SlaveRestartRequest
	SlaveRestartResponse
*/
package ci

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type BuildDescribeRequest struct {
	JobName string `protobuf:"bytes,1,opt,name=job_name" json:"job_name,omitempty"`
	Number  int64  `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	Console string `protobuf:"bytes,3,opt,name=console" json:"console,omitempty"`
}

func (m *BuildDescribeRequest) Reset()                    { *m = BuildDescribeRequest{} }
func (m *BuildDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*BuildDescribeRequest) ProtoMessage()               {}
func (*BuildDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BuildDescribeResponse struct {
	Status        *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	BuildNumber   int64          `protobuf:"varint,2,opt,name=build_number" json:"build_number,omitempty"`
	JobName       string         `protobuf:"bytes,3,opt,name=job_name" json:"job_name,omitempty"`
	BaseUrl       string         `protobuf:"bytes,4,opt,name=base_url" json:"base_url,omitempty"`
	Result        string         `protobuf:"bytes,5,opt,name=result" json:"result,omitempty"`
	ConsoleOutput string         `protobuf:"bytes,6,opt,name=console_output" json:"console_output,omitempty"`
}

func (m *BuildDescribeResponse) Reset()                    { *m = BuildDescribeResponse{} }
func (m *BuildDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildDescribeResponse) ProtoMessage()               {}
func (*BuildDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BuildDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type BuildListRequest struct {
	JobName string `protobuf:"bytes,1,opt,name=job_name" json:"job_name,omitempty"`
}

func (m *BuildListRequest) Reset()                    { *m = BuildListRequest{} }
func (m *BuildListRequest) String() string            { return proto.CompactTextString(m) }
func (*BuildListRequest) ProtoMessage()               {}
func (*BuildListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BuildListResponse struct {
	Status  *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	JobName string         `protobuf:"bytes,2,opt,name=job_name" json:"job_name,omitempty"`
	Builds  []*Build       `protobuf:"bytes,3,rep,name=builds" json:"builds,omitempty"`
}

func (m *BuildListResponse) Reset()                    { *m = BuildListResponse{} }
func (m *BuildListResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildListResponse) ProtoMessage()               {}
func (*BuildListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BuildListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BuildListResponse) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type Build struct {
	BuildNumber int64  `protobuf:"varint,1,opt,name=build_number" json:"build_number,omitempty"`
	Result      string `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *Build) Reset()                    { *m = Build{} }
func (m *Build) String() string            { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()               {}
func (*Build) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*BuildDescribeRequest)(nil), "ci.BuildDescribeRequest")
	proto.RegisterType((*BuildDescribeResponse)(nil), "ci.BuildDescribeResponse")
	proto.RegisterType((*BuildListRequest)(nil), "ci.BuildListRequest")
	proto.RegisterType((*BuildListResponse)(nil), "ci.BuildListResponse")
	proto.RegisterType((*Build)(nil), "ci.Build")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Builds service

type BuildsClient interface {
	Describe(ctx context.Context, in *BuildDescribeRequest, opts ...grpc.CallOption) (*BuildDescribeResponse, error)
	List(ctx context.Context, in *BuildListRequest, opts ...grpc.CallOption) (*BuildListResponse, error)
}

type buildsClient struct {
	cc *grpc.ClientConn
}

func NewBuildsClient(cc *grpc.ClientConn) BuildsClient {
	return &buildsClient{cc}
}

func (c *buildsClient) Describe(ctx context.Context, in *BuildDescribeRequest, opts ...grpc.CallOption) (*BuildDescribeResponse, error) {
	out := new(BuildDescribeResponse)
	err := grpc.Invoke(ctx, "/ci.Builds/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildsClient) List(ctx context.Context, in *BuildListRequest, opts ...grpc.CallOption) (*BuildListResponse, error) {
	out := new(BuildListResponse)
	err := grpc.Invoke(ctx, "/ci.Builds/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Builds service

type BuildsServer interface {
	Describe(context.Context, *BuildDescribeRequest) (*BuildDescribeResponse, error)
	List(context.Context, *BuildListRequest) (*BuildListResponse, error)
}

func RegisterBuildsServer(s *grpc.Server, srv BuildsServer) {
	s.RegisterService(&_Builds_serviceDesc, srv)
}

func _Builds_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BuildDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BuildsServer).Describe(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Builds_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BuildListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BuildsServer).List(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Builds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ci.Builds",
	HandlerType: (*BuildsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Builds_Describe_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Builds_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0xd3, 0x02, 0x15, 0x2e, 0x06, 0x71, 0x02, 0xa4, 0x34, 0x84, 0x98, 0x06, 0xa3, 0x1b,
	0x5a, 0x83, 0x6f, 0x60, 0xdc, 0x98, 0xb8, 0xd2, 0x95, 0xab, 0xda, 0x96, 0x09, 0x19, 0x53, 0x3a,
	0xb5, 0x33, 0x63, 0x62, 0x08, 0x1b, 0x5f, 0xc1, 0x95, 0xcf, 0xc5, 0x2b, 0xf8, 0x20, 0xb6, 0xb7,
	0x80, 0x15, 0x7f, 0xe2, 0x86, 0x30, 0xb7, 0xa7, 0xe7, 0x7c, 0xe7, 0x76, 0xa0, 0x19, 0x28, 0x16,
	0x4d, 0x9d, 0x24, 0xe5, 0x92, 0x13, 0x3d, 0x64, 0xd6, 0x60, 0xc6, 0xf9, 0x2c, 0xa2, 0xae, 0x9f,
	0x30, 0xd7, 0x8f, 0x63, 0x2e, 0x7d, 0xc9, 0x78, 0x2c, 0x0a, 0x85, 0xd5, 0xcb, 0xc7, 0x53, 0xf9,
	0x9c, 0x50, 0xe1, 0xe2, 0x6f, 0x31, 0xb7, 0xaf, 0xa0, 0x73, 0x91, 0x1b, 0x5d, 0x52, 0x11, 0xa6,
	0x2c, 0xa0, 0x37, 0xf4, 0x51, 0x51, 0x21, 0x49, 0x1b, 0xea, 0x0f, 0x3c, 0xf0, 0x62, 0x7f, 0x4e,
	0x4d, 0xed, 0x48, 0x3b, 0x6d, 0x90, 0x16, 0x18, 0xb1, 0x9a, 0x07, 0x34, 0x35, 0xf5, 0xec, 0x5c,
	0x21, 0x07, 0xb0, 0x17, 0x66, 0xfe, 0x3c, 0xa2, 0x66, 0x25, 0x17, 0xd8, 0x6f, 0x1a, 0x74, 0x77,
	0xbc, 0x44, 0x92, 0x29, 0x28, 0x19, 0x82, 0x21, 0x32, 0x1c, 0x25, 0xd0, 0xaa, 0x39, 0x69, 0x39,
	0x05, 0x89, 0x73, 0x8b, 0x53, 0xd2, 0x81, 0x7d, 0x6c, 0xe3, 0x7d, 0x09, 0x28, 0x23, 0x60, 0x42,
	0x3e, 0x09, 0x7c, 0x41, 0x3d, 0x95, 0x46, 0x66, 0x75, 0x03, 0x95, 0x52, 0xa1, 0x22, 0x69, 0xd6,
	0xf0, 0xdc, 0x83, 0xd6, 0x1a, 0xca, 0xe3, 0x4a, 0x26, 0x4a, 0x9a, 0x06, 0xb2, 0x8d, 0xa0, 0x8d,
	0x68, 0xd7, 0x4c, 0xc8, 0x5f, 0x2b, 0xda, 0xf7, 0x70, 0x58, 0x52, 0xfd, 0x13, 0xbe, 0x6c, 0xa3,
	0x23, 0x44, 0x1f, 0x0c, 0xac, 0x23, 0x32, 0xec, 0x4a, 0xf6, 0x46, 0xc3, 0x09, 0x99, 0x83, 0xc6,
	0xf6, 0x18, 0x6a, 0xf8, 0xe7, 0x5b, 0x65, 0x0d, 0x2b, 0x7f, 0xd6, 0x41, 0xa7, 0xc9, 0x4a, 0x03,
	0x03, 0xf5, 0x82, 0xc4, 0x50, 0xdf, 0xec, 0x95, 0x98, 0x5b, 0xc3, 0x9d, 0xcf, 0x66, 0xf5, 0x7f,
	0x78, 0x52, 0xf4, 0xb0, 0xc7, 0x2f, 0xab, 0xf7, 0x57, 0xfd, 0x84, 0x1c, 0xe3, 0x0d, 0x09, 0x99,
	0xfb, 0x74, 0xe6, 0x16, 0x98, 0xee, 0x62, 0x53, 0x60, 0xe9, 0x2e, 0x0a, 0x9e, 0x25, 0xb9, 0x83,
	0x6a, 0xbe, 0x06, 0xd2, 0xd9, 0x3a, 0x96, 0x76, 0x67, 0x75, 0x77, 0xa6, 0xeb, 0x8c, 0x11, 0x66,
	0x0c, 0xc9, 0xe0, 0xaf, 0x8c, 0xc0, 0xc0, 0xab, 0x77, 0xfe, 0x11, 0x00, 0x00, 0xff, 0xff, 0x11,
	0x47, 0xae, 0x07, 0xc3, 0x02, 0x00, 0x00,
}
