// Code generated by protoc-gen-go.
// source: slave.proto
// DO NOT EDIT!

package ci

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SlaveType int32

const (
	SlaveType_ALL       SlaveType = 0
	SlaveType_CRETAED   SlaveType = 1
	SlaveType_DELETED   SlaveType = 2
	SlaveType_REFRESHED SlaveType = 3
)

var SlaveType_name = map[int32]string{
	0: "ALL",
	1: "CRETAED",
	2: "DELETED",
	3: "REFRESHED",
}
var SlaveType_value = map[string]int32{
	"ALL":       0,
	"CRETAED":   1,
	"DELETED":   2,
	"REFRESHED": 3,
}

func (x SlaveType) String() string {
	return proto.EnumName(SlaveType_name, int32(x))
}
func (SlaveType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type SlaveListRequest struct {
	From string    `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To   string    `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Type SlaveType `protobuf:"varint,3,opt,name=type,enum=ci.SlaveType" json:"type,omitempty"`
}

func (m *SlaveListRequest) Reset()                    { *m = SlaveListRequest{} }
func (m *SlaveListRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveListRequest) ProtoMessage()               {}
func (*SlaveListRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type SlaveListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Slaves []*Slave       `protobuf:"bytes,2,rep,name=slaves" json:"slaves,omitempty"`
}

func (m *SlaveListResponse) Reset()                    { *m = SlaveListResponse{} }
func (m *SlaveListResponse) String() string            { return proto.CompactTextString(m) }
func (*SlaveListResponse) ProtoMessage()               {}
func (*SlaveListResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *SlaveListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SlaveListResponse) GetSlaves() []*Slave {
	if m != nil {
		return m.Slaves
	}
	return nil
}

type Slave struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Status      string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	IsDeleted   bool   `protobuf:"varint,3,opt,name=is_deleted" json:"is_deleted,omitempty"`
	IsRefreshed bool   `protobuf:"varint,4,opt,name=is_refreshed" json:"is_refreshed,omitempty"`
	CreatedAt   string `protobuf:"bytes,5,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,6,opt,name=updated_at" json:"updated_at,omitempty"`
}

func (m *Slave) Reset()                    { *m = Slave{} }
func (m *Slave) String() string            { return proto.CompactTextString(m) }
func (*Slave) ProtoMessage()               {}
func (*Slave) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type SlaveCreateRequest struct {
	Sku               string      `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`
	Executors         int32       `protobuf:"varint,2,opt,name=executors" json:"executors,omitempty"`
	Labels            string      `protobuf:"bytes,3,opt,name=labels" json:"labels,omitempty"`
	UserStartupScript string      `protobuf:"bytes,4,opt,name=user_startup_script" json:"user_startup_script,omitempty"`
	SaltbaseVersion   string      `protobuf:"bytes,5,opt,name=saltbase_version" json:"saltbase_version,omitempty"`
	CiStarterVersion  string      `protobuf:"bytes,6,opt,name=ci_starter_version" json:"ci_starter_version,omitempty"`
	Ports             []*PortInfo `protobuf:"bytes,7,rep,name=ports" json:"ports,omitempty"`
	Role              string      `protobuf:"bytes,8,opt,name=role" json:"role,omitempty"`
}

func (m *SlaveCreateRequest) Reset()                    { *m = SlaveCreateRequest{} }
func (m *SlaveCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveCreateRequest) ProtoMessage()               {}
func (*SlaveCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *SlaveCreateRequest) GetPorts() []*PortInfo {
	if m != nil {
		return m.Ports
	}
	return nil
}

type PortInfo struct {
	Protocol  string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	PortRange string `protobuf:"bytes,2,opt,name=port_range" json:"port_range,omitempty"`
}

func (m *PortInfo) Reset()                    { *m = PortInfo{} }
func (m *PortInfo) String() string            { return proto.CompactTextString(m) }
func (*PortInfo) ProtoMessage()               {}
func (*PortInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

type SlaveDescribeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SlaveDescribeRequest) Reset()                    { *m = SlaveDescribeRequest{} }
func (m *SlaveDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveDescribeRequest) ProtoMessage()               {}
func (*SlaveDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

type SlaveDescribeResponse struct {
	Status        *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Name          string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Executors     int64          `protobuf:"varint,3,opt,name=executors" json:"executors,omitempty"`
	NodeStatus    string         `protobuf:"bytes,4,opt,name=node_status" json:"node_status,omitempty"`
	OfflineReason string         `protobuf:"bytes,5,opt,name=offline_reason" json:"offline_reason,omitempty"`
	Label         string         `protobuf:"bytes,6,opt,name=label" json:"label,omitempty"`
	Provider      string         `protobuf:"bytes,7,opt,name=provider" json:"provider,omitempty"`
	Sku           string         `protobuf:"bytes,8,opt,name=sku" json:"sku,omitempty"`
	StartupScript string         `protobuf:"bytes,9,opt,name=startup_script" json:"startup_script,omitempty"`
	CreatedAt     string         `protobuf:"bytes,10,opt,name=created_at" json:"created_at,omitempty"`
}

func (m *SlaveDescribeResponse) Reset()                    { *m = SlaveDescribeResponse{} }
func (m *SlaveDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SlaveDescribeResponse) ProtoMessage()               {}
func (*SlaveDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *SlaveDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SlaveDeleteRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SlaveDeleteRequest) Reset()                    { *m = SlaveDeleteRequest{} }
func (m *SlaveDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveDeleteRequest) ProtoMessage()               {}
func (*SlaveDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

type SlaveRestartRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SlaveRestartRequest) Reset()                    { *m = SlaveRestartRequest{} }
func (m *SlaveRestartRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveRestartRequest) ProtoMessage()               {}
func (*SlaveRestartRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

type SlaveRestartResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SlaveRestartResponse) Reset()                    { *m = SlaveRestartResponse{} }
func (m *SlaveRestartResponse) String() string            { return proto.CompactTextString(m) }
func (*SlaveRestartResponse) ProtoMessage()               {}
func (*SlaveRestartResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *SlaveRestartResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*SlaveListRequest)(nil), "ci.SlaveListRequest")
	proto.RegisterType((*SlaveListResponse)(nil), "ci.SlaveListResponse")
	proto.RegisterType((*Slave)(nil), "ci.Slave")
	proto.RegisterType((*SlaveCreateRequest)(nil), "ci.SlaveCreateRequest")
	proto.RegisterType((*PortInfo)(nil), "ci.PortInfo")
	proto.RegisterType((*SlaveDescribeRequest)(nil), "ci.SlaveDescribeRequest")
	proto.RegisterType((*SlaveDescribeResponse)(nil), "ci.SlaveDescribeResponse")
	proto.RegisterType((*SlaveDeleteRequest)(nil), "ci.SlaveDeleteRequest")
	proto.RegisterType((*SlaveRestartRequest)(nil), "ci.SlaveRestartRequest")
	proto.RegisterType((*SlaveRestartResponse)(nil), "ci.SlaveRestartResponse")
	proto.RegisterEnum("ci.SlaveType", SlaveType_name, SlaveType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Slaves service

type SlavesClient interface {
	List(ctx context.Context, in *SlaveListRequest, opts ...grpc.CallOption) (*SlaveListResponse, error)
	Describe(ctx context.Context, in *SlaveDescribeRequest, opts ...grpc.CallOption) (*SlaveDescribeResponse, error)
	Create(ctx context.Context, in *SlaveCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Delete(ctx context.Context, in *SlaveDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Restart(ctx context.Context, in *SlaveRestartRequest, opts ...grpc.CallOption) (*SlaveRestartResponse, error)
}

type slavesClient struct {
	cc *grpc.ClientConn
}

func NewSlavesClient(cc *grpc.ClientConn) SlavesClient {
	return &slavesClient{cc}
}

func (c *slavesClient) List(ctx context.Context, in *SlaveListRequest, opts ...grpc.CallOption) (*SlaveListResponse, error) {
	out := new(SlaveListResponse)
	err := grpc.Invoke(ctx, "/ci.Slaves/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slavesClient) Describe(ctx context.Context, in *SlaveDescribeRequest, opts ...grpc.CallOption) (*SlaveDescribeResponse, error) {
	out := new(SlaveDescribeResponse)
	err := grpc.Invoke(ctx, "/ci.Slaves/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slavesClient) Create(ctx context.Context, in *SlaveCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/ci.Slaves/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slavesClient) Delete(ctx context.Context, in *SlaveDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/ci.Slaves/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slavesClient) Restart(ctx context.Context, in *SlaveRestartRequest, opts ...grpc.CallOption) (*SlaveRestartResponse, error) {
	out := new(SlaveRestartResponse)
	err := grpc.Invoke(ctx, "/ci.Slaves/Restart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Slaves service

type SlavesServer interface {
	List(context.Context, *SlaveListRequest) (*SlaveListResponse, error)
	Describe(context.Context, *SlaveDescribeRequest) (*SlaveDescribeResponse, error)
	Create(context.Context, *SlaveCreateRequest) (*dtypes.LongRunningResponse, error)
	Delete(context.Context, *SlaveDeleteRequest) (*dtypes.LongRunningResponse, error)
	Restart(context.Context, *SlaveRestartRequest) (*SlaveRestartResponse, error)
}

func RegisterSlavesServer(s *grpc.Server, srv SlavesServer) {
	s.RegisterService(&_Slaves_serviceDesc, srv)
}

func _Slaves_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlavesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.Slaves/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlavesServer).List(ctx, req.(*SlaveListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Slaves_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlavesServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.Slaves/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlavesServer).Describe(ctx, req.(*SlaveDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Slaves_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlavesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.Slaves/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlavesServer).Create(ctx, req.(*SlaveCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Slaves_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlavesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.Slaves/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlavesServer).Delete(ctx, req.(*SlaveDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Slaves_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlavesServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.Slaves/Restart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlavesServer).Restart(ctx, req.(*SlaveRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Slaves_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ci.Slaves",
	HandlerType: (*SlavesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Slaves_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Slaves_Describe_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Slaves_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Slaves_Delete_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Slaves_Restart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

func init() { proto.RegisterFile("slave.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xfe, 0xe5, 0x9f, 0x13, 0x4f, 0xda, 0x28, 0xdd, 0xfe, 0xf9, 0xb9, 0x6e, 0x55, 0x81, 0x5b,
	0x04, 0x0a, 0x28, 0x2e, 0x41, 0xe2, 0x80, 0xc4, 0xa1, 0x6a, 0x82, 0xa8, 0x14, 0x21, 0x94, 0xf6,
	0xc2, 0xc9, 0x72, 0x9c, 0x4d, 0x30, 0xb8, 0x5e, 0xb3, 0xbb, 0x0e, 0x20, 0xc4, 0x85, 0x57, 0xe0,
	0xc0, 0xfb, 0xf0, 0x0a, 0x3c, 0x00, 0x17, 0x1e, 0x84, 0xdd, 0xf5, 0xda, 0xa4, 0x69, 0x55, 0xe5,
	0x92, 0x78, 0x67, 0x67, 0xe6, 0xfb, 0xe6, 0x9b, 0x99, 0x85, 0x26, 0x8b, 0xfc, 0x39, 0xee, 0x26,
	0x94, 0x70, 0x82, 0xca, 0x41, 0x68, 0xef, 0xcf, 0x08, 0x99, 0x45, 0xd8, 0xf5, 0x93, 0xd0, 0xf5,
	0xe3, 0x98, 0x70, 0x9f, 0x87, 0x24, 0x66, 0x99, 0x87, 0xbd, 0x23, 0xcd, 0x13, 0xfe, 0x39, 0xc1,
	0xcc, 0x55, 0xbf, 0x99, 0xdd, 0x39, 0x83, 0xf6, 0xb9, 0x4c, 0x34, 0x0c, 0x19, 0x1f, 0xe1, 0x0f,
	0x29, 0x66, 0x1c, 0xad, 0x41, 0x75, 0x4a, 0xc9, 0xa5, 0x55, 0xba, 0x53, 0x7a, 0x60, 0x22, 0x80,
	0x32, 0x27, 0x56, 0x59, 0x7d, 0xef, 0x41, 0x55, 0x06, 0x5b, 0x15, 0x71, 0x6a, 0xf5, 0xd6, 0xbb,
	0x41, 0xd8, 0x55, 0xd1, 0x17, 0xc2, 0xe8, 0xbc, 0x82, 0x8d, 0x85, 0x54, 0x2c, 0x11, 0xe0, 0x18,
	0x1d, 0x80, 0xc1, 0x04, 0x93, 0x94, 0xa9, 0x6c, 0xcd, 0x5e, 0xab, 0x9b, 0x91, 0xe8, 0x9e, 0x2b,
	0x2b, 0xda, 0x15, 0xf7, 0x32, 0x88, 0x09, 0x84, 0x8a, 0xb8, 0x37, 0x8b, 0x9c, 0xce, 0x47, 0xa8,
	0xa9, 0x0f, 0xc9, 0x27, 0xf6, 0x2f, 0xb1, 0xe6, 0xd3, 0x2a, 0x32, 0x66, 0x9c, 0x04, 0xc1, 0x90,
	0x79, 0x13, 0x1c, 0x61, 0x8e, 0x27, 0x8a, 0x59, 0x03, 0x6d, 0xc1, 0x9a, 0xb0, 0x51, 0x3c, 0xa5,
	0x98, 0xbd, 0x15, 0xd6, 0xaa, 0xb2, 0x0a, 0xcf, 0x80, 0x62, 0x5f, 0xb8, 0x79, 0x3e, 0xb7, 0x6a,
	0x79, 0x74, 0x9a, 0x4c, 0x72, 0x9b, 0x21, 0x6d, 0xce, 0xcf, 0x12, 0x20, 0x85, 0x7c, 0xaa, 0xbc,
	0x73, 0x59, 0x9a, 0x50, 0x61, 0xef, 0x53, 0xcd, 0x62, 0x03, 0x4c, 0xfc, 0x09, 0x07, 0x29, 0x27,
	0x34, 0x23, 0x52, 0x93, 0xc4, 0x22, 0x7f, 0x8c, 0x23, 0xa6, 0x48, 0x48, 0xb1, 0x36, 0x53, 0x86,
	0xa9, 0x27, 0xd8, 0x52, 0x9e, 0x26, 0x1e, 0x0b, 0x68, 0x98, 0x70, 0xc5, 0xc5, 0x44, 0x16, 0xb4,
	0x99, 0x1f, 0xf1, 0xb1, 0xcf, 0xb0, 0x37, 0xc7, 0x94, 0x89, 0x56, 0x69, 0x46, 0x36, 0xa0, 0x20,
	0xcc, 0x82, 0x44, 0x70, 0x7e, 0x67, 0xe8, 0x94, 0xb5, 0x84, 0x50, 0xce, 0xac, 0xba, 0x12, 0x6b,
	0x4d, 0x8a, 0xf5, 0x5a, 0x18, 0xce, 0xe2, 0x29, 0x91, 0x32, 0x51, 0x12, 0x61, 0xab, 0xa1, 0x8a,
	0x38, 0x86, 0x46, 0x71, 0xd3, 0x86, 0x86, 0xea, 0x76, 0x40, 0x22, 0x4d, 0x5f, 0x94, 0x2d, 0x13,
	0x79, 0xd4, 0x8f, 0x67, 0x38, 0x13, 0xd2, 0x39, 0x82, 0x2d, 0x55, 0x75, 0x1f, 0x4b, 0xa6, 0x63,
	0xbc, 0x30, 0x0e, 0xff, 0xe4, 0x77, 0x7e, 0x97, 0x60, 0x7b, 0xc9, 0x6d, 0xc5, 0x56, 0xe7, 0x79,
	0xca, 0xd7, 0x05, 0x94, 0x82, 0x55, 0xd0, 0x26, 0x34, 0x63, 0x32, 0xc1, 0x9e, 0xce, 0x92, 0x09,
	0xb5, 0x03, 0x2d, 0x32, 0x9d, 0x46, 0x61, 0x8c, 0x45, 0x3f, 0x7d, 0x56, 0xc8, 0xb4, 0x0e, 0x35,
	0xa5, 0xb6, 0x56, 0x26, 0x2b, 0x71, 0x1e, 0x4e, 0x30, 0x15, 0xe2, 0x48, 0x8b, 0x6e, 0x57, 0x23,
	0xcf, 0xb2, 0xd4, 0x06, 0x33, 0xd7, 0x61, 0x61, 0x24, 0x40, 0x55, 0xe8, 0xe8, 0xee, 0xf7, 0xd5,
	0x48, 0xdd, 0xac, 0xc2, 0x21, 0x6c, 0x2a, 0x1f, 0x51, 0xbc, 0x4c, 0x7b, 0xb3, 0xd3, 0x53, 0x2d,
	0x68, 0xe1, 0xb4, 0x9a, 0x50, 0x9d, 0xe7, 0x60, 0x16, 0x5b, 0x85, 0xea, 0x50, 0x39, 0x19, 0x0e,
	0xdb, 0xff, 0x89, 0x7a, 0xea, 0xa7, 0xa3, 0xc1, 0xc5, 0xc9, 0xa0, 0xdf, 0x2e, 0xc9, 0x43, 0x7f,
	0x30, 0x1c, 0x5c, 0x88, 0x43, 0x59, 0x48, 0x61, 0x8e, 0x06, 0x2f, 0x46, 0x83, 0xf3, 0x97, 0xe2,
	0x58, 0xe9, 0xfd, 0xa8, 0x82, 0xa1, 0xe2, 0x19, 0x7a, 0x03, 0x55, 0xb9, 0x8d, 0x68, 0xab, 0xd8,
	0xaa, 0x85, 0x3d, 0xb7, 0xb7, 0x97, 0xac, 0x19, 0x3d, 0xe7, 0xe8, 0xdb, 0xaf, 0x3f, 0xdf, 0xcb,
	0x07, 0x68, 0x5f, 0x3c, 0x25, 0x09, 0x0b, 0x44, 0x47, 0xd4, 0x9b, 0x12, 0x84, 0xee, 0xfc, 0xb8,
	0xfb, 0xd8, 0xcd, 0xd6, 0x15, 0x45, 0xd0, 0xc8, 0x27, 0x00, 0x59, 0x45, 0xa2, 0xa5, 0xd9, 0xb1,
	0x77, 0x6f, 0xb8, 0xd1, 0x30, 0x0f, 0x15, 0xcc, 0x3d, 0x74, 0x78, 0x1b, 0x8c, 0xfb, 0x45, 0xea,
	0xf9, 0x15, 0x4d, 0xc1, 0xc8, 0x96, 0x11, 0xed, 0x14, 0x19, 0xaf, 0x6c, 0xa7, 0xbd, 0x97, 0x8b,
	0x38, 0x24, 0xf1, 0x6c, 0x94, 0xc6, 0x71, 0x28, 0xfe, 0x72, 0xac, 0xfb, 0x0a, 0xeb, 0xae, 0x7d,
	0x6b, 0x49, 0xcf, 0x4a, 0x1d, 0xf4, 0x0e, 0x8c, 0xac, 0xed, 0x0b, 0x38, 0x57, 0xe6, 0xe0, 0x76,
	0x1c, 0x5d, 0x53, 0x67, 0xa5, 0x9a, 0x12, 0xa8, 0xeb, 0xc9, 0x40, 0xff, 0x17, 0x60, 0x57, 0x07,
	0xca, 0xb6, 0xae, 0x5f, 0x68, 0xa8, 0x9e, 0x82, 0x7a, 0x84, 0x3a, 0x2b, 0x40, 0xb9, 0x14, 0x8f,
	0x09, 0xe1, 0x63, 0x43, 0xbd, 0x02, 0x4f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x19, 0x97, 0xeb,
	0x0a, 0x3c, 0x06, 0x00, 0x00,
}
