// Code generated by protoc-gen-go.
// source: artifactory.proto
// DO NOT EDIT!

/*
Package artifactory is a generated protocol buffer package.

It is generated from these files:
	artifactory.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
	ListRequest
	ListResponse
	DescribeRequest
	DescribeResponse
	Artifact
	JavaSpec
	DockerSpec
	PhpSpec
	NpmSpec
*/
package artifactory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SearchRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SearchResponse struct {
	Status    *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Artifacts []*Artifact    `protobuf:"bytes,2,rep,name=artifacts" json:"artifacts,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchResponse) GetArtifacts() []*Artifact {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

type ListRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListResponse struct {
	Status    *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Artifacts []*Artifact    `protobuf:"bytes,2,rep,name=artifacts" json:"artifacts,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListResponse) GetArtifacts() []*Artifact {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

type DescribeRequest struct {
	Id   string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DescribeResponse struct {
	Status   *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Artifact *Artifact      `protobuf:"bytes,2,opt,name=artifact" json:"artifact,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeResponse) GetArtifact() *Artifact {
	if m != nil {
		return m.Artifact
	}
	return nil
}

type Artifact struct {
	Id               string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Version          string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	LastModifiedTime string `protobuf:"bytes,4,opt,name=last_modified_time" json:"last_modified_time,omitempty"`
	Type             string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	// Types that are valid to be assigned to Specs:
	//	*Artifact_Java
	//	*Artifact_Docker
	//	*Artifact_Php
	//	*Artifact_Npm
	Specs isArtifact_Specs `protobuf_oneof:"specs"`
}

func (m *Artifact) Reset()                    { *m = Artifact{} }
func (m *Artifact) String() string            { return proto.CompactTextString(m) }
func (*Artifact) ProtoMessage()               {}
func (*Artifact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isArtifact_Specs interface {
	isArtifact_Specs()
}

type Artifact_Java struct {
	Java *JavaSpec `protobuf:"bytes,6,opt,name=java,oneof"`
}
type Artifact_Docker struct {
	Docker *DockerSpec `protobuf:"bytes,7,opt,name=docker,oneof"`
}
type Artifact_Php struct {
	Php *PhpSpec `protobuf:"bytes,8,opt,name=php,oneof"`
}
type Artifact_Npm struct {
	Npm *NpmSpec `protobuf:"bytes,9,opt,name=npm,oneof"`
}

func (*Artifact_Java) isArtifact_Specs()   {}
func (*Artifact_Docker) isArtifact_Specs() {}
func (*Artifact_Php) isArtifact_Specs()    {}
func (*Artifact_Npm) isArtifact_Specs()    {}

func (m *Artifact) GetSpecs() isArtifact_Specs {
	if m != nil {
		return m.Specs
	}
	return nil
}

func (m *Artifact) GetJava() *JavaSpec {
	if x, ok := m.GetSpecs().(*Artifact_Java); ok {
		return x.Java
	}
	return nil
}

func (m *Artifact) GetDocker() *DockerSpec {
	if x, ok := m.GetSpecs().(*Artifact_Docker); ok {
		return x.Docker
	}
	return nil
}

func (m *Artifact) GetPhp() *PhpSpec {
	if x, ok := m.GetSpecs().(*Artifact_Php); ok {
		return x.Php
	}
	return nil
}

func (m *Artifact) GetNpm() *NpmSpec {
	if x, ok := m.GetSpecs().(*Artifact_Npm); ok {
		return x.Npm
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Artifact) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Artifact_OneofMarshaler, _Artifact_OneofUnmarshaler, _Artifact_OneofSizer, []interface{}{
		(*Artifact_Java)(nil),
		(*Artifact_Docker)(nil),
		(*Artifact_Php)(nil),
		(*Artifact_Npm)(nil),
	}
}

func _Artifact_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Artifact)
	// specs
	switch x := m.Specs.(type) {
	case *Artifact_Java:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Java); err != nil {
			return err
		}
	case *Artifact_Docker:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Docker); err != nil {
			return err
		}
	case *Artifact_Php:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Php); err != nil {
			return err
		}
	case *Artifact_Npm:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Npm); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Artifact.Specs has unexpected type %T", x)
	}
	return nil
}

func _Artifact_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Artifact)
	switch tag {
	case 6: // specs.java
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JavaSpec)
		err := b.DecodeMessage(msg)
		m.Specs = &Artifact_Java{msg}
		return true, err
	case 7: // specs.docker
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DockerSpec)
		err := b.DecodeMessage(msg)
		m.Specs = &Artifact_Docker{msg}
		return true, err
	case 8: // specs.php
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PhpSpec)
		err := b.DecodeMessage(msg)
		m.Specs = &Artifact_Php{msg}
		return true, err
	case 9: // specs.npm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NpmSpec)
		err := b.DecodeMessage(msg)
		m.Specs = &Artifact_Npm{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Artifact_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Artifact)
	// specs
	switch x := m.Specs.(type) {
	case *Artifact_Java:
		s := proto.Size(x.Java)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Artifact_Docker:
		s := proto.Size(x.Docker)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Artifact_Php:
		s := proto.Size(x.Php)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Artifact_Npm:
		s := proto.Size(x.Npm)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type JavaSpec struct {
	GroupId     string `protobuf:"bytes,1,opt,name=group_id" json:"group_id,omitempty"`
	ArtifactId  string `protobuf:"bytes,2,opt,name=artifact_id" json:"artifact_id,omitempty"`
	ArtifactUrl string `protobuf:"bytes,3,opt,name=artifact_url" json:"artifact_url,omitempty"`
}

func (m *JavaSpec) Reset()                    { *m = JavaSpec{} }
func (m *JavaSpec) String() string            { return proto.CompactTextString(m) }
func (*JavaSpec) ProtoMessage()               {}
func (*JavaSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DockerSpec struct {
	TarSums     []string `protobuf:"bytes,1,rep,name=tar_sums" json:"tar_sums,omitempty"`
	ManifestUrl string   `protobuf:"bytes,2,opt,name=manifest_url" json:"manifest_url,omitempty"`
}

func (m *DockerSpec) Reset()                    { *m = DockerSpec{} }
func (m *DockerSpec) String() string            { return proto.CompactTextString(m) }
func (*DockerSpec) ProtoMessage()               {}
func (*DockerSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type PhpSpec struct {
	DownloadUrl string `protobuf:"bytes,1,opt,name=download_url" json:"download_url,omitempty"`
	Shasum      string `protobuf:"bytes,2,opt,name=shasum" json:"shasum,omitempty"`
}

func (m *PhpSpec) Reset()                    { *m = PhpSpec{} }
func (m *PhpSpec) String() string            { return proto.CompactTextString(m) }
func (*PhpSpec) ProtoMessage()               {}
func (*PhpSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type NpmSpec struct {
	Description string   `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	ArtifactId  string   `protobuf:"bytes,2,opt,name=artifact_id" json:"artifact_id,omitempty"`
	Shasum      string   `protobuf:"bytes,3,opt,name=shasum" json:"shasum,omitempty"`
	Keywords    []string `protobuf:"bytes,4,rep,name=keywords" json:"keywords,omitempty"`
	ArtifactUrl string   `protobuf:"bytes,5,opt,name=artifact_url" json:"artifact_url,omitempty"`
}

func (m *NpmSpec) Reset()                    { *m = NpmSpec{} }
func (m *NpmSpec) String() string            { return proto.CompactTextString(m) }
func (*NpmSpec) ProtoMessage()               {}
func (*NpmSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*SearchRequest)(nil), "artifactory.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "artifactory.SearchResponse")
	proto.RegisterType((*ListRequest)(nil), "artifactory.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "artifactory.ListResponse")
	proto.RegisterType((*DescribeRequest)(nil), "artifactory.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "artifactory.DescribeResponse")
	proto.RegisterType((*Artifact)(nil), "artifactory.Artifact")
	proto.RegisterType((*JavaSpec)(nil), "artifactory.JavaSpec")
	proto.RegisterType((*DockerSpec)(nil), "artifactory.DockerSpec")
	proto.RegisterType((*PhpSpec)(nil), "artifactory.PhpSpec")
	proto.RegisterType((*NpmSpec)(nil), "artifactory.NpmSpec")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Artifactory service

type ArtifactoryClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
}

type artifactoryClient struct {
	cc *grpc.ClientConn
}

func NewArtifactoryClient(cc *grpc.ClientConn) ArtifactoryClient {
	return &artifactoryClient{cc}
}

func (c *artifactoryClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/artifactory.Artifactory/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactoryClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/artifactory.Artifactory/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactoryClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/artifactory.Artifactory/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Artifactory service

type ArtifactoryServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
}

func RegisterArtifactoryServer(s *grpc.Server, srv ArtifactoryServer) {
	s.RegisterService(&_Artifactory_serviceDesc, srv)
}

func _Artifactory_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactoryServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifactory.Artifactory/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactoryServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artifactory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifactory.Artifactory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactoryServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artifactory_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactoryServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifactory.Artifactory/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactoryServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Artifactory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "artifactory.Artifactory",
	HandlerType: (*ArtifactoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Artifactory_Search_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Artifactory_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Artifactory_Describe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xfe, 0xad, 0x7f, 0xd3, 0xd3, 0xae, 0xdb, 0xcf, 0x0c, 0x08, 0xd9, 0x40, 0x28, 0x68, 0xda,
	0x80, 0x92, 0x40, 0xd9, 0x0b, 0x0c, 0x4d, 0x02, 0x21, 0x84, 0x10, 0xbd, 0x41, 0x70, 0x51, 0x79,
	0x89, 0xdb, 0x66, 0x6d, 0x62, 0x63, 0xa7, 0xad, 0xaa, 0x6a, 0x37, 0x88, 0x37, 0xe0, 0xd1, 0x78,
	0x05, 0xee, 0x79, 0x05, 0x1c, 0x3b, 0x69, 0x1a, 0xd4, 0xc1, 0x2e, 0xb8, 0x89, 0xe2, 0x73, 0x3e,
	0x9f, 0xef, 0xb3, 0xbf, 0x73, 0x0c, 0xff, 0x63, 0x1e, 0x07, 0x03, 0xec, 0xc5, 0x94, 0x2f, 0x1c,
	0xc6, 0x69, 0x4c, 0x51, 0x73, 0x2d, 0x64, 0x1d, 0x0c, 0x29, 0x1d, 0x4e, 0x88, 0x8b, 0x59, 0xe0,
	0xe2, 0x28, 0xa2, 0x31, 0x8e, 0x03, 0x1a, 0x09, 0x0d, 0xb5, 0x6e, 0x25, 0x61, 0x3f, 0x5e, 0x30,
	0x22, 0x5c, 0xf5, 0xd5, 0x71, 0xbb, 0x03, 0xdb, 0x3d, 0x82, 0xb9, 0x37, 0x7a, 0x4f, 0x3e, 0x4f,
	0x89, 0x88, 0xd1, 0x36, 0x54, 0xe5, 0x0f, 0x5f, 0x98, 0x5b, 0xf7, 0xb7, 0x8e, 0x1b, 0xa8, 0x05,
	0x95, 0x04, 0x6e, 0x96, 0x92, 0x95, 0xfd, 0x11, 0xda, 0x19, 0x5a, 0x30, 0x59, 0x9c, 0xa0, 0x7b,
	0x50, 0x13, 0x92, 0x69, 0x2a, 0x14, 0xbe, 0xd9, 0x6d, 0x3b, 0x9a, 0xc4, 0xe9, 0xa9, 0x28, 0x3a,
	0x86, 0x46, 0x26, 0x52, 0xc8, 0x22, 0x65, 0x09, 0xb9, 0xe9, 0xac, 0x9f, 0xe4, 0x34, 0xfd, 0xb7,
	0xf7, 0xa1, 0xf9, 0x26, 0x10, 0x71, 0xa6, 0x23, 0x23, 0x56, 0x32, 0xec, 0x0f, 0xd0, 0xd2, 0xc9,
	0x7f, 0x4e, 0xfb, 0x18, 0x76, 0xce, 0x88, 0xf0, 0x78, 0x70, 0x4e, 0x32, 0x6a, 0x80, 0x52, 0xe0,
	0xeb, 0x13, 0xff, 0x26, 0xe3, 0x13, 0xec, 0xe6, 0xe0, 0x6b, 0x4a, 0x39, 0x02, 0x23, 0x23, 0x56,
	0x35, 0xaf, 0x54, 0xf2, 0xb5, 0x04, 0x46, 0xb6, 0x48, 0x35, 0xac, 0x3c, 0x88, 0x70, 0x98, 0x7a,
	0x80, 0x76, 0xa0, 0x3e, 0x23, 0x5c, 0x48, 0x6f, 0xcd, 0xb2, 0x0a, 0x58, 0x80, 0x26, 0x58, 0xc4,
	0xfd, 0x90, 0xfa, 0xc1, 0x20, 0x20, 0x7e, 0x3f, 0x0e, 0x24, 0xb8, 0x52, 0x90, 0x5f, 0x55, 0xab,
	0x43, 0xa8, 0x5c, 0xe0, 0x19, 0x36, 0x6b, 0x1b, 0x64, 0xbc, 0x96, 0x89, 0x1e, 0x23, 0xde, 0xab,
	0xff, 0xd0, 0x43, 0xa8, 0xf9, 0xd4, 0x1b, 0x13, 0x6e, 0xd6, 0x15, 0xf0, 0x76, 0x01, 0x78, 0xa6,
	0x52, 0x29, 0xf4, 0x01, 0x94, 0xd9, 0x88, 0x99, 0x86, 0xc2, 0xed, 0x15, 0x70, 0xef, 0x46, 0x2c,
	0x07, 0x45, 0x2c, 0x34, 0x1b, 0x1b, 0x40, 0x6f, 0x59, 0xa8, 0x41, 0x2f, 0xea, 0x50, 0x15, 0xf2,
	0x4f, 0xd8, 0x2f, 0xc1, 0xc8, 0xb4, 0xa0, 0x5d, 0x30, 0x86, 0x9c, 0x4e, 0x59, 0x7f, 0x75, 0x17,
	0x37, 0x60, 0xd5, 0xf4, 0xfd, 0x95, 0x49, 0x7b, 0xd0, 0x5a, 0x05, 0xa7, 0x7c, 0xa2, 0xef, 0xc5,
	0x3e, 0x01, 0xc8, 0xb5, 0x26, 0xa5, 0x62, 0xcc, 0xfb, 0x62, 0x1a, 0x26, 0x46, 0x95, 0xf5, 0xae,
	0x10, 0x47, 0xc1, 0x40, 0x5a, 0xae, 0x76, 0xe9, 0x16, 0x77, 0xa1, 0x9e, 0x2a, 0x4f, 0x00, 0x3e,
	0x9d, 0x47, 0x13, 0x8a, 0x7d, 0x05, 0xd0, 0x0a, 0xda, 0xd2, 0xef, 0x11, 0x96, 0x75, 0xd2, 0x0d,
	0x63, 0xa8, 0xa7, 0xa7, 0x48, 0xc4, 0xf9, 0xaa, 0x3d, 0x58, 0x32, 0x7a, 0x7f, 0x52, 0x9c, 0x17,
	0xd1, 0x1e, 0x4a, 0x75, 0x63, 0xb2, 0x98, 0x53, 0xee, 0x0b, 0xe9, 0x5c, 0x79, 0xc3, 0x99, 0x94,
	0x83, 0xdd, 0x9f, 0x25, 0x68, 0x9e, 0xe6, 0xf7, 0x87, 0xe6, 0x50, 0xd3, 0x03, 0x89, 0xac, 0xc2,
	0xbd, 0x16, 0x66, 0xda, 0xda, 0xdf, 0x98, 0xd3, 0xfd, 0x6b, 0x9f, 0x7c, 0xf9, 0xfe, 0xe3, 0x5b,
	0xc9, 0x41, 0x1d, 0xf9, 0x72, 0x30, 0xe1, 0x51, 0x3f, 0x7d, 0x42, 0xf2, 0x1d, 0xee, 0xec, 0xa9,
	0xf3, 0xcc, 0x15, 0x6a, 0x9b, 0xbb, 0x4c, 0xfa, 0xe9, 0x12, 0x5d, 0x40, 0x25, 0x19, 0x48, 0x64,
	0x16, 0x4a, 0xaf, 0x0d, 0xb0, 0x75, 0x67, 0x43, 0x26, 0xa5, 0x7c, 0xa2, 0x28, 0x8f, 0xd0, 0xe1,
	0x5f, 0x28, 0x53, 0xae, 0x25, 0x18, 0xd9, 0xd4, 0xa1, 0x83, 0x62, 0x2f, 0x16, 0x27, 0xd7, 0xba,
	0x7b, 0x45, 0x36, 0xe5, 0xed, 0x2a, 0xde, 0x0e, 0x7a, 0x74, 0x2d, 0x5e, 0x77, 0x19, 0xf8, 0x97,
	0xe7, 0x35, 0xf5, 0x4e, 0x3e, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xe1, 0x6b, 0x73, 0x7f,
	0x05, 0x00, 0x00,
}
