// Code generated by protoc-gen-go.
// source: volume.proto
// DO NOT EDIT!

package glusterfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VolumeCreateRequest struct {
	KubeCluster      string `protobuf:"bytes,1,opt,name=kube_cluster,json=kubeCluster" json:"kube_cluster,omitempty"`
	GlusterfsCluster string `protobuf:"bytes,2,opt,name=glusterfs_cluster,json=glusterfsCluster" json:"glusterfs_cluster,omitempty"`
	Volume           string `protobuf:"bytes,3,opt,name=volume" json:"volume,omitempty"`
}

func (m *VolumeCreateRequest) Reset()                    { *m = VolumeCreateRequest{} }
func (m *VolumeCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*VolumeCreateRequest) ProtoMessage()               {}
func (*VolumeCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type VolumeDeleteRequest struct {
	KubeCluster      string `protobuf:"bytes,1,opt,name=kube_cluster,json=kubeCluster" json:"kube_cluster,omitempty"`
	GlusterfsCluster string `protobuf:"bytes,2,opt,name=glusterfs_cluster,json=glusterfsCluster" json:"glusterfs_cluster,omitempty"`
	Volume           string `protobuf:"bytes,3,opt,name=volume" json:"volume,omitempty"`
}

func (m *VolumeDeleteRequest) Reset()                    { *m = VolumeDeleteRequest{} }
func (m *VolumeDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*VolumeDeleteRequest) ProtoMessage()               {}
func (*VolumeDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type VolumeListRequest struct {
	KubeCluster      string `protobuf:"bytes,1,opt,name=kube_cluster,json=kubeCluster" json:"kube_cluster,omitempty"`
	GlusterfsCluster string `protobuf:"bytes,2,opt,name=glusterfs_cluster,json=glusterfsCluster" json:"glusterfs_cluster,omitempty"`
}

func (m *VolumeListRequest) Reset()                    { *m = VolumeListRequest{} }
func (m *VolumeListRequest) String() string            { return proto.CompactTextString(m) }
func (*VolumeListRequest) ProtoMessage()               {}
func (*VolumeListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type VolumeListResponse struct {
	Status  *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Volumes []*Volume      `protobuf:"bytes,2,rep,name=volumes" json:"volumes,omitempty"`
}

func (m *VolumeListResponse) Reset()                    { *m = VolumeListResponse{} }
func (m *VolumeListResponse) String() string            { return proto.CompactTextString(m) }
func (*VolumeListResponse) ProtoMessage()               {}
func (*VolumeListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *VolumeListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VolumeListResponse) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type Volume struct {
	Path     string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Bricks   string `protobuf:"bytes,2,opt,name=bricks" json:"bricks,omitempty"`
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
	Replica  int64  `protobuf:"varint,4,opt,name=replica" json:"replica,omitempty"`
}

func (m *Volume) Reset()                    { *m = Volume{} }
func (m *Volume) String() string            { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()               {}
func (*Volume) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func init() {
	proto.RegisterType((*VolumeCreateRequest)(nil), "glusterfs.VolumeCreateRequest")
	proto.RegisterType((*VolumeDeleteRequest)(nil), "glusterfs.VolumeDeleteRequest")
	proto.RegisterType((*VolumeListRequest)(nil), "glusterfs.VolumeListRequest")
	proto.RegisterType((*VolumeListResponse)(nil), "glusterfs.VolumeListResponse")
	proto.RegisterType((*Volume)(nil), "glusterfs.Volume")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Volumes service

type VolumesClient interface {
	List(ctx context.Context, in *VolumeListRequest, opts ...grpc.CallOption) (*VolumeListResponse, error)
	Create(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Delete(ctx context.Context, in *VolumeDeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
}

type volumesClient struct {
	cc *grpc.ClientConn
}

func NewVolumesClient(cc *grpc.ClientConn) VolumesClient {
	return &volumesClient{cc}
}

func (c *volumesClient) List(ctx context.Context, in *VolumeListRequest, opts ...grpc.CallOption) (*VolumeListResponse, error) {
	out := new(VolumeListResponse)
	err := grpc.Invoke(ctx, "/glusterfs.Volumes/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumesClient) Create(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/glusterfs.Volumes/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumesClient) Delete(ctx context.Context, in *VolumeDeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/glusterfs.Volumes/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Volumes service

type VolumesServer interface {
	List(context.Context, *VolumeListRequest) (*VolumeListResponse, error)
	Create(context.Context, *VolumeCreateRequest) (*dtypes.VoidResponse, error)
	Delete(context.Context, *VolumeDeleteRequest) (*dtypes.VoidResponse, error)
}

func RegisterVolumesServer(s *grpc.Server, srv VolumesServer) {
	s.RegisterService(&_Volumes_serviceDesc, srv)
}

func _Volumes_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(VolumeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(VolumesServer).List(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Volumes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(VolumeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(VolumesServer).Create(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Volumes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(VolumeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(VolumesServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Volumes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "glusterfs.Volumes",
	HandlerType: (*VolumesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Volumes_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Volumes_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Volumes_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor1 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x93, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x91, 0x65, 0xe4, 0x7a, 0x6c, 0x4a, 0xbd, 0x2d, 0x46, 0x08, 0xb7, 0xb4, 0x3a, 0x94,
	0xe2, 0x82, 0xb6, 0x75, 0xe9, 0xa5, 0x87, 0x12, 0x70, 0x48, 0x08, 0x04, 0x02, 0x0a, 0xf8, 0x1a,
	0x64, 0x79, 0xe3, 0x6c, 0xac, 0x68, 0x15, 0xed, 0xca, 0x10, 0x8c, 0x2e, 0xb9, 0xe6, 0x90, 0x43,
	0x5e, 0x20, 0xef, 0x94, 0x57, 0xc8, 0x83, 0x44, 0xda, 0x95, 0x14, 0x1b, 0xc7, 0x10, 0x08, 0xc9,
	0xc5, 0x78, 0x66, 0x7e, 0xe6, 0xfb, 0x77, 0x66, 0x04, 0xed, 0x39, 0x0b, 0x92, 0x33, 0xe2, 0x44,
	0x31, 0x13, 0x0c, 0x35, 0xa7, 0x41, 0xc2, 0x05, 0x89, 0x8f, 0xb9, 0xd5, 0x9b, 0x32, 0x36, 0x0d,
	0x08, 0xf6, 0x22, 0x8a, 0xbd, 0x30, 0x64, 0xc2, 0x13, 0x94, 0x85, 0x5c, 0x09, 0xad, 0x6e, 0x9e,
	0x9e, 0x88, 0x8b, 0x88, 0x70, 0x2c, 0x7f, 0x55, 0xde, 0x4e, 0xe1, 0xe3, 0x48, 0x36, 0x1c, 0xc6,
	0xc4, 0x13, 0xc4, 0x25, 0xe7, 0x09, 0xe1, 0x02, 0x7d, 0x83, 0xf6, 0x2c, 0x19, 0x93, 0x23, 0x5f,
	0xb5, 0x37, 0xb5, 0xaf, 0xda, 0x8f, 0xa6, 0xdb, 0xca, 0x73, 0x43, 0x95, 0x42, 0x3f, 0xa1, 0x53,
	0xc1, 0x2b, 0x5d, 0x4d, 0xea, 0x3e, 0x54, 0x85, 0x52, 0xdc, 0x05, 0x43, 0xf9, 0x36, 0x75, 0xa9,
	0x28, 0xa2, 0x47, 0xfc, 0x36, 0x09, 0xc8, 0xdb, 0xe3, 0x7d, 0xe8, 0x28, 0xfc, 0x3e, 0xe5, 0xe2,
	0x95, 0xe0, 0x36, 0x05, 0xb4, 0x0c, 0xe1, 0x51, 0xb6, 0x15, 0x82, 0xbe, 0x83, 0xc1, 0xb3, 0x15,
	0x25, 0x5c, 0xf6, 0x6f, 0x0d, 0xde, 0x3b, 0x6a, 0x3b, 0xce, 0xa1, 0xcc, 0xba, 0x45, 0x35, 0x43,
	0x35, 0x94, 0x59, 0x9e, 0x01, 0xf4, 0x4c, 0xd8, 0x71, 0x2a, 0x82, 0xa3, 0xfa, 0xba, 0xa5, 0xc2,
	0x3e, 0x05, 0x43, 0xa5, 0x10, 0x82, 0x7a, 0xe4, 0x89, 0x93, 0xc2, 0xbc, 0xfc, 0x9f, 0x4f, 0x61,
	0x1c, 0x53, 0x7f, 0xc6, 0x0b, 0xab, 0x45, 0x84, 0x2c, 0x78, 0x47, 0xc2, 0x49, 0xc4, 0x68, 0x28,
	0x8a, 0xf9, 0x54, 0x31, 0x32, 0xa1, 0x11, 0x93, 0x28, 0xa0, 0xbe, 0x67, 0xd6, 0xb3, 0x92, 0xee,
	0x96, 0xe1, 0xe0, 0x56, 0x87, 0x86, 0x82, 0x71, 0x74, 0xa5, 0x41, 0x3d, 0x7f, 0x1d, 0xea, 0xad,
	0x99, 0x5b, 0x9a, 0xac, 0xf5, 0x79, 0x43, 0x55, 0x8d, 0xc4, 0xde, 0xb9, 0xbc, 0xbb, 0xbf, 0xa9,
	0x6d, 0xa1, 0xff, 0xf2, 0x86, 0x2b, 0x29, 0x9e, 0xff, 0x72, 0x7e, 0xe3, 0xe2, 0x89, 0x78, 0xb1,
	0xbc, 0x9b, 0x14, 0x2f, 0xd6, 0xf6, 0x90, 0xa2, 0x04, 0x0c, 0x75, 0xcd, 0xe8, 0xcb, 0x1a, 0x70,
	0xe5, 0xcc, 0xad, 0x4f, 0xe5, 0xd0, 0x47, 0x8c, 0x4e, 0x2a, 0x1f, 0x7f, 0xa5, 0x0f, 0x6c, 0xf5,
	0x9f, 0xef, 0xe3, 0x9f, 0xd6, 0x47, 0xd7, 0x1a, 0x18, 0xea, 0x8c, 0x9f, 0xe0, 0xae, 0xdc, 0xf7,
	0x06, 0xee, 0x81, 0xe4, 0xee, 0xf5, 0x77, 0x5f, 0xf6, 0x7e, 0xbc, 0x50, 0xda, 0x74, 0x6c, 0xc8,
	0x6f, 0xfc, 0xcf, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0x52, 0xc3, 0x17, 0x34, 0x04, 0x00,
	0x00,
}
