// Code generated by protoc-gen-go.
// source: db.proto
// DO NOT EDIT!

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db.proto
	slaves.proto

It has these top-level messages:
	CreateRequest
	DeleteRequest
	BackupRequest
	RestoreRequest
	DescribeRequest
	DescribeResponse
	DbPodSpecs
	ListRequest
	ListResponse
	Database
	SnapshotListRequest
	SnapshotListResponse
	Snapshot
	SlaveAddRequest
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CreateRequest struct {
	Type       string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Sku        string `protobuf:"bytes,2,opt,name=sku" json:"sku,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Cluster    string `protobuf:"bytes,4,opt,name=cluster" json:"cluster,omitempty"`
	Pv         string `protobuf:"bytes,5,opt,name=pv" json:"pv,omitempty"`
	PvSize     int64  `protobuf:"varint,6,opt,name=pv_size" json:"pv_size,omitempty"`
	Node       int32  `protobuf:"varint,7,opt,name=node" json:"node,omitempty"`
	Region     string `protobuf:"bytes,8,opt,name=region" json:"region,omitempty"`
	BucketName string `protobuf:"bytes,9,opt,name=bucket_name" json:"bucket_name,omitempty"`
	Credential string `protobuf:"bytes,10,opt,name=credential" json:"credential,omitempty"`
	Version    string `protobuf:"bytes,11,opt,name=version" json:"version,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DeleteRequest struct {
	Type    string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cluster string `protobuf:"bytes,3,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BackupRequest struct {
	Cluster        string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type           string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	BucketName     string `protobuf:"bytes,4,opt,name=bucket_name" json:"bucket_name,omitempty"`
	SecretName     string `protobuf:"bytes,5,opt,name=secret_name" json:"secret_name,omitempty"`
	SnapshotName   string `protobuf:"bytes,6,opt,name=snapshot_name" json:"snapshot_name,omitempty"`
	Credential     string `protobuf:"bytes,7,opt,name=credential" json:"credential,omitempty"`
	Region         string `protobuf:"bytes,8,opt,name=region" json:"region,omitempty"`
	AuthSecretName string `protobuf:"bytes,9,opt,name=auth_secret_name" json:"auth_secret_name,omitempty"`
	Force          bool   `protobuf:"varint,10,opt,name=force" json:"force,omitempty"`
}

func (m *BackupRequest) Reset()                    { *m = BackupRequest{} }
func (m *BackupRequest) String() string            { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()               {}
func (*BackupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RestoreRequest struct {
	Cluster      string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type         string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Pv           string `protobuf:"bytes,4,opt,name=pv" json:"pv,omitempty"`
	PvSize       int64  `protobuf:"varint,5,opt,name=pv_size" json:"pv_size,omitempty"`
	Sku          string `protobuf:"bytes,6,opt,name=sku" json:"sku,omitempty"`
	Node         int32  `protobuf:"varint,7,opt,name=node" json:"node,omitempty"`
	SnapshotPhid string `protobuf:"bytes,8,opt,name=snapshot_phid" json:"snapshot_phid,omitempty"`
	BucketName   string `protobuf:"bytes,9,opt,name=bucket_name" json:"bucket_name,omitempty"`
	Credential   string `protobuf:"bytes,10,opt,name=credential" json:"credential,omitempty"`
	Region       string `protobuf:"bytes,11,opt,name=region" json:"region,omitempty"`
	SecretName   string `protobuf:"bytes,12,opt,name=secret_name" json:"secret_name,omitempty"`
	Version      string `protobuf:"bytes,13,opt,name=version" json:"version,omitempty"`
	Force        bool   `protobuf:"varint,14,opt,name=force" json:"force,omitempty"`
}

func (m *RestoreRequest) Reset()                    { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()               {}
func (*RestoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DescribeRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DescribeResponse struct {
	Status      *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Pods        []*DbPodSpecs  `protobuf:"bytes,2,rep,name=pods" json:"pods,omitempty"`
	ServiceName string         `protobuf:"bytes,3,opt,name=service_name" json:"service_name,omitempty"`
	ServiceIp   string         `protobuf:"bytes,4,opt,name=service_ip" json:"service_ip,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeResponse) GetPods() []*DbPodSpecs {
	if m != nil {
		return m.Pods
	}
	return nil
}

type DbPodSpecs struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Phase     string `protobuf:"bytes,2,opt,name=phase" json:"phase,omitempty"`
	Condition string `protobuf:"bytes,3,opt,name=condition" json:"condition,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Type      string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
}

func (m *DbPodSpecs) Reset()                    { *m = DbPodSpecs{} }
func (m *DbPodSpecs) String() string            { return proto.CompactTextString(m) }
func (*DbPodSpecs) ProtoMessage()               {}
func (*DbPodSpecs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ListRequest struct {
	Phid string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ListResponse struct {
	Status    *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Databases []*Database    `protobuf:"bytes,2,rep,name=databases" json:"databases,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListResponse) GetDatabases() []*Database {
	if m != nil {
		return m.Databases
	}
	return nil
}

type Database struct {
	Phid                string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	ClusterName         string `protobuf:"bytes,2,opt,name=cluster_name" json:"cluster_name,omitempty"`
	KubernetesService   string `protobuf:"bytes,3,opt,name=kubernetes_service" json:"kubernetes_service,omitempty"`
	Namespace           string `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
	Type                string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	Sku                 string `protobuf:"bytes,6,opt,name=sku" json:"sku,omitempty"`
	Version             string `protobuf:"bytes,7,opt,name=version" json:"version,omitempty"`
	ArchiveBucket       string `protobuf:"bytes,8,opt,name=archive_bucket" json:"archive_bucket,omitempty"`
	ArchiveBucketRegion string `protobuf:"bytes,9,opt,name=archive_bucket_region" json:"archive_bucket_region,omitempty"`
	AutoSnapshot        int32  `protobuf:"varint,10,opt,name=auto_snapshot" json:"auto_snapshot,omitempty"`
	PvSize              int64  `protobuf:"varint,11,opt,name=pv_size" json:"pv_size,omitempty"`
	Created             string `protobuf:"bytes,12,opt,name=created" json:"created,omitempty"`
	LastBackup          string `protobuf:"bytes,13,opt,name=last_backup" json:"last_backup,omitempty"`
}

func (m *Database) Reset()                    { *m = Database{} }
func (m *Database) String() string            { return proto.CompactTextString(m) }
func (*Database) ProtoMessage()               {}
func (*Database) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SnapshotListRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Phid string `protobuf:"bytes,2,opt,name=phid" json:"phid,omitempty"`
}

func (m *SnapshotListRequest) Reset()                    { *m = SnapshotListRequest{} }
func (m *SnapshotListRequest) String() string            { return proto.CompactTextString(m) }
func (*SnapshotListRequest) ProtoMessage()               {}
func (*SnapshotListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SnapshotListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	List   []*Snapshot    `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (m *SnapshotListResponse) Reset()                    { *m = SnapshotListResponse{} }
func (m *SnapshotListResponse) String() string            { return proto.CompactTextString(m) }
func (*SnapshotListResponse) ProtoMessage()               {}
func (*SnapshotListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SnapshotListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SnapshotListResponse) GetList() []*Snapshot {
	if m != nil {
		return m.List
	}
	return nil
}

type Snapshot struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Provider    string `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	Bucket      string `protobuf:"bytes,3,opt,name=bucket" json:"bucket,omitempty"`
	Region      string `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	Zone        string `protobuf:"bytes,5,opt,name=zone" json:"zone,omitempty"`
	Status      string `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	Process     string `protobuf:"bytes,7,opt,name=process" json:"process,omitempty"`
	RestoreDb   string `protobuf:"bytes,8,opt,name=restore_db" json:"restore_db,omitempty"`
	RestoreSnap string `protobuf:"bytes,9,opt,name=restore_snap" json:"restore_snap,omitempty"`
	Created     string `protobuf:"bytes,10,opt,name=created" json:"created,omitempty"`
	DbName      string `protobuf:"bytes,11,opt,name=db_name" json:"db_name,omitempty"`
	DbCluster   string `protobuf:"bytes,12,opt,name=db_cluster" json:"db_cluster,omitempty"`
}

func (m *Snapshot) Reset()                    { *m = Snapshot{} }
func (m *Snapshot) String() string            { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()               {}
func (*Snapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "db.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "db.DeleteRequest")
	proto.RegisterType((*BackupRequest)(nil), "db.BackupRequest")
	proto.RegisterType((*RestoreRequest)(nil), "db.RestoreRequest")
	proto.RegisterType((*DescribeRequest)(nil), "db.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "db.DescribeResponse")
	proto.RegisterType((*DbPodSpecs)(nil), "db.DbPodSpecs")
	proto.RegisterType((*ListRequest)(nil), "db.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "db.ListResponse")
	proto.RegisterType((*Database)(nil), "db.Database")
	proto.RegisterType((*SnapshotListRequest)(nil), "db.SnapshotListRequest")
	proto.RegisterType((*SnapshotListResponse)(nil), "db.SnapshotListResponse")
	proto.RegisterType((*Snapshot)(nil), "db.Snapshot")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Databases service

type DatabasesClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type databasesClient struct {
	cc *grpc.ClientConn
}

func NewDatabasesClient(cc *grpc.ClientConn) DatabasesClient {
	return &databasesClient{cc}
}

func (c *databasesClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/db.Databases/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databasesClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/db.Databases/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databasesClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/db.Databases/Backup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databasesClient) SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error) {
	out := new(SnapshotListResponse)
	err := grpc.Invoke(ctx, "/db.Databases/SnapshotList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databasesClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/db.Databases/Restore", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databasesClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/db.Databases/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databasesClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/db.Databases/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Databases service

type DatabasesServer interface {
	Create(context.Context, *CreateRequest) (*dtypes.VoidResponse, error)
	Delete(context.Context, *DeleteRequest) (*dtypes.VoidResponse, error)
	Backup(context.Context, *BackupRequest) (*dtypes.VoidResponse, error)
	SnapshotList(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error)
	Restore(context.Context, *RestoreRequest) (*dtypes.VoidResponse, error)
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterDatabasesServer(s *grpc.Server, srv DatabasesServer) {
	s.RegisterService(&_Databases_serviceDesc, srv)
}

func _Databases_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DatabasesServer).Create(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Databases_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DatabasesServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Databases_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DatabasesServer).Backup(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Databases_SnapshotList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SnapshotListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DatabasesServer).SnapshotList(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Databases_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DatabasesServer).Restore(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Databases_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DatabasesServer).Describe(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Databases_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DatabasesServer).List(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Databases_serviceDesc = grpc.ServiceDesc{
	ServiceName: "db.Databases",
	HandlerType: (*DatabasesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Databases_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Databases_Delete_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _Databases_Backup_Handler,
		},
		{
			MethodName: "SnapshotList",
			Handler:    _Databases_SnapshotList_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Databases_Restore_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Databases_Describe_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Databases_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0x24, 0x35,
	0x10, 0xd6, 0xfc, 0x75, 0x66, 0x6a, 0x7e, 0x92, 0x75, 0xb2, 0xa1, 0x35, 0xec, 0x2e, 0xa8, 0x05,
	0x68, 0x89, 0xd0, 0xcc, 0xee, 0x72, 0x43, 0x08, 0x24, 0xc8, 0x11, 0x09, 0x94, 0x48, 0x1c, 0xe0,
	0xd0, 0x72, 0xb7, 0x4d, 0xa6, 0x95, 0xa1, 0xdd, 0xb4, 0xbb, 0x47, 0x22, 0x51, 0x2e, 0x3c, 0x00,
	0x17, 0xce, 0xbc, 0x0a, 0x0f, 0xc0, 0x95, 0x13, 0x77, 0x9e, 0x82, 0x13, 0xee, 0xb2, 0x3d, 0x63,
	0x0f, 0x9d, 0x55, 0xe0, 0x32, 0x52, 0x97, 0xed, 0xaf, 0xfc, 0x7d, 0xf5, 0x95, 0x6b, 0x60, 0xc8,
	0x92, 0x45, 0x51, 0x8a, 0x4a, 0x90, 0x2e, 0x4b, 0xe6, 0x4f, 0xae, 0x84, 0xb8, 0x5a, 0xf3, 0x25,
	0x2d, 0xb2, 0x25, 0xcd, 0x73, 0x51, 0xd1, 0x2a, 0x13, 0xb9, 0xd4, 0x3b, 0xe6, 0xa7, 0x4d, 0x98,
	0x55, 0x3f, 0x16, 0x5c, 0x2e, 0xf1, 0x57, 0xc7, 0xa3, 0xdf, 0x3a, 0x30, 0xfd, 0xbc, 0xe4, 0xb4,
	0xe2, 0x17, 0xfc, 0x87, 0x9a, 0xcb, 0x8a, 0x4c, 0xa0, 0xdf, 0x6c, 0x08, 0x3b, 0x6f, 0x77, 0x9e,
	0x8f, 0xc8, 0x18, 0x7a, 0xf2, 0xba, 0x0e, 0xbb, 0xf8, 0xa1, 0x96, 0x72, 0xfa, 0x3d, 0x0f, 0x7b,
	0xf8, 0x75, 0x08, 0x07, 0xe9, 0xba, 0x96, 0x15, 0x2f, 0xc3, 0x3e, 0x06, 0x00, 0xba, 0xc5, 0x26,
	0x1c, 0xd8, 0xc5, 0x62, 0x13, 0xcb, 0xec, 0x86, 0x87, 0x81, 0x0a, 0xf4, 0xf0, 0xac, 0x60, 0x3c,
	0x3c, 0x50, 0x5f, 0x03, 0x32, 0x83, 0xa0, 0xe4, 0x57, 0xea, 0x7e, 0xe1, 0x10, 0xb7, 0x1f, 0xc3,
	0x38, 0xa9, 0xd3, 0x6b, 0x5e, 0xc5, 0x98, 0x60, 0x84, 0x41, 0x05, 0x98, 0x96, 0x9c, 0xf1, 0xbc,
	0xca, 0xe8, 0x3a, 0x04, 0x8b, 0xbb, 0xe1, 0xa5, 0x6c, 0x4e, 0x8e, 0x9b, 0x40, 0xf4, 0x31, 0x4c,
	0xcf, 0xf9, 0x9a, 0xdf, 0x77, 0x7f, 0x7b, 0xe5, 0xee, 0xfe, 0x95, 0x91, 0x43, 0xf4, 0xbb, 0xa2,
	0xff, 0x19, 0x4d, 0xaf, 0xeb, 0xc2, 0x1e, 0x77, 0xb6, 0xb4, 0x21, 0x58, 0xf4, 0x5e, 0xdb, 0xb5,
	0xfb, 0x36, 0x28, 0xb9, 0xba, 0xb8, 0x09, 0x6a, 0x3d, 0x1e, 0xc3, 0x54, 0xe6, 0xb4, 0x90, 0x2b,
	0x61, 0xc2, 0x41, 0x0b, 0xc5, 0x03, 0x8c, 0xed, 0x6b, 0x13, 0xc2, 0x11, 0xad, 0xab, 0x55, 0xec,
	0x82, 0x6a, 0x81, 0xa6, 0x30, 0xf8, 0x4e, 0x94, 0x29, 0x47, 0x6d, 0x86, 0xd1, 0xdf, 0x1d, 0x98,
	0x5d, 0x28, 0x0e, 0xa2, 0xe4, 0xff, 0x8b, 0x8d, 0xae, 0x5f, 0x7f, 0xbf, 0x7e, 0x03, 0xac, 0x9f,
	0x31, 0x42, 0xb0, 0x45, 0xd9, 0x15, 0xd3, 0xe5, 0x56, 0xac, 0x32, 0xf6, 0x5f, 0x6b, 0xba, 0x23,
	0x3c, 0x6e, 0x13, 0x70, 0xb2, 0x5f, 0xf8, 0xa9, 0x4f, 0x7e, 0x86, 0xe4, 0x3f, 0x81, 0xc3, 0x73,
	0x2e, 0xd3, 0x32, 0x4b, 0x5e, 0x4b, 0x1e, 0xe9, 0xb6, 0xb8, 0x39, 0xba, 0x81, 0xa3, 0xdd, 0x79,
	0x59, 0xa8, 0xce, 0xe1, 0xe4, 0x19, 0x04, 0x52, 0xb5, 0x51, 0x2d, 0xf1, 0xfc, 0xf8, 0xd5, 0x6c,
	0xa1, 0x3b, 0x68, 0x71, 0x89, 0x51, 0xf2, 0x04, 0xfa, 0x85, 0x60, 0x52, 0xe1, 0xf5, 0xf4, 0x6a,
	0xb2, 0x38, 0x4f, 0xbe, 0x12, 0xec, 0xb2, 0xe0, 0xa9, 0x24, 0x27, 0x30, 0x91, 0xbc, 0xdc, 0x64,
	0x29, 0x8f, 0x9d, 0xae, 0x51, 0x02, 0xd8, 0x68, 0x56, 0x68, 0xb1, 0xa3, 0x6f, 0x00, 0x9c, 0x73,
	0xf6, 0x5e, 0x1d, 0x4b, 0xb3, 0x58, 0x51, 0x69, 0x2f, 0xfd, 0x08, 0x46, 0xa9, 0xc8, 0x59, 0xd6,
	0xf4, 0xb6, 0x41, 0x9c, 0x6d, 0x6f, 0xd9, 0xf7, 0x58, 0xa2, 0xf1, 0xa2, 0x37, 0x61, 0xfc, 0x45,
	0x26, 0x2b, 0xa7, 0x3b, 0xb0, 0x44, 0x08, 0x1e, 0x7d, 0x09, 0x13, 0xbd, 0xf8, 0x40, 0xc2, 0x6f,
	0xc1, 0x88, 0xd1, 0x8a, 0x26, 0xea, 0x3e, 0x96, 0xf5, 0x04, 0x59, 0x9b, 0x60, 0xf4, 0x73, 0x17,
	0x86, 0xf6, 0xc3, 0xcf, 0xd5, 0xc8, 0x61, 0xaa, 0x11, 0x3b, 0x0e, 0x9c, 0x03, 0xb9, 0xae, 0x13,
	0x5e, 0xe6, 0xaa, 0x83, 0x65, 0x6c, 0x94, 0x31, 0xc4, 0x14, 0xd7, 0x66, 0xa7, 0x2c, 0x68, 0xca,
	0xdb, 0xb8, 0xf9, 0x9e, 0x74, 0x0c, 0xa2, 0xfb, 0xe8, 0x14, 0x66, 0xb4, 0x4c, 0x57, 0xd9, 0x86,
	0xc7, 0xda, 0x87, 0xc6, 0x97, 0x4f, 0xe1, 0xb1, 0x1f, 0x8f, 0x8d, 0xfb, 0x46, 0xb6, 0x53, 0x55,
	0xbb, 0x89, 0xd8, 0x5a, 0x1a, 0x4d, 0x3a, 0x70, 0x1b, 0x62, 0x8c, 0x0d, 0xd1, 0xb8, 0x0b, 0x1f,
	0x4e, 0x66, 0x1c, 0xaa, 0x6c, 0xbb, 0xa6, 0xb2, 0x8a, 0x13, 0x7c, 0x4f, 0xb4, 0x4b, 0xa3, 0x97,
	0x70, 0x7c, 0x69, 0x80, 0xf6, 0xca, 0xe0, 0x3f, 0x52, 0x28, 0x14, 0x4a, 0x12, 0x5d, 0xc0, 0x89,
	0x7f, 0xe4, 0x81, 0xc5, 0x99, 0x43, 0x7f, 0xad, 0xf6, 0xbb, 0x75, 0xb1, 0x38, 0xd1, 0x9f, 0x1d,
	0x18, 0xda, 0x8f, 0x3d, 0x83, 0x1d, 0xc1, 0x50, 0x8d, 0x82, 0x4d, 0xc6, 0x54, 0x9b, 0x74, 0xad,
	0xa1, 0x8c, 0x60, 0xbd, 0xbd, 0xfe, 0xdc, 0x16, 0xe1, 0x46, 0xe4, 0xb6, 0x08, 0x3b, 0xfb, 0x6d,
	0xeb, 0xa0, 0xf0, 0x52, 0x2e, 0xa5, 0xa9, 0x83, 0x72, 0x7c, 0xa9, 0x5f, 0xa5, 0x98, 0x25, 0xa6,
	0x06, 0xca, 0x0c, 0x36, 0xd6, 0xe8, 0x6c, 0xa4, 0x77, 0x24, 0xdd, 0xbe, 0xf6, 0x2c, 0xd1, 0x76,
	0x19, 0x5b, 0x2c, 0x15, 0xb0, 0x5d, 0x8d, 0xba, 0xbf, 0xfa, 0x75, 0x00, 0x23, 0xeb, 0x39, 0x49,
	0xbe, 0x85, 0x40, 0xcf, 0x33, 0xf2, 0xa8, 0x51, 0xc0, 0x9b, 0x6d, 0xf3, 0x13, 0x2b, 0xd9, 0xd7,
	0x22, 0x63, 0x56, 0xd8, 0xe8, 0xf9, 0x4f, 0x7f, 0xfc, 0xf5, 0x4b, 0x37, 0x9a, 0x3f, 0xc5, 0xd9,
	0xc9, 0x92, 0xe5, 0xe6, 0xc5, 0xe2, 0xe5, 0xf2, 0xd6, 0x64, 0xb9, 0x5b, 0xde, 0x36, 0x67, 0xee,
	0x3e, 0xea, 0x9c, 0x91, 0x18, 0x02, 0x3d, 0x6c, 0x34, 0xb8, 0x37, 0x78, 0xee, 0x01, 0xff, 0x00,
	0xc1, 0xdf, 0x3b, 0x7b, 0xe7, 0xb5, 0xe0, 0xcb, 0xdb, 0x86, 0xe4, 0x1d, 0x49, 0x20, 0xd0, 0xe3,
	0x48, 0x27, 0xf0, 0x46, 0xd3, 0x3d, 0x09, 0x96, 0x98, 0xe0, 0xfd, 0xc8, 0x4f, 0xa0, 0x4d, 0xd8,
	0x4a, 0x82, 0xc2, 0xc4, 0xf5, 0x17, 0x79, 0xc3, 0x75, 0x8a, 0x63, 0xd2, 0x79, 0xf8, 0xef, 0x05,
	0x93, 0xf3, 0x19, 0xe6, 0x0c, 0xc9, 0xa9, 0x97, 0xd3, 0x76, 0x8c, 0x24, 0x1c, 0x0e, 0xcc, 0x20,
	0x22, 0xa4, 0x01, 0xf1, 0xa7, 0xd2, 0x3d, 0x44, 0x5e, 0x20, 0xe8, 0xd9, 0xfc, 0x5d, 0x0f, 0xd4,
	0xd8, 0xa4, 0x95, 0x49, 0xaa, 0x1e, 0x1b, 0xf3, 0x66, 0x93, 0x63, 0x5d, 0x10, 0x6f, 0x02, 0x34,
	0x89, 0xdc, 0xa0, 0x5f, 0x12, 0xf2, 0xb0, 0x92, 0x7c, 0x0a, 0x7d, 0x94, 0xe9, 0xb0, 0xc1, 0x72,
	0xe5, 0x39, 0xda, 0x05, 0x0c, 0xf0, 0x09, 0x02, 0xcf, 0xc8, 0xc4, 0x05, 0x4e, 0x02, 0xfc, 0xa7,
	0xf5, 0xe1, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0x1c, 0xaa, 0x0f, 0xaf, 0x09, 0x00, 0x00,
}
