// Code generated by protoc-gen-go.
// source: dashboard.proto
// DO NOT EDIT!

/*
Package monitoring is a generated protocol buffer package.

It is generated from these files:
	dashboard.proto

It has these top-level messages:
	DashboardCreateRequest
	DashboardCreateResponse
*/
package monitoring

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type DashboardCreateRequest struct {
	Type        string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ClusterName string `protobuf:"bytes,2,opt,name=cluster_name" json:"cluster_name,omitempty"`
	ObjectName  string `protobuf:"bytes,3,opt,name=object_name" json:"object_name,omitempty"`
	Namespace   string `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *DashboardCreateRequest) Reset()                    { *m = DashboardCreateRequest{} }
func (m *DashboardCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*DashboardCreateRequest) ProtoMessage()               {}
func (*DashboardCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DashboardCreateResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Url    string         `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *DashboardCreateResponse) Reset()                    { *m = DashboardCreateResponse{} }
func (m *DashboardCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*DashboardCreateResponse) ProtoMessage()               {}
func (*DashboardCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DashboardCreateResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*DashboardCreateRequest)(nil), "monitoring.DashboardCreateRequest")
	proto.RegisterType((*DashboardCreateResponse)(nil), "monitoring.DashboardCreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Dashboard service

type DashboardClient interface {
	Create(ctx context.Context, in *DashboardCreateRequest, opts ...grpc.CallOption) (*DashboardCreateResponse, error)
}

type dashboardClient struct {
	cc *grpc.ClientConn
}

func NewDashboardClient(cc *grpc.ClientConn) DashboardClient {
	return &dashboardClient{cc}
}

func (c *dashboardClient) Create(ctx context.Context, in *DashboardCreateRequest, opts ...grpc.CallOption) (*DashboardCreateResponse, error) {
	out := new(DashboardCreateResponse)
	err := grpc.Invoke(ctx, "/monitoring.Dashboard/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dashboard service

type DashboardServer interface {
	Create(context.Context, *DashboardCreateRequest) (*DashboardCreateResponse, error)
}

func RegisterDashboardServer(s *grpc.Server, srv DashboardServer) {
	s.RegisterService(&_Dashboard_serviceDesc, srv)
}

func _Dashboard_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DashboardCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DashboardServer).Create(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Dashboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.Dashboard",
	HandlerType: (*DashboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Dashboard_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0xe9, 0xcc, 0x50, 0xe8, 0xed, 0xf0, 0xff, 0x18, 0x65, 0x2c, 0x45, 0x06, 0xe9, 0x6c,
	0xd4, 0x45, 0xa2, 0xe3, 0xce, 0xad, 0xe2, 0x03, 0xe8, 0x03, 0x48, 0xda, 0x5e, 0x6a, 0xa5, 0x93,
	0x1b, 0x93, 0x54, 0x10, 0x5c, 0xb9, 0x73, 0xed, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0xd3, 0x04, 0x67,
	0x16, 0x8a, 0x9b, 0x40, 0x3e, 0x4e, 0xce, 0x39, 0x39, 0xf0, 0xbf, 0x96, 0xf6, 0xbe, 0x24, 0x69,
	0x6a, 0xae, 0x0d, 0x39, 0x62, 0xb0, 0x22, 0xd5, 0x3a, 0x32, 0xad, 0x6a, 0xf2, 0x83, 0x86, 0xa8,
	0xe9, 0x50, 0x48, 0xdd, 0x0a, 0xa9, 0x14, 0x39, 0xe9, 0x5a, 0x52, 0x36, 0x28, 0xf3, 0xd9, 0x80,
	0x6b, 0xf7, 0xac, 0xd1, 0x0a, 0x7f, 0x06, 0x5e, 0xd4, 0x30, 0xbb, 0xfa, 0x36, 0xbd, 0x34, 0x28,
	0x1d, 0xde, 0xe0, 0x63, 0x8f, 0xd6, 0xb1, 0x29, 0x4c, 0x06, 0x61, 0x16, 0x1d, 0x46, 0x47, 0x09,
	0xdb, 0x83, 0x69, 0xd5, 0xf5, 0xd6, 0xa1, 0xb9, 0x53, 0x72, 0x85, 0xd9, 0xc8, 0xd3, 0x5d, 0x48,
	0xa9, 0x7c, 0xc0, 0xca, 0x05, 0x38, 0xf6, 0x70, 0x07, 0x92, 0xe1, 0x66, 0xb5, 0xac, 0x30, 0x9b,
	0x0c, 0xa8, 0xb8, 0x86, 0xfd, 0x1f, 0x29, 0x56, 0xaf, 0xdb, 0x21, 0x9b, 0x43, 0x6c, 0xd7, 0x55,
	0x7b, 0xeb, 0x83, 0xd2, 0xe5, 0x3f, 0x1e, 0x5a, 0xf2, 0x5b, 0x4f, 0x59, 0x0a, 0xe3, 0xde, 0x74,
	0x21, 0x6f, 0xf9, 0x16, 0x41, 0xb2, 0x31, 0x62, 0x2f, 0x10, 0x07, 0x33, 0x56, 0xf0, 0xed, 0x10,
	0xfc, 0xf7, 0xff, 0xe4, 0x8b, 0x3f, 0x35, 0xa1, 0x4d, 0x71, 0xfc, 0xfa, 0xf1, 0xf9, 0x3e, 0x5a,
	0xe4, 0x73, 0x3f, 0xe3, 0xf6, 0x81, 0x78, 0x3a, 0xe5, 0x67, 0x62, 0x33, 0xff, 0x45, 0x74, 0x52,
	0xc6, 0x7e, 0xc0, 0xf3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0xd1, 0x05, 0x75, 0x95, 0x01,
	0x00, 0x00,
}
