// Code generated by protoc-gen-go.
// source: client.proto
// DO NOT EDIT!

/*
Package kubernetes is a generated protocol buffer package.

It is generated from these files:
	client.proto
	clusters.proto

It has these top-level messages:
	ClientRequest
	NodeListResponse
	Node
	NamespaceListResponse
	Namespace
	SecretListResponse
	Secret
	JobListResponse
	Job
	PodListResponse
	Pod
	Container
	ServiceListResponse
	Service
	AppDescribeRequest
	AppDescribeResponse
	AppListResponse
	App
	ReplicationControllerListResponse
	ReplicationController
	Cluster
	ClusterDescribeRequest
	ClusterDescribeResponse
	ClusterListResponse
	ClusterCreateRequest
	ClusterScaleRequest
	ClusterDeleteRequest
	ClusterStartupScriptRequest
	ClusterStartupScriptResponse
	ClusterConfigRequest
	ClusterConfigResponse
*/
package kubernetes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ClientRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *ClientRequest) Reset()                    { *m = ClientRequest{} }
func (m *ClientRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()               {}
func (*ClientRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodeListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Nodes  []*Node        `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *NodeListResponse) Reset()                    { *m = NodeListResponse{} }
func (m *NodeListResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeListResponse) ProtoMessage()               {}
func (*NodeListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NodeListResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Name             string             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ProviderId       string             `protobuf:"bytes,2,opt,name=provider_id" json:"provider_id,omitempty"`
	CreatedAt        string             `protobuf:"bytes,3,opt,name=created_at" json:"created_at,omitempty"`
	Capacity         *Node_NodeCapacity `protobuf:"bytes,4,opt,name=capacity" json:"capacity,omitempty"`
	OsImage          string             `protobuf:"bytes,5,opt,name=os_image" json:"os_image,omitempty"`
	KernelVersion    string             `protobuf:"bytes,6,opt,name=kernel_version" json:"kernel_version,omitempty"`
	ContainerRuntime string             `protobuf:"bytes,7,opt,name=container_runtime" json:"container_runtime,omitempty"`
	KubeletVersion   string             `protobuf:"bytes,8,opt,name=kubelet_version" json:"kubelet_version,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetCapacity() *Node_NodeCapacity {
	if m != nil {
		return m.Capacity
	}
	return nil
}

type Node_NodeCapacity struct {
	Cpu    int64 `protobuf:"varint,1,opt,name=cpu" json:"cpu,omitempty"`
	Memory int64 `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
	Pods   int64 `protobuf:"varint,3,opt,name=pods" json:"pods,omitempty"`
}

func (m *Node_NodeCapacity) Reset()                    { *m = Node_NodeCapacity{} }
func (m *Node_NodeCapacity) String() string            { return proto.CompactTextString(m) }
func (*Node_NodeCapacity) ProtoMessage()               {}
func (*Node_NodeCapacity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type NamespaceListResponse struct {
	Status     *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Namespaces []*Namespace   `protobuf:"bytes,2,rep,name=namespaces" json:"namespaces,omitempty"`
}

func (m *NamespaceListResponse) Reset()                    { *m = NamespaceListResponse{} }
func (m *NamespaceListResponse) String() string            { return proto.CompactTextString(m) }
func (*NamespaceListResponse) ProtoMessage()               {}
func (*NamespaceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NamespaceListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NamespaceListResponse) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

type Namespace struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at" json:"created_at,omitempty"`
	Phase     string `protobuf:"bytes,3,opt,name=phase" json:"phase,omitempty"`
}

func (m *Namespace) Reset()                    { *m = Namespace{} }
func (m *Namespace) String() string            { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()               {}
func (*Namespace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SecretListResponse struct {
	Status  *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Secrets []*Secret      `protobuf:"bytes,2,rep,name=secrets" json:"secrets,omitempty"`
}

func (m *SecretListResponse) Reset()                    { *m = SecretListResponse{} }
func (m *SecretListResponse) String() string            { return proto.CompactTextString(m) }
func (*SecretListResponse) ProtoMessage()               {}
func (*SecretListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SecretListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SecretListResponse) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type Secret struct {
	Name            string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace       string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	ResourceVersion string `protobuf:"bytes,3,opt,name=resource_version" json:"resource_version,omitempty"`
	SecretType      string `protobuf:"bytes,4,opt,name=secret_type" json:"secret_type,omitempty"`
	CreatedAt       string `protobuf:"bytes,5,opt,name=created_at" json:"created_at,omitempty"`
}

func (m *Secret) Reset()                    { *m = Secret{} }
func (m *Secret) String() string            { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()               {}
func (*Secret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type JobListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Jobs   []*Job         `protobuf:"bytes,2,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *JobListResponse) Reset()                    { *m = JobListResponse{} }
func (m *JobListResponse) String() string            { return proto.CompactTextString(m) }
func (*JobListResponse) ProtoMessage()               {}
func (*JobListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *JobListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *JobListResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type Job struct {
	Name           string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace      string       `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	App            string       `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	CreatedAt      string       `protobuf:"bytes,4,opt,name=created_at" json:"created_at,omitempty"`
	Parallelism    int32        `protobuf:"varint,5,opt,name=parallelism" json:"parallelism,omitempty"`
	Completions    int32        `protobuf:"varint,6,opt,name=completions" json:"completions,omitempty"`
	Containers     []*Container `protobuf:"bytes,7,rep,name=containers" json:"containers,omitempty"`
	StartTime      string       `protobuf:"bytes,8,opt,name=start_time" json:"start_time,omitempty"`
	CompletionTime string       `protobuf:"bytes,9,opt,name=completion_time" json:"completion_time,omitempty"`
	Active         int32        `protobuf:"varint,10,opt,name=active" json:"active,omitempty"`
	Succeeded      int32        `protobuf:"varint,11,opt,name=succeeded" json:"succeeded,omitempty"`
	Failed         int32        `protobuf:"varint,12,opt,name=failed" json:"failed,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Job) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type PodListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Pods   []*Pod         `protobuf:"bytes,2,rep,name=pods" json:"pods,omitempty"`
}

func (m *PodListResponse) Reset()                    { *m = PodListResponse{} }
func (m *PodListResponse) String() string            { return proto.CompactTextString(m) }
func (*PodListResponse) ProtoMessage()               {}
func (*PodListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PodListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PodListResponse) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type Pod struct {
	Name           string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace      string       `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	App            string       `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	CreatedAt      string       `protobuf:"bytes,4,opt,name=created_at" json:"created_at,omitempty"`
	Containers     []*Container `protobuf:"bytes,5,rep,name=containers" json:"containers,omitempty"`
	ServiceAccount string       `protobuf:"bytes,6,opt,name=service_account" json:"service_account,omitempty"`
	NodeName       string       `protobuf:"bytes,7,opt,name=node_name" json:"node_name,omitempty"`
	Phase          string       `protobuf:"bytes,8,opt,name=phase" json:"phase,omitempty"`
	StartTime      string       `protobuf:"bytes,9,opt,name=start_time" json:"start_time,omitempty"`
	Message        string       `protobuf:"bytes,10,opt,name=message" json:"message,omitempty"`
}

func (m *Pod) Reset()                    { *m = Pod{} }
func (m *Pod) String() string            { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()               {}
func (*Pod) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Pod) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Container struct {
	Name     string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image    string   `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Commands []string `protobuf:"bytes,3,rep,name=commands" json:"commands,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ServiceListResponse struct {
	Status   *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Services []*Service     `protobuf:"bytes,2,rep,name=services" json:"services,omitempty"`
}

func (m *ServiceListResponse) Reset()                    { *m = ServiceListResponse{} }
func (m *ServiceListResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceListResponse) ProtoMessage()               {}
func (*ServiceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ServiceListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ServiceListResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                  string                         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace             string                         `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	App                   string                         `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	CreatedAt             string                         `protobuf:"bytes,4,opt,name=created_at" json:"created_at,omitempty"`
	Type                  string                         `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	ClusterIp             string                         `protobuf:"bytes,6,opt,name=cluster_ip" json:"cluster_ip,omitempty"`
	Ports                 []*Service_Port                `protobuf:"bytes,7,rep,name=ports" json:"ports,omitempty"`
	ExternalIps           []string                       `protobuf:"bytes,8,rep,name=external_ips" json:"external_ips,omitempty"`
	LoadbalancerIngresses []*Service_LoadBalancerIngress `protobuf:"bytes,9,rep,name=loadbalancer_ingresses" json:"loadbalancer_ingresses,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Service) GetPorts() []*Service_Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Service) GetLoadbalancerIngresses() []*Service_LoadBalancerIngress {
	if m != nil {
		return m.LoadbalancerIngresses
	}
	return nil
}

type Service_Port struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Protocol   string `protobuf:"bytes,2,opt,name=protocol" json:"protocol,omitempty"`
	Port       int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	TargetPort string `protobuf:"bytes,4,opt,name=target_port" json:"target_port,omitempty"`
	NodePort   int32  `protobuf:"varint,5,opt,name=node_port" json:"node_port,omitempty"`
}

func (m *Service_Port) Reset()                    { *m = Service_Port{} }
func (m *Service_Port) String() string            { return proto.CompactTextString(m) }
func (*Service_Port) ProtoMessage()               {}
func (*Service_Port) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 0} }

type Service_LoadBalancerIngress struct {
	HostName string `protobuf:"bytes,1,opt,name=host_name" json:"host_name,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *Service_LoadBalancerIngress) Reset()                    { *m = Service_LoadBalancerIngress{} }
func (m *Service_LoadBalancerIngress) String() string            { return proto.CompactTextString(m) }
func (*Service_LoadBalancerIngress) ProtoMessage()               {}
func (*Service_LoadBalancerIngress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 1} }

type AppDescribeRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Cluster   string `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *AppDescribeRequest) Reset()                    { *m = AppDescribeRequest{} }
func (m *AppDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*AppDescribeRequest) ProtoMessage()               {}
func (*AppDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type AppDescribeResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	App    *Service       `protobuf:"bytes,2,opt,name=app" json:"app,omitempty"`
}

func (m *AppDescribeResponse) Reset()                    { *m = AppDescribeResponse{} }
func (m *AppDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*AppDescribeResponse) ProtoMessage()               {}
func (*AppDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AppDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AppDescribeResponse) GetApp() *Service {
	if m != nil {
		return m.App
	}
	return nil
}

type AppListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Apps   []*App         `protobuf:"bytes,2,rep,name=apps" json:"apps,omitempty"`
}

func (m *AppListResponse) Reset()                    { *m = AppListResponse{} }
func (m *AppListResponse) String() string            { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()               {}
func (*AppListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AppListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AppListResponse) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type App struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at" json:"created_at,omitempty"`
	Type      string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	ClusterIp string `protobuf:"bytes,6,opt,name=cluster_ip" json:"cluster_ip,omitempty"`
}

func (m *App) Reset()                    { *m = App{} }
func (m *App) String() string            { return proto.CompactTextString(m) }
func (*App) ProtoMessage()               {}
func (*App) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type ReplicationControllerListResponse struct {
	Status                 *dtypes.Status           `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	ReplicationControllers []*ReplicationController `protobuf:"bytes,2,rep,name=replication_controllers" json:"replication_controllers,omitempty"`
}

func (m *ReplicationControllerListResponse) Reset()         { *m = ReplicationControllerListResponse{} }
func (m *ReplicationControllerListResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicationControllerListResponse) ProtoMessage()    {}
func (*ReplicationControllerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18}
}

func (m *ReplicationControllerListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplicationControllerListResponse) GetReplicationControllers() []*ReplicationController {
	if m != nil {
		return m.ReplicationControllers
	}
	return nil
}

type ReplicationController struct {
	Name               string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace          string       `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	App                string       `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	CreatedAt          string       `protobuf:"bytes,4,opt,name=created_at" json:"created_at,omitempty"`
	Generation         int64        `protobuf:"varint,5,opt,name=generation" json:"generation,omitempty"`
	CurrentReplicas    int32        `protobuf:"varint,6,opt,name=current_replicas" json:"current_replicas,omitempty"`
	Replicas           int32        `protobuf:"varint,7,opt,name=replicas" json:"replicas,omitempty"`
	ObservedGeneration int64        `protobuf:"varint,8,opt,name=observed_generation" json:"observed_generation,omitempty"`
	Containers         []*Container `protobuf:"bytes,9,rep,name=containers" json:"containers,omitempty"`
}

func (m *ReplicationController) Reset()                    { *m = ReplicationController{} }
func (m *ReplicationController) String() string            { return proto.CompactTextString(m) }
func (*ReplicationController) ProtoMessage()               {}
func (*ReplicationController) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ReplicationController) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientRequest)(nil), "kubernetes.ClientRequest")
	proto.RegisterType((*NodeListResponse)(nil), "kubernetes.NodeListResponse")
	proto.RegisterType((*Node)(nil), "kubernetes.Node")
	proto.RegisterType((*Node_NodeCapacity)(nil), "kubernetes.Node.NodeCapacity")
	proto.RegisterType((*NamespaceListResponse)(nil), "kubernetes.NamespaceListResponse")
	proto.RegisterType((*Namespace)(nil), "kubernetes.Namespace")
	proto.RegisterType((*SecretListResponse)(nil), "kubernetes.SecretListResponse")
	proto.RegisterType((*Secret)(nil), "kubernetes.Secret")
	proto.RegisterType((*JobListResponse)(nil), "kubernetes.JobListResponse")
	proto.RegisterType((*Job)(nil), "kubernetes.Job")
	proto.RegisterType((*PodListResponse)(nil), "kubernetes.PodListResponse")
	proto.RegisterType((*Pod)(nil), "kubernetes.Pod")
	proto.RegisterType((*Container)(nil), "kubernetes.Container")
	proto.RegisterType((*ServiceListResponse)(nil), "kubernetes.ServiceListResponse")
	proto.RegisterType((*Service)(nil), "kubernetes.Service")
	proto.RegisterType((*Service_Port)(nil), "kubernetes.Service.Port")
	proto.RegisterType((*Service_LoadBalancerIngress)(nil), "kubernetes.Service.LoadBalancerIngress")
	proto.RegisterType((*AppDescribeRequest)(nil), "kubernetes.AppDescribeRequest")
	proto.RegisterType((*AppDescribeResponse)(nil), "kubernetes.AppDescribeResponse")
	proto.RegisterType((*AppListResponse)(nil), "kubernetes.AppListResponse")
	proto.RegisterType((*App)(nil), "kubernetes.App")
	proto.RegisterType((*ReplicationControllerListResponse)(nil), "kubernetes.ReplicationControllerListResponse")
	proto.RegisterType((*ReplicationController)(nil), "kubernetes.ReplicationController")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Client service

type ClientClient interface {
	Nodes(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*NodeListResponse, error)
	Secrets(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*SecretListResponse, error)
	Jobs(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*JobListResponse, error)
	Namespaces(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*NamespaceListResponse, error)
	Pods(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*PodListResponse, error)
	Services(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServiceListResponse, error)
	ReplicationControllers(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ReplicationControllerListResponse, error)
	Apps(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*AppListResponse, error)
	App(ctx context.Context, in *AppDescribeRequest, opts ...grpc.CallOption) (*AppDescribeResponse, error)
	AppPods(ctx context.Context, in *AppDescribeRequest, opts ...grpc.CallOption) (*PodListResponse, error)
}

type clientClient struct {
	cc *grpc.ClientConn
}

func NewClientClient(cc *grpc.ClientConn) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) Nodes(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*NodeListResponse, error) {
	out := new(NodeListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/Nodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Secrets(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*SecretListResponse, error) {
	out := new(SecretListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/Secrets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Jobs(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*JobListResponse, error) {
	out := new(JobListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/Jobs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Namespaces(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*NamespaceListResponse, error) {
	out := new(NamespaceListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/Namespaces", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Pods(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*PodListResponse, error) {
	out := new(PodListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/Pods", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Services(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServiceListResponse, error) {
	out := new(ServiceListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/Services", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) ReplicationControllers(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ReplicationControllerListResponse, error) {
	out := new(ReplicationControllerListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/ReplicationControllers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Apps(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/Apps", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) App(ctx context.Context, in *AppDescribeRequest, opts ...grpc.CallOption) (*AppDescribeResponse, error) {
	out := new(AppDescribeResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/App", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) AppPods(ctx context.Context, in *AppDescribeRequest, opts ...grpc.CallOption) (*PodListResponse, error) {
	out := new(PodListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Client/AppPods", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Client service

type ClientServer interface {
	Nodes(context.Context, *ClientRequest) (*NodeListResponse, error)
	Secrets(context.Context, *ClientRequest) (*SecretListResponse, error)
	Jobs(context.Context, *ClientRequest) (*JobListResponse, error)
	Namespaces(context.Context, *ClientRequest) (*NamespaceListResponse, error)
	Pods(context.Context, *ClientRequest) (*PodListResponse, error)
	Services(context.Context, *ClientRequest) (*ServiceListResponse, error)
	ReplicationControllers(context.Context, *ClientRequest) (*ReplicationControllerListResponse, error)
	Apps(context.Context, *ClientRequest) (*AppListResponse, error)
	App(context.Context, *AppDescribeRequest) (*AppDescribeResponse, error)
	AppPods(context.Context, *AppDescribeRequest) (*PodListResponse, error)
}

func RegisterClientServer(s *grpc.Server, srv ClientServer) {
	s.RegisterService(&_Client_serviceDesc, srv)
}

func _Client_Nodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).Nodes(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_Secrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).Secrets(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_Jobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).Jobs(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_Namespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).Namespaces(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_Pods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).Pods(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_Services_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).Services(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_ReplicationControllers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).ReplicationControllers(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_Apps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).Apps(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_App_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AppDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).App(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Client_AppPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AppDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ClientServer).AppPods(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Client_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubernetes.Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Nodes",
			Handler:    _Client_Nodes_Handler,
		},
		{
			MethodName: "Secrets",
			Handler:    _Client_Secrets_Handler,
		},
		{
			MethodName: "Jobs",
			Handler:    _Client_Jobs_Handler,
		},
		{
			MethodName: "Namespaces",
			Handler:    _Client_Namespaces_Handler,
		},
		{
			MethodName: "Pods",
			Handler:    _Client_Pods_Handler,
		},
		{
			MethodName: "Services",
			Handler:    _Client_Services_Handler,
		},
		{
			MethodName: "ReplicationControllers",
			Handler:    _Client_ReplicationControllers_Handler,
		},
		{
			MethodName: "Apps",
			Handler:    _Client_Apps_Handler,
		},
		{
			MethodName: "App",
			Handler:    _Client_App_Handler,
		},
		{
			MethodName: "AppPods",
			Handler:    _Client_AppPods_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 1261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0x5b, 0x6f, 0x1b, 0xc5,
	0x17, 0x97, 0xbd, 0xbe, 0x9e, 0xa4, 0x49, 0x3a, 0xfe, 0x27, 0x75, 0xdd, 0x36, 0x4d, 0xf6, 0x2f,
	0x94, 0x86, 0x52, 0x3b, 0xb4, 0x15, 0x12, 0x37, 0x09, 0x12, 0xc4, 0x4d, 0x55, 0x55, 0x35, 0x0f,
	0x08, 0xa9, 0x92, 0x35, 0x5e, 0x0f, 0xee, 0xd2, 0xf5, 0xce, 0x32, 0xb3, 0x8e, 0x88, 0x4a, 0x5e,
	0xfa, 0x52, 0x10, 0x2f, 0x48, 0xfd, 0x66, 0xf0, 0x09, 0x90, 0xf8, 0x18, 0x3c, 0x70, 0xe6, 0xcc,
	0xae, 0xed, 0x75, 0x56, 0x8e, 0x0d, 0x79, 0xf1, 0x65, 0x2e, 0xe7, 0xf7, 0x3b, 0xbf, 0x73, 0x99,
	0x03, 0xab, 0x5e, 0xe0, 0x8b, 0x30, 0x6e, 0x47, 0x4a, 0xc6, 0x92, 0xc1, 0x8b, 0x51, 0x4f, 0xa8,
	0x50, 0xc4, 0x42, 0xb7, 0x6e, 0x0e, 0xa4, 0x1c, 0x04, 0xa2, 0xc3, 0x23, 0xbf, 0xc3, 0xc3, 0x50,
	0xc6, 0x3c, 0xf6, 0x65, 0xa8, 0xed, 0xc9, 0xd6, 0x96, 0x59, 0xee, 0xc7, 0xa7, 0x91, 0xd0, 0x1d,
	0xfa, 0xb4, 0xeb, 0xee, 0x0e, 0x5c, 0x39, 0x22, 0x8b, 0x4f, 0xc5, 0x0f, 0x23, 0xa1, 0x63, 0xb6,
	0x0e, 0x55, 0x2f, 0x18, 0xe9, 0x58, 0xa8, 0x66, 0x61, 0xa7, 0x70, 0xa7, 0xee, 0x1e, 0xc3, 0xc6,
	0x63, 0xd9, 0x17, 0x8f, 0x7c, 0x8d, 0x67, 0x74, 0x84, 0x26, 0x05, 0xdb, 0x86, 0x8a, 0x46, 0xfb,
	0x23, 0x4d, 0x67, 0x56, 0xee, 0xaf, 0xb5, 0xad, 0xe9, 0xf6, 0x31, 0xad, 0xb2, 0xdb, 0x50, 0x0e,
	0xf1, 0x8e, 0x6e, 0x16, 0x77, 0x1c, 0xdc, 0xde, 0x68, 0x4f, 0x78, 0xb6, 0x8d, 0x31, 0xf7, 0x75,
	0x11, 0x4a, 0xe6, 0x07, 0x5b, 0x85, 0x52, 0xc8, 0x87, 0xc2, 0x62, 0xb1, 0x06, 0xac, 0x20, 0xad,
	0x13, 0xbf, 0x2f, 0x54, 0xd7, 0xef, 0xe3, 0x6d, 0xb3, 0xc8, 0x00, 0x3c, 0x25, 0x78, 0x2c, 0xfa,
	0x5d, 0x1e, 0x37, 0x1d, 0x5a, 0xeb, 0x40, 0xcd, 0xe3, 0x11, 0xf7, 0xfc, 0xf8, 0xb4, 0x59, 0x22,
	0x0a, 0xb7, 0x66, 0x31, 0xe8, 0xe3, 0x28, 0x39, 0xc4, 0x36, 0xa0, 0x26, 0x75, 0xd7, 0x1f, 0xf2,
	0x81, 0x68, 0x96, 0xc9, 0xc4, 0x16, 0xac, 0xbd, 0x30, 0xe7, 0x83, 0xee, 0x89, 0x50, 0x1a, 0xa5,
	0x6a, 0x56, 0x68, 0xfd, 0x3a, 0x5c, 0xf5, 0x64, 0x18, 0x73, 0x3f, 0x44, 0x12, 0x6a, 0x14, 0xc6,
	0x3e, 0xd2, 0xab, 0xd2, 0xd6, 0x35, 0x58, 0x37, 0x20, 0x81, 0x88, 0xc7, 0x77, 0x6a, 0x66, 0xa3,
	0xf5, 0x3e, 0xac, 0x66, 0xd0, 0x56, 0xc0, 0xf1, 0xa2, 0x11, 0x39, 0xe5, 0xb0, 0x35, 0xa8, 0x0c,
	0xc5, 0x50, 0xaa, 0x53, 0xf2, 0xc7, 0x31, 0x2e, 0x47, 0xb2, 0xaf, 0xc9, 0x13, 0xc7, 0xed, 0xc1,
	0xe6, 0x63, 0x14, 0x40, 0xe3, 0xcd, 0xe5, 0x34, 0xde, 0x07, 0x08, 0xd3, 0x8b, 0xa9, 0xd0, 0x9b,
	0x19, 0x11, 0xd2, 0x5d, 0xf7, 0x23, 0xa8, 0x8f, 0xff, 0xcc, 0x28, 0x9e, 0x15, 0xd7, 0x0a, 0x7e,
	0x05, 0xca, 0xd1, 0x73, 0xae, 0x85, 0xd5, 0xda, 0xfd, 0x16, 0xd8, 0xb1, 0xc0, 0x43, 0xf1, 0x52,
	0xf4, 0xfe, 0x0f, 0x55, 0x4d, 0xb7, 0x52, 0x6e, 0x6c, 0x9a, 0x9b, 0x35, 0xe8, 0x06, 0x50, 0xb1,
	0xbf, 0x66, 0x58, 0x5d, 0x85, 0xfa, 0xd8, 0xb7, 0x84, 0x54, 0x13, 0x36, 0x94, 0xd0, 0x72, 0xa4,
	0x3c, 0x31, 0x16, 0xdf, 0x49, 0x93, 0xc6, 0x22, 0x75, 0x0d, 0x01, 0x4a, 0x87, 0x59, 0xbf, 0x28,
	0xe2, 0xee, 0x13, 0x58, 0xff, 0x5a, 0xf6, 0x96, 0xf2, 0xe2, 0x16, 0x94, 0xbe, 0x97, 0xbd, 0xd4,
	0x85, 0xf5, 0x69, 0x17, 0xd0, 0x94, 0xfb, 0x77, 0x01, 0x1c, 0xfc, 0xbe, 0x98, 0x3d, 0x26, 0x04,
	0x8f, 0xa2, 0x84, 0x70, 0x96, 0x5b, 0x69, 0x9c, 0xf9, 0x5c, 0xf1, 0x20, 0x10, 0x81, 0xaf, 0x87,
	0x44, 0xb8, 0x6c, 0x16, 0x3d, 0x39, 0x8c, 0x30, 0xdf, 0x4c, 0x25, 0x53, 0x7e, 0x96, 0x4d, 0xdc,
	0xc7, 0xf9, 0xa9, 0x31, 0x31, 0xcf, 0xc5, 0xfd, 0x28, 0xdd, 0x35, 0x40, 0xe8, 0x9d, 0x42, 0x61,
	0x4c, 0x0e, 0xd7, 0xd2, 0x1c, 0x9e, 0xd8, 0xb4, 0x1b, 0x75, 0xda, 0xc0, 0x34, 0xe5, 0x5e, 0xec,
	0x9f, 0x88, 0x26, 0x10, 0x0e, 0x7a, 0xa1, 0x47, 0x9e, 0x27, 0x44, 0x5f, 0xf4, 0x9b, 0x2b, 0xb4,
	0x84, 0x47, 0xbe, 0xe3, 0x7e, 0x80, 0xff, 0x57, 0xcd, 0x7f, 0x23, 0xe8, 0x13, 0xd9, 0x5f, 0x56,
	0x50, 0x4a, 0xfe, 0x1c, 0x41, 0xd1, 0x94, 0xfb, 0x3b, 0x0a, 0x8a, 0xdf, 0x97, 0x20, 0x68, 0x56,
	0xa6, 0xf2, 0x3c, 0x99, 0x50, 0x12, 0x2d, 0xd4, 0x89, 0x8f, 0x99, 0xc5, 0x3d, 0x4f, 0x62, 0xc9,
	0x27, 0xad, 0xc0, 0xe0, 0x62, 0x59, 0x77, 0x89, 0x4a, 0x35, 0x5b, 0x1b, 0xb5, 0x14, 0x79, 0x4a,
	0x61, 0x2b, 0x24, 0x76, 0x50, 0xe4, 0xaa, 0x4d, 0xa7, 0x01, 0xca, 0xbb, 0x0f, 0xa0, 0x3e, 0x01,
	0xcb, 0x7a, 0x86, 0xe6, 0x6c, 0x4f, 0xb2, 0x5e, 0x61, 0x97, 0xc2, 0xe0, 0x0c, 0x79, 0x48, 0xed,
	0xc1, 0xc1, 0xbb, 0xcf, 0xa0, 0x71, 0x6c, 0xb9, 0x2d, 0x25, 0xf3, 0x5b, 0x50, 0x4b, 0x5c, 0x4a,
	0xa5, 0x6e, 0x64, 0xcb, 0x8f, 0xf6, 0xdc, 0x5f, 0x1c, 0xa8, 0x26, 0xbf, 0x2f, 0x41, 0x72, 0xb4,
	0x40, 0x15, 0x58, 0x1e, 0x9f, 0xb0, 0x0f, 0x49, 0xd7, 0x8f, 0x12, 0x41, 0xf7, 0x50, 0x3d, 0xa9,
	0xe2, 0x34, 0x6d, 0x9b, 0x39, 0x9c, 0x30, 0x0d, 0x54, 0xcc, 0xfe, 0x07, 0xab, 0xe2, 0x47, 0xbc,
	0x1a, 0xf2, 0x00, 0x6f, 0x6b, 0x54, 0x1b, 0xc5, 0x60, 0x5f, 0xc0, 0x56, 0x20, 0x79, 0xbf, 0xc7,
	0x03, 0x1e, 0x7a, 0xc6, 0x6e, 0x38, 0xc0, 0x9e, 0xa0, 0xd1, 0xc7, 0x3a, 0xd9, 0xdb, 0xcb, 0xb3,
	0xf7, 0x08, 0x6f, 0x1c, 0x26, 0x37, 0xbe, 0xb2, 0x17, 0x5a, 0xcf, 0xa0, 0x44, 0x30, 0x59, 0x9f,
	0x51, 0x7d, 0x7a, 0x14, 0x3d, 0x19, 0x24, 0x2e, 0x53, 0xab, 0x56, 0xf6, 0xd1, 0xa1, 0x72, 0xc4,
	0x58, 0x0f, 0xb0, 0xd1, 0xd0, 0x62, 0x29, 0x93, 0x23, 0xb4, 0x44, 0x65, 0xdb, 0x7a, 0x08, 0x8d,
	0x1c, 0x50, 0x73, 0xf2, 0xb9, 0xd4, 0x71, 0x77, 0x0a, 0x11, 0xa0, 0x88, 0xda, 0x10, 0x96, 0xfb,
	0x39, 0xb0, 0x4f, 0xa3, 0xe8, 0x33, 0xa1, 0x3d, 0xe5, 0xf7, 0x44, 0xfa, 0x1c, 0x67, 0x19, 0x4e,
	0x3d, 0xce, 0xc5, 0xf3, 0x61, 0xb2, 0xed, 0xfa, 0x1b, 0x68, 0x64, 0xec, 0x2c, 0x98, 0x31, 0x3b,
	0x36, 0xba, 0x45, 0xda, 0xcc, 0x4d, 0x16, 0xac, 0x76, 0x34, 0xbc, 0x6c, 0xb5, 0xa3, 0xd1, 0xdc,
	0x6a, 0x47, 0x53, 0x98, 0xdc, 0x0e, 0x7e, 0x5d, 0x9c, 0x79, 0xff, 0x2a, 0xd9, 0xdc, 0xd7, 0x05,
	0xd8, 0x7d, 0x2a, 0xa2, 0xc0, 0xf7, 0x68, 0x12, 0x32, 0x25, 0xa8, 0x24, 0x36, 0x58, 0xb5, 0x94,
	0x0b, 0x87, 0x70, 0x4d, 0x4d, 0x8c, 0x74, 0xbd, 0xb1, 0x95, 0xd4, 0xab, 0xdd, 0x69, 0xaf, 0x72,
	0xf1, 0xdc, 0x3f, 0x0b, 0xb0, 0x99, 0xbb, 0x73, 0x09, 0x45, 0x87, 0x6b, 0x03, 0x81, 0x8d, 0x85,
	0x2c, 0x93, 0x1a, 0x8e, 0x79, 0x2b, 0xbd, 0x91, 0x52, 0x38, 0xd5, 0x75, 0x13, 0xee, 0xe9, 0xe3,
	0x81, 0x29, 0x3e, 0x5e, 0xa9, 0xd2, 0xca, 0x0d, 0x68, 0xe0, 0x03, 0x87, 0x21, 0x46, 0xa3, 0x53,
	0x86, 0x6a, 0x64, 0x28, 0xdb, 0x44, 0xeb, 0x73, 0x9a, 0xe8, 0xfd, 0x9f, 0x01, 0x2a, 0x76, 0x92,
	0x64, 0x1a, 0xca, 0x66, 0x1a, 0xd2, 0xec, 0x7a, 0xe6, 0xe8, 0xf4, 0x98, 0xd9, 0xba, 0x39, 0x3b,
	0xae, 0x4d, 0x07, 0xc5, 0x7d, 0xf7, 0xd5, 0x1f, 0x7f, 0xbd, 0x29, 0xde, 0x65, 0xfb, 0x34, 0xcd,
	0x4e, 0x4e, 0x76, 0x4e, 0x0e, 0x3a, 0x76, 0x00, 0xee, 0xbc, 0x4c, 0xe2, 0x7d, 0xd6, 0xa1, 0x49,
	0x93, 0x9d, 0x9a, 0x4e, 0x46, 0xf3, 0xc6, 0x3c, 0xd8, 0xed, 0xf3, 0x43, 0x48, 0x06, 0xf8, 0x01,
	0x01, 0xdf, 0x63, 0x77, 0x17, 0x01, 0x4e, 0xe6, 0x1b, 0x16, 0x41, 0x09, 0x87, 0x80, 0xb9, 0xb8,
	0x37, 0x66, 0x26, 0x87, 0x0c, 0xe8, 0x01, 0x81, 0xbe, 0xcd, 0xee, 0x2c, 0x02, 0x6a, 0xc6, 0x11,
	0xf6, 0xaa, 0x00, 0x30, 0x9e, 0xe8, 0xe6, 0x02, 0xef, 0xe6, 0x4e, 0x84, 0x19, 0xf8, 0xf7, 0x08,
	0xfe, 0x80, 0xb5, 0x17, 0x12, 0x7b, 0x82, 0x1a, 0x99, 0x26, 0xda, 0x5f, 0xdc, 0xed, 0x99, 0x51,
	0x61, 0x39, 0xb7, 0xcd, 0xd0, 0xc0, 0x7e, 0x82, 0x5a, 0xd2, 0x8c, 0xe6, 0xa2, 0xde, 0xce, 0xe9,
	0x5e, 0x19, 0xe4, 0x87, 0x84, 0xdc, 0x66, 0xef, 0x2c, 0x16, 0xe5, 0x04, 0xf1, 0x4d, 0x01, 0xb6,
	0x72, 0xab, 0x78, 0x2e, 0x99, 0x7b, 0x17, 0xb6, 0x87, 0x0c, 0xb5, 0x0e, 0x51, 0xdb, 0x67, 0x7b,
	0x8b, 0x50, 0x53, 0x1e, 0x45, 0x01, 0x7b, 0xe8, 0xe2, 0x51, 0x98, 0x69, 0xe1, 0xcb, 0x45, 0xc1,
	0x34, 0x73, 0xf6, 0x6b, 0xc1, 0xb6, 0xed, 0xed, 0x19, 0xb3, 0x33, 0x4f, 0x57, 0x36, 0x0c, 0x39,
	0x4f, 0x92, 0x7b, 0x44, 0xd0, 0x1f, 0xb3, 0x0f, 0x17, 0x85, 0xee, 0xbc, 0x1c, 0xa7, 0xdf, 0x99,
	0xfd, 0x7d, 0xc6, 0x7e, 0x2b, 0x40, 0x15, 0x8d, 0x53, 0x26, 0x5e, 0xc4, 0x68, 0x6e, 0x3a, 0x7e,
	0x49, 0x6c, 0x0e, 0xd9, 0x27, 0xff, 0x81, 0x0d, 0xa5, 0x69, 0xaf, 0x42, 0x53, 0xc4, 0x83, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xe2, 0x45, 0x2b, 0xac, 0x0f, 0x00, 0x00,
}
