// Code generated by protoc-gen-go.
// source: ssh.proto
// DO NOT EDIT!

/*
Package ssh is a generated protocol buffer package.

It is generated from these files:
	ssh.proto

It has these top-level messages:
	SecureShellGetRequest
	SecureShellGetResponse
	SSHKey
*/
package ssh

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Use specific requests for protos
type SecureShellGetRequest struct {
	JenkinsNamespace string `protobuf:"bytes,1,opt,name=jenkins_namespace" json:"jenkins_namespace,omitempty"`
	ClusterNamespace string `protobuf:"bytes,2,opt,name=cluster_namespace" json:"cluster_namespace,omitempty"`
	ClusterName      string `protobuf:"bytes,3,opt,name=cluster_name" json:"cluster_name,omitempty"`
	InstanceName     string `protobuf:"bytes,4,opt,name=instance_name" json:"instance_name,omitempty"`
}

func (m *SecureShellGetRequest) Reset()                    { *m = SecureShellGetRequest{} }
func (m *SecureShellGetRequest) String() string            { return proto.CompactTextString(m) }
func (*SecureShellGetRequest) ProtoMessage()               {}
func (*SecureShellGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// return phid ?
type SecureShellGetResponse struct {
	Status       *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	SshKey       *SSHKey        `protobuf:"bytes,2,opt,name=ssh_key" json:"ssh_key,omitempty"`
	InstanceAddr string         `protobuf:"bytes,3,opt,name=instance_addr" json:"instance_addr,omitempty"`
	InstancePort int32          `protobuf:"varint,4,opt,name=instance_port" json:"instance_port,omitempty"`
	User         string         `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
}

func (m *SecureShellGetResponse) Reset()                    { *m = SecureShellGetResponse{} }
func (m *SecureShellGetResponse) String() string            { return proto.CompactTextString(m) }
func (*SecureShellGetResponse) ProtoMessage()               {}
func (*SecureShellGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SecureShellGetResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SecureShellGetResponse) GetSshKey() *SSHKey {
	if m != nil {
		return m.SshKey
	}
	return nil
}

type SSHKey struct {
	PublicKey          []byte `protobuf:"bytes,1,opt,name=public_key,proto3" json:"public_key,omitempty"`
	PrivateKey         []byte `protobuf:"bytes,2,opt,name=private_key,proto3" json:"private_key,omitempty"`
	AwsFingerprint     string `protobuf:"bytes,3,opt,name=aws_fingerprint" json:"aws_fingerprint,omitempty"`
	OpensshFingerprint string `protobuf:"bytes,4,opt,name=openssh_fingerprint" json:"openssh_fingerprint,omitempty"`
}

func (m *SSHKey) Reset()                    { *m = SSHKey{} }
func (m *SSHKey) String() string            { return proto.CompactTextString(m) }
func (*SSHKey) ProtoMessage()               {}
func (*SSHKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*SecureShellGetRequest)(nil), "ssh.SecureShellGetRequest")
	proto.RegisterType((*SecureShellGetResponse)(nil), "ssh.SecureShellGetResponse")
	proto.RegisterType((*SSHKey)(nil), "ssh.SSHKey")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for SecureShell service

type SecureShellClient interface {
	Get(ctx context.Context, in *SecureShellGetRequest, opts ...grpc.CallOption) (*SecureShellGetResponse, error)
}

type secureShellClient struct {
	cc *grpc.ClientConn
}

func NewSecureShellClient(cc *grpc.ClientConn) SecureShellClient {
	return &secureShellClient{cc}
}

func (c *secureShellClient) Get(ctx context.Context, in *SecureShellGetRequest, opts ...grpc.CallOption) (*SecureShellGetResponse, error) {
	out := new(SecureShellGetResponse)
	err := grpc.Invoke(ctx, "/ssh.SecureShell/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SecureShell service

type SecureShellServer interface {
	Get(context.Context, *SecureShellGetRequest) (*SecureShellGetResponse, error)
}

func RegisterSecureShellServer(s *grpc.Server, srv SecureShellServer) {
	s.RegisterService(&_SecureShell_serviceDesc, srv)
}

func _SecureShell_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureShellGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureShellServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.SecureShell/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureShellServer).Get(ctx, req.(*SecureShellGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecureShell_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssh.SecureShell",
	HandlerType: (*SecureShellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SecureShell_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4e, 0xf3, 0x30,
	0x14, 0xc4, 0xd5, 0xbf, 0x9f, 0xfa, 0x92, 0x0f, 0x84, 0x4b, 0x4b, 0x9b, 0x56, 0x08, 0xba, 0x62,
	0x95, 0x40, 0x39, 0x04, 0x48, 0xec, 0xc8, 0x01, 0x2a, 0x37, 0x79, 0xa4, 0xa1, 0xc1, 0x36, 0xb6,
	0x53, 0x54, 0x96, 0x1c, 0x01, 0x8e, 0xc6, 0x15, 0x38, 0x08, 0x8e, 0x5d, 0xa1, 0x80, 0xba, 0x89,
	0xa2, 0x19, 0xdb, 0xf3, 0x9b, 0x67, 0x43, 0x4f, 0xa9, 0x55, 0x28, 0x24, 0xd7, 0x9c, 0xb4, 0xcc,
	0x6f, 0x30, 0xcd, 0x38, 0xcf, 0x0a, 0x8c, 0xa8, 0xc8, 0x23, 0xca, 0x18, 0xd7, 0x54, 0xe7, 0x9c,
	0x29, 0xb7, 0x24, 0x18, 0x56, 0x72, 0xaa, 0xb7, 0x02, 0x55, 0x64, 0xbf, 0x4e, 0x9f, 0xbd, 0xc2,
	0x20, 0xc6, 0xa4, 0x94, 0x18, 0xaf, 0xb0, 0x28, 0x6e, 0x50, 0xdf, 0xe3, 0x73, 0x89, 0x4a, 0x93,
	0x31, 0x1c, 0x3d, 0x22, 0x5b, 0xe7, 0x4c, 0x2d, 0x18, 0x7d, 0x42, 0x25, 0x68, 0x82, 0xa3, 0xc6,
	0x59, 0xe3, 0xa2, 0x57, 0x59, 0x49, 0x51, 0x2a, 0x8d, 0xb2, 0x66, 0x35, 0xad, 0x75, 0x0c, 0x7e,
	0xdd, 0x1a, 0xb5, 0xac, 0x3a, 0x80, 0xff, 0xe6, 0x1c, 0x4d, 0x59, 0x82, 0x4e, 0x6e, 0x57, 0xf2,
	0xec, 0xbd, 0x01, 0xc3, 0xbf, 0xe1, 0x4a, 0x18, 0x66, 0x24, 0xa7, 0xd0, 0x35, 0xeb, 0x75, 0xa9,
	0x6c, 0xa4, 0x37, 0x3f, 0x08, 0x1d, 0x7b, 0x18, 0x5b, 0x95, 0x4c, 0xe1, 0x9f, 0xe9, 0xbc, 0x58,
	0xe3, 0xd6, 0x06, 0x7b, 0x73, 0x2f, 0xac, 0xc6, 0x11, 0xc7, 0xb7, 0x77, 0xb8, 0xfd, 0x95, 0x47,
	0xd3, 0x54, 0xee, 0xc1, 0x10, 0x5c, 0x6a, 0x8b, 0xd1, 0x21, 0x3e, 0xb4, 0x4b, 0x85, 0x72, 0xd4,
	0xb1, 0x50, 0x19, 0x74, 0x77, 0xa7, 0x10, 0x00, 0x51, 0x2e, 0x8b, 0x3c, 0xb1, 0x31, 0x15, 0x87,
	0x4f, 0xfa, 0xe0, 0x09, 0x99, 0x6f, 0xa8, 0xc6, 0x9f, 0x6c, 0x9f, 0x9c, 0xc0, 0x21, 0x7d, 0x51,
	0x8b, 0x87, 0x9c, 0x65, 0x28, 0x8d, 0xcd, 0xf4, 0x2e, 0x70, 0x02, 0x7d, 0x2e, 0x90, 0x55, 0xa4,
	0x75, 0xd3, 0xb6, 0x9f, 0x0b, 0xf0, 0x6a, 0xe5, 0x09, 0x85, 0x96, 0x19, 0x00, 0x09, 0x5c, 0x8f,
	0x7d, 0x57, 0x12, 0x4c, 0xf6, 0x7a, 0x6e, 0x62, 0xb3, 0xf3, 0xb7, 0xcf, 0xaf, 0x8f, 0xe6, 0x84,
	0x8c, 0xcd, 0x03, 0x10, 0x2a, 0xe1, 0xa9, 0x7b, 0x09, 0x66, 0x87, 0x01, 0x8d, 0x36, 0x97, 0xe1,
	0xd5, 0xb2, 0x6b, 0xaf, 0xfc, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x39, 0xe3, 0x4c, 0xbb, 0x3a,
	0x02, 0x00, 0x00,
}
