// Code generated by protoc-gen-go.
// source: disk.proto
// DO NOT EDIT!

/*
Package pv is a generated protocol buffer package.

It is generated from these files:
	disk.proto
	pvc.proto
	pv.proto

It has these top-level messages:
	DiskCreateRequest
	DiskDeleteRequest
	DiskListRequest
	DiskListResponse
	Disk
	PVCRegisterRequest
	PVCUnregisterRequest
	PVCListRequest
	PVCListResponse
	PVCList
	PVRegisterRequest
	PVUnregisterRequest
	PVListRequest
	PVListResponse
	PV
*/
package pv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type DiskCreateRequest struct {
	Cluster  string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Zone     string `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
	DiskType string `protobuf:"bytes,4,opt,name=disk_type" json:"disk_type,omitempty"`
	Size     int64  `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
}

func (m *DiskCreateRequest) Reset()                    { *m = DiskCreateRequest{} }
func (m *DiskCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*DiskCreateRequest) ProtoMessage()               {}
func (*DiskCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DiskDeleteRequest struct {
	Cluster    string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *DiskDeleteRequest) Reset()                    { *m = DiskDeleteRequest{} }
func (m *DiskDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DiskDeleteRequest) ProtoMessage()               {}
func (*DiskDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DiskListRequest struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
}

func (m *DiskListRequest) Reset()                    { *m = DiskListRequest{} }
func (m *DiskListRequest) String() string            { return proto.CompactTextString(m) }
func (*DiskListRequest) ProtoMessage()               {}
func (*DiskListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DiskListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Kube   string         `protobuf:"bytes,2,opt,name=kube" json:"kube,omitempty"`
	Disk   []*Disk        `protobuf:"bytes,3,rep,name=disk" json:"disk,omitempty"`
}

func (m *DiskListResponse) Reset()                    { *m = DiskListResponse{} }
func (m *DiskListResponse) String() string            { return proto.CompactTextString(m) }
func (*DiskListResponse) ProtoMessage()               {}
func (*DiskListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DiskListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DiskListResponse) GetDisk() []*Disk {
	if m != nil {
		return m.Disk
	}
	return nil
}

type Disk struct {
	Name     string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id       string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Provider string   `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	Size     int64    `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Type     string   `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	Zone     string   `protobuf:"bytes,6,opt,name=zone" json:"zone,omitempty"`
	Status   string   `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	Users    []string `protobuf:"bytes,8,rep,name=users" json:"users,omitempty"`
	Kind     string   `protobuf:"bytes,9,opt,name=kind" json:"kind,omitempty"`
	Endpoint string   `protobuf:"bytes,10,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *Disk) Reset()                    { *m = Disk{} }
func (m *Disk) String() string            { return proto.CompactTextString(m) }
func (*Disk) ProtoMessage()               {}
func (*Disk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*DiskCreateRequest)(nil), "pv.DiskCreateRequest")
	proto.RegisterType((*DiskDeleteRequest)(nil), "pv.DiskDeleteRequest")
	proto.RegisterType((*DiskListRequest)(nil), "pv.DiskListRequest")
	proto.RegisterType((*DiskListResponse)(nil), "pv.DiskListResponse")
	proto.RegisterType((*Disk)(nil), "pv.Disk")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Disks service

type DisksClient interface {
	List(ctx context.Context, in *DiskListRequest, opts ...grpc.CallOption) (*DiskListResponse, error)
	Create(ctx context.Context, in *DiskCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Delete(ctx context.Context, in *DiskDeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
}

type disksClient struct {
	cc *grpc.ClientConn
}

func NewDisksClient(cc *grpc.ClientConn) DisksClient {
	return &disksClient{cc}
}

func (c *disksClient) List(ctx context.Context, in *DiskListRequest, opts ...grpc.CallOption) (*DiskListResponse, error) {
	out := new(DiskListResponse)
	err := grpc.Invoke(ctx, "/pv.Disks/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disksClient) Create(ctx context.Context, in *DiskCreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/pv.Disks/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disksClient) Delete(ctx context.Context, in *DiskDeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/pv.Disks/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Disks service

type DisksServer interface {
	List(context.Context, *DiskListRequest) (*DiskListResponse, error)
	Create(context.Context, *DiskCreateRequest) (*dtypes.VoidResponse, error)
	Delete(context.Context, *DiskDeleteRequest) (*dtypes.VoidResponse, error)
}

func RegisterDisksServer(s *grpc.Server, srv DisksServer) {
	s.RegisterService(&_Disks_serviceDesc, srv)
}

func _Disks_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DiskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DisksServer).List(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Disks_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DiskCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DisksServer).Create(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Disks_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DiskDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DisksServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Disks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pv.Disks",
	HandlerType: (*DisksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Disks_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Disks_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Disks_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x9f, 0x4d, 0x2e, 0xd0, 0xc7, 0x00, 0xd5, 0xc8, 0xaa, 0x2a, 0x64, 0x58, 0x94, 0x22,
	0xd9, 0xb4, 0x6c, 0x10, 0x5b, 0xba, 0x64, 0x05, 0x12, 0xb0, 0x43, 0x2e, 0xbe, 0x94, 0x51, 0xc2,
	0xcc, 0xe0, 0x19, 0x5b, 0x22, 0x51, 0x36, 0xfc, 0x02, 0x4b, 0xbe, 0x82, 0x6f, 0xe1, 0x17, 0xf8,
	0x10, 0xe6, 0x61, 0x27, 0xf5, 0x22, 0xd9, 0x58, 0xbe, 0x57, 0x77, 0xce, 0x4b, 0x07, 0xa0, 0x66,
	0x6a, 0x56, 0xc8, 0x46, 0x68, 0x41, 0x42, 0xd9, 0x65, 0x27, 0x37, 0x42, 0xdc, 0xcc, 0xb1, 0xac,
	0x24, 0x2b, 0x2b, 0xce, 0x85, 0xae, 0x34, 0x13, 0x5c, 0xf9, 0x8b, 0xec, 0xd8, 0xae, 0x6b, 0xfd,
	0x43, 0xa2, 0x2a, 0xdd, 0xd7, 0xef, 0xf3, 0x0a, 0x8e, 0xae, 0x0c, 0xce, 0xeb, 0x06, 0x2b, 0x8d,
	0x6f, 0xf1, 0x7b, 0x8b, 0x4a, 0x93, 0x03, 0xd8, 0xfb, 0x3c, 0x6f, 0x95, 0xc6, 0x86, 0x06, 0x8f,
	0x82, 0xb3, 0x29, 0xb9, 0x0b, 0x31, 0xaf, 0xbe, 0x21, 0x0d, 0x87, 0x69, 0x21, 0x38, 0xd2, 0xc8,
	0x4d, 0x47, 0x30, 0xb5, 0x4a, 0x3e, 0x59, 0x54, 0x1a, 0x0f, 0x07, 0x8a, 0x2d, 0x90, 0x26, 0x66,
	0x8a, 0xf2, 0x97, 0x9e, 0xe2, 0x0a, 0xe7, 0xb8, 0x83, 0x82, 0x00, 0xb0, 0x1a, 0xb9, 0x66, 0x5f,
	0x98, 0xd9, 0x39, 0xa2, 0x3c, 0x87, 0x03, 0xfb, 0xf2, 0x0d, 0x53, 0x7a, 0xdb, 0xbb, 0xfc, 0x23,
	0x1c, 0x6e, 0x6e, 0x94, 0x34, 0x8e, 0x91, 0x9c, 0x42, 0xaa, 0x8c, 0xfd, 0x56, 0xb9, 0x9b, 0x3b,
	0x97, 0xfb, 0x85, 0x77, 0x5e, 0xbc, 0x73, 0x5b, 0xab, 0x6f, 0xd6, 0x5e, 0x0f, 0x76, 0x8e, 0x21,
	0xb6, 0x06, 0x8c, 0x9d, 0xc8, 0xdc, 0x4e, 0x0a, 0xd9, 0x15, 0x16, 0x31, 0xff, 0x1d, 0x40, 0x6c,
	0x7f, 0xd6, 0xee, 0xbd, 0x50, 0x80, 0x90, 0xd5, 0xfd, 0xd3, 0x43, 0x98, 0x98, 0x18, 0x3b, 0x23,
	0xbc, 0xe9, 0xd3, 0x18, 0xac, 0xdb, 0x20, 0x22, 0x3b, 0xb9, 0x58, 0x92, 0x51, 0x6e, 0xa9, 0x9b,
	0xf6, 0xd7, 0x22, 0xf7, 0xdc, 0x7c, 0x0f, 0x92, 0x56, 0x61, 0xa3, 0xe8, 0xc4, 0xe8, 0x70, 0xc7,
	0x33, 0xc6, 0x6b, 0x3a, 0x1d, 0x88, 0x90, 0xd7, 0x52, 0x30, 0xae, 0x29, 0xd8, 0xcd, 0xe5, 0x9f,
	0x10, 0x12, 0xab, 0x4e, 0x91, 0x0f, 0x10, 0x5b, 0xf7, 0xe4, 0xfe, 0xa0, 0xfc, 0x56, 0x5e, 0xd9,
	0x83, 0xf1, 0xd2, 0x07, 0x94, 0x3f, 0xf9, 0xf9, 0xf7, 0xdf, 0xaf, 0xf0, 0x94, 0x9c, 0xb8, 0xb6,
	0xc8, 0xae, 0xec, 0x9e, 0x17, 0x17, 0xa5, 0x4d, 0x41, 0x95, 0xcb, 0x3e, 0xdf, 0x15, 0x41, 0x48,
	0x7d, 0x2f, 0xc8, 0xc3, 0x01, 0x65, 0xd4, 0x13, 0x03, 0xde, 0xe7, 0xfa, 0x5e, 0xb0, 0x7a, 0x0d,
	0x5e, 0x38, 0xf0, 0xb3, 0xec, 0xf1, 0x2e, 0xf0, 0x72, 0x69, 0x23, 0x5d, 0xbd, 0x0a, 0xce, 0xc9,
	0x57, 0x48, 0x7d, 0x37, 0x36, 0x34, 0xa3, 0xae, 0x6c, 0xa1, 0xb9, 0x70, 0x34, 0xcf, 0xce, 0x9f,
	0xee, 0xa6, 0xd9, 0x94, 0x6a, 0x75, 0x9d, 0xba, 0xce, 0xbf, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x75, 0xe4, 0x45, 0xcc, 0x3b, 0x03, 0x00, 0x00,
}
