// Code generated by protoc-gen-go.
// source: clusters.proto
// DO NOT EDIT!

package kubernetes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Cluster struct {
	Phid      string            `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	Name      string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Provider  string            `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	Zone      string            `protobuf:"bytes,4,opt,name=zone" json:"zone,omitempty"`
	Region    string            `protobuf:"bytes,5,opt,name=region" json:"region,omitempty"`
	Os        string            `protobuf:"bytes,6,opt,name=os" json:"os,omitempty"`
	Links     map[string]string `protobuf:"bytes,7,rep,name=links" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Nodes     int32             `protobuf:"varint,8,opt,name=nodes" json:"nodes,omitempty"`
	CreatedAt string            `protobuf:"bytes,9,opt,name=created_at" json:"created_at,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Cluster) GetLinks() map[string]string {
	if m != nil {
		return m.Links
	}
	return nil
}

type ClusterDescribeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterDescribeRequest) Reset()                    { *m = ClusterDescribeRequest{} }
func (m *ClusterDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeRequest) ProtoMessage()               {}
func (*ClusterDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ClusterDescribeResponse struct {
	Status  *dtypes.Status                 `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Cluster *Cluster                       `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
	Specs   *ClusterDescribeResponse_Specs `protobuf:"bytes,3,opt,name=specs" json:"specs,omitempty"`
}

func (m *ClusterDescribeResponse) Reset()                    { *m = ClusterDescribeResponse{} }
func (m *ClusterDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse) ProtoMessage()               {}
func (*ClusterDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ClusterDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClusterDescribeResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClusterDescribeResponse) GetSpecs() *ClusterDescribeResponse_Specs {
	if m != nil {
		return m.Specs
	}
	return nil
}

type ClusterDescribeResponse_Specs struct {
	Containers  int32 `protobuf:"varint,1,opt,name=containers" json:"containers,omitempty"`
	Pods        int32 `protobuf:"varint,2,opt,name=pods" json:"pods,omitempty"`
	Services    int32 `protobuf:"varint,3,opt,name=services" json:"services,omitempty"`
	Rcs         int32 `protobuf:"varint,4,opt,name=rcs" json:"rcs,omitempty"`
	CpuCore     int64 `protobuf:"varint,5,opt,name=cpu_core" json:"cpu_core,omitempty"`
	TotalMemory int64 `protobuf:"varint,6,opt,name=total_memory" json:"total_memory,omitempty"`
}

func (m *ClusterDescribeResponse_Specs) Reset()         { *m = ClusterDescribeResponse_Specs{} }
func (m *ClusterDescribeResponse_Specs) String() string { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse_Specs) ProtoMessage()    {}
func (*ClusterDescribeResponse_Specs) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{2, 0}
}

type ClusterListResponse struct {
	Status   *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Clusters []*Cluster     `protobuf:"bytes,2,rep,name=clusters" json:"clusters,omitempty"`
}

func (m *ClusterListResponse) Reset()                    { *m = ClusterListResponse{} }
func (m *ClusterListResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterListResponse) ProtoMessage()               {}
func (*ClusterListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ClusterListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClusterListResponse) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type ClusterCreateRequest struct {
	Name                string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Provider            string            `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	Zone                string            `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
	CloudCredential     string            `protobuf:"bytes,4,opt,name=cloud_credential" json:"cloud_credential,omitempty"`
	CloudCredentialData map[string]string `protobuf:"bytes,5,rep,name=cloud_credential_data" json:"cloud_credential_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeSet             map[string]int64  `protobuf:"bytes,6,rep,name=node_set" json:"node_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SaltbaseVersion     string            `protobuf:"bytes,7,opt,name=saltbase_version" json:"saltbase_version,omitempty"`
	KubeStarterVersion  string            `protobuf:"bytes,8,opt,name=kube_starter_version" json:"kube_starter_version,omitempty"`
	KubeVersion         string            `protobuf:"bytes,9,opt,name=kube_version" json:"kube_version,omitempty"`
}

func (m *ClusterCreateRequest) Reset()                    { *m = ClusterCreateRequest{} }
func (m *ClusterCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterCreateRequest) ProtoMessage()               {}
func (*ClusterCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ClusterCreateRequest) GetCloudCredentialData() map[string]string {
	if m != nil {
		return m.CloudCredentialData
	}
	return nil
}

func (m *ClusterCreateRequest) GetNodeSet() map[string]int64 {
	if m != nil {
		return m.NodeSet
	}
	return nil
}

type ClusterScaleRequest struct {
	Name        string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NodeChanges map[string]int64 `protobuf:"bytes,2,rep,name=node_changes" json:"node_changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *ClusterScaleRequest) Reset()                    { *m = ClusterScaleRequest{} }
func (m *ClusterScaleRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterScaleRequest) ProtoMessage()               {}
func (*ClusterScaleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ClusterScaleRequest) GetNodeChanges() map[string]int64 {
	if m != nil {
		return m.NodeChanges
	}
	return nil
}

type ClusterDeleteRequest struct {
	Name              string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReleaseReservedIp bool   `protobuf:"varint,2,opt,name=release_reserved_ip" json:"release_reserved_ip,omitempty"`
}

func (m *ClusterDeleteRequest) Reset()                    { *m = ClusterDeleteRequest{} }
func (m *ClusterDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDeleteRequest) ProtoMessage()               {}
func (*ClusterDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type ClusterStartupScriptRequest struct {
	Role string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
}

func (m *ClusterStartupScriptRequest) Reset()                    { *m = ClusterStartupScriptRequest{} }
func (m *ClusterStartupScriptRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterStartupScriptRequest) ProtoMessage()               {}
func (*ClusterStartupScriptRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type ClusterStartupScriptResponse struct {
	Status        *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Configuration string         `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *ClusterStartupScriptResponse) Reset()                    { *m = ClusterStartupScriptResponse{} }
func (m *ClusterStartupScriptResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterStartupScriptResponse) ProtoMessage()               {}
func (*ClusterStartupScriptResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ClusterStartupScriptResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ClusterClientConfigRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterClientConfigRequest) Reset()                    { *m = ClusterClientConfigRequest{} }
func (m *ClusterClientConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigRequest) ProtoMessage()               {}
func (*ClusterClientConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type ClusterClientConfigResponse struct {
	Status        *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Configuration string         `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *ClusterClientConfigResponse) Reset()                    { *m = ClusterClientConfigResponse{} }
func (m *ClusterClientConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigResponse) ProtoMessage()               {}
func (*ClusterClientConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ClusterClientConfigResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ClusterClientContainerRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DiskName string `protobuf:"bytes,2,opt,name=disk_name" json:"disk_name,omitempty"`
}

func (m *ClusterClientContainerRequest) Reset()                    { *m = ClusterClientContainerRequest{} }
func (m *ClusterClientContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientContainerRequest) ProtoMessage()               {}
func (*ClusterClientContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type ClusterInstanceListRequest struct {
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name" json:"cluster_name,omitempty"`
}

func (m *ClusterInstanceListRequest) Reset()                    { *m = ClusterInstanceListRequest{} }
func (m *ClusterInstanceListRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceListRequest) ProtoMessage()               {}
func (*ClusterInstanceListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type ClusterInstance struct {
	Phid       string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	ExternalId string `protobuf:"bytes,2,opt,name=external_id" json:"external_id,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ExternalIp string `protobuf:"bytes,4,opt,name=external_ip" json:"external_ip,omitempty"`
	InternalIp string `protobuf:"bytes,5,opt,name=internal_ip" json:"internal_ip,omitempty"`
	Role       string `protobuf:"bytes,6,opt,name=role" json:"role,omitempty"`
	Sku        string `protobuf:"bytes,7,opt,name=sku" json:"sku,omitempty"`
}

func (m *ClusterInstance) Reset()                    { *m = ClusterInstance{} }
func (m *ClusterInstance) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstance) ProtoMessage()               {}
func (*ClusterInstance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type ClusterInstanceListResponse struct {
	Status    *dtypes.Status     `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Instances []*ClusterInstance `protobuf:"bytes,2,rep,name=instances" json:"instances,omitempty"`
}

func (m *ClusterInstanceListResponse) Reset()                    { *m = ClusterInstanceListResponse{} }
func (m *ClusterInstanceListResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceListResponse) ProtoMessage()               {}
func (*ClusterInstanceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *ClusterInstanceListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClusterInstanceListResponse) GetInstances() []*ClusterInstance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type ClusterUpdateRequest struct {
	Name               string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SaltbaseVersion    string `protobuf:"bytes,2,opt,name=saltbase_version" json:"saltbase_version,omitempty"`
	KubeStarterVersion string `protobuf:"bytes,3,opt,name=kube_starter_version" json:"kube_starter_version,omitempty"`
	KubeVersion        string `protobuf:"bytes,4,opt,name=kube_version" json:"kube_version,omitempty"`
}

func (m *ClusterUpdateRequest) Reset()                    { *m = ClusterUpdateRequest{} }
func (m *ClusterUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterUpdateRequest) ProtoMessage()               {}
func (*ClusterUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func init() {
	proto.RegisterType((*Cluster)(nil), "kubernetes.Cluster")
	proto.RegisterType((*ClusterDescribeRequest)(nil), "kubernetes.ClusterDescribeRequest")
	proto.RegisterType((*ClusterDescribeResponse)(nil), "kubernetes.ClusterDescribeResponse")
	proto.RegisterType((*ClusterDescribeResponse_Specs)(nil), "kubernetes.ClusterDescribeResponse.Specs")
	proto.RegisterType((*ClusterListResponse)(nil), "kubernetes.ClusterListResponse")
	proto.RegisterType((*ClusterCreateRequest)(nil), "kubernetes.ClusterCreateRequest")
	proto.RegisterType((*ClusterScaleRequest)(nil), "kubernetes.ClusterScaleRequest")
	proto.RegisterType((*ClusterDeleteRequest)(nil), "kubernetes.ClusterDeleteRequest")
	proto.RegisterType((*ClusterStartupScriptRequest)(nil), "kubernetes.ClusterStartupScriptRequest")
	proto.RegisterType((*ClusterStartupScriptResponse)(nil), "kubernetes.ClusterStartupScriptResponse")
	proto.RegisterType((*ClusterClientConfigRequest)(nil), "kubernetes.ClusterClientConfigRequest")
	proto.RegisterType((*ClusterClientConfigResponse)(nil), "kubernetes.ClusterClientConfigResponse")
	proto.RegisterType((*ClusterClientContainerRequest)(nil), "kubernetes.ClusterClientContainerRequest")
	proto.RegisterType((*ClusterInstanceListRequest)(nil), "kubernetes.ClusterInstanceListRequest")
	proto.RegisterType((*ClusterInstance)(nil), "kubernetes.ClusterInstance")
	proto.RegisterType((*ClusterInstanceListResponse)(nil), "kubernetes.ClusterInstanceListResponse")
	proto.RegisterType((*ClusterUpdateRequest)(nil), "kubernetes.ClusterUpdateRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Clusters service

type ClustersClient interface {
	Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error)
	Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Scale(ctx context.Context, in *ClusterScaleRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	List(ctx context.Context, in *dtypes.VoidRequest, opts ...grpc.CallOption) (*ClusterListResponse, error)
	StartupScript(ctx context.Context, in *ClusterStartupScriptRequest, opts ...grpc.CallOption) (*ClusterStartupScriptResponse, error)
	ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error)
	Instances(ctx context.Context, in *ClusterInstanceListRequest, opts ...grpc.CallOption) (*ClusterInstanceListResponse, error)
}

type clustersClient struct {
	cc *grpc.ClientConn
}

func NewClustersClient(cc *grpc.ClientConn) ClustersClient {
	return &clustersClient{cc}
}

func (c *clustersClient) Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error) {
	out := new(ClusterDescribeResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Scale(ctx context.Context, in *ClusterScaleRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Scale", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) List(ctx context.Context, in *dtypes.VoidRequest, opts ...grpc.CallOption) (*ClusterListResponse, error) {
	out := new(ClusterListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) StartupScript(ctx context.Context, in *ClusterStartupScriptRequest, opts ...grpc.CallOption) (*ClusterStartupScriptResponse, error) {
	out := new(ClusterStartupScriptResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/StartupScript", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error) {
	out := new(ClusterClientConfigResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/ClientConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Instances(ctx context.Context, in *ClusterInstanceListRequest, opts ...grpc.CallOption) (*ClusterInstanceListResponse, error) {
	out := new(ClusterInstanceListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Instances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Clusters service

type ClustersServer interface {
	Describe(context.Context, *ClusterDescribeRequest) (*ClusterDescribeResponse, error)
	Create(context.Context, *ClusterCreateRequest) (*dtypes.LongRunningResponse, error)
	Scale(context.Context, *ClusterScaleRequest) (*dtypes.LongRunningResponse, error)
	Delete(context.Context, *ClusterDeleteRequest) (*dtypes.LongRunningResponse, error)
	Update(context.Context, *ClusterUpdateRequest) (*dtypes.LongRunningResponse, error)
	List(context.Context, *dtypes.VoidRequest) (*ClusterListResponse, error)
	StartupScript(context.Context, *ClusterStartupScriptRequest) (*ClusterStartupScriptResponse, error)
	ClientConfig(context.Context, *ClusterClientConfigRequest) (*ClusterClientConfigResponse, error)
	Instances(context.Context, *ClusterInstanceListRequest) (*ClusterInstanceListResponse, error)
}

func RegisterClustersServer(s *grpc.Server, srv ClustersServer) {
	s.RegisterService(&_Clusters_serviceDesc, srv)
}

func _Clusters_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Describe(ctx, req.(*ClusterDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Create(ctx, req.(*ClusterCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Scale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Scale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Scale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Scale(ctx, req.(*ClusterScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Delete(ctx, req.(*ClusterDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Update(ctx, req.(*ClusterUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dtypes.VoidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).List(ctx, req.(*dtypes.VoidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_StartupScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStartupScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).StartupScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/StartupScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).StartupScript(ctx, req.(*ClusterStartupScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_ClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).ClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/ClientConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).ClientConfig(ctx, req.(*ClusterClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Instances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInstanceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Instances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Instances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Instances(ctx, req.(*ClusterInstanceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clusters_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubernetes.Clusters",
	HandlerType: (*ClustersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Clusters_Describe_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Clusters_Create_Handler,
		},
		{
			MethodName: "Scale",
			Handler:    _Clusters_Scale_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Clusters_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Clusters_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Clusters_List_Handler,
		},
		{
			MethodName: "StartupScript",
			Handler:    _Clusters_StartupScript_Handler,
		},
		{
			MethodName: "ClientConfig",
			Handler:    _Clusters_ClientConfig_Handler,
		},
		{
			MethodName: "Instances",
			Handler:    _Clusters_Instances_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor1 = []byte{
	// 1107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x57, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0x96, 0xe3, 0x3a, 0x4d, 0xdf, 0xb4, 0xa5, 0x4c, 0xbb, 0x8b, 0x71, 0x4a, 0x29, 0x66, 0xd9,
	0x2d, 0x85, 0x38, 0x25, 0x20, 0xb4, 0xf4, 0x02, 0x28, 0x05, 0x09, 0xa9, 0xe2, 0xb0, 0x61, 0x11,
	0x07, 0x24, 0xcb, 0xb5, 0x87, 0xac, 0x15, 0x67, 0xec, 0xf5, 0xd8, 0x11, 0x65, 0xd5, 0x0b, 0x17,
	0x0e, 0x1c, 0x39, 0x80, 0xb8, 0xf0, 0x23, 0xf8, 0x29, 0xfc, 0x02, 0x24, 0x7e, 0x07, 0x62, 0x3e,
	0x6c, 0x37, 0x4e, 0x27, 0x1f, 0x12, 0x97, 0xc8, 0x33, 0xf3, 0x7e, 0x3c, 0xf3, 0xbc, 0xef, 0xfb,
	0x8c, 0x02, 0xbb, 0x7e, 0x94, 0xd3, 0x0c, 0xa7, 0xd4, 0x49, 0xd2, 0x38, 0x8b, 0x11, 0x8c, 0xf3,
	0x2b, 0x9c, 0x12, 0x9c, 0x61, 0x6a, 0x1d, 0x8e, 0xe2, 0x78, 0x14, 0xe1, 0x9e, 0x97, 0x84, 0x3d,
	0x8f, 0x90, 0x38, 0xf3, 0xb2, 0x30, 0x26, 0x85, 0xa5, 0x75, 0x9f, 0x6f, 0x07, 0xd9, 0x75, 0x82,
	0x69, 0x4f, 0xfc, 0xca, 0x7d, 0xfb, 0x6f, 0x0d, 0x36, 0x07, 0x32, 0x28, 0xda, 0x86, 0x8d, 0xe4,
	0x59, 0x18, 0x98, 0xda, 0xb1, 0x76, 0xb2, 0xc5, 0x57, 0xc4, 0x9b, 0x60, 0xb3, 0x21, 0x56, 0x7b,
	0xd0, 0x62, 0x0e, 0xd3, 0x30, 0xc0, 0xa9, 0xa9, 0x97, 0xe7, 0x3f, 0xc4, 0x04, 0x9b, 0x1b, 0x62,
	0xb5, 0x0b, 0xcd, 0x14, 0x8f, 0x58, 0x42, 0xd3, 0x10, 0x6b, 0x80, 0x46, 0x4c, 0xcd, 0xa6, 0xf8,
	0xee, 0x82, 0x11, 0x85, 0x64, 0x4c, 0xcd, 0xcd, 0x63, 0xfd, 0xa4, 0xdd, 0x3f, 0x72, 0x6e, 0x51,
	0x3b, 0x45, 0x6e, 0xe7, 0x92, 0x1b, 0x7c, 0x46, 0xb2, 0xf4, 0x1a, 0xed, 0x80, 0x41, 0xe2, 0x00,
	0x53, 0xb3, 0xc5, 0xbc, 0x0d, 0xc4, 0x42, 0xf9, 0x29, 0xf6, 0x32, 0x1c, 0xb8, 0x5e, 0x66, 0x6e,
	0xf1, 0x88, 0xd6, 0xbb, 0x00, 0x33, 0x0e, 0x6d, 0xd0, 0xc7, 0xf8, 0xba, 0x80, 0xcd, 0xbc, 0xa7,
	0x5e, 0x94, 0x17, 0xb8, 0xcf, 0x1b, 0x8f, 0x35, 0xfb, 0x21, 0xdc, 0x2f, 0xd2, 0x5c, 0x60, 0xea,
	0xa7, 0xe1, 0x15, 0x7e, 0x82, 0x9f, 0xe7, 0x98, 0x66, 0xd5, 0x1d, 0x85, 0xab, 0xfd, 0x73, 0x03,
	0x5e, 0xb9, 0x63, 0x48, 0x13, 0x46, 0x22, 0x46, 0x47, 0xd0, 0xa4, 0x8c, 0xd1, 0x9c, 0x0a, 0xdb,
	0x76, 0x7f, 0xd7, 0x91, 0x64, 0x3a, 0x43, 0xb1, 0x8b, 0x1e, 0xc0, 0x66, 0x51, 0x1b, 0x91, 0xb8,
	0xdd, 0xdf, 0x57, 0xdc, 0x12, 0x3d, 0x06, 0x83, 0x26, 0xd8, 0xa7, 0x82, 0xc2, 0x76, 0xff, 0x6d,
	0x85, 0xcd, 0x7c, 0x66, 0x67, 0xc8, 0x1d, 0xac, 0x04, 0x0c, 0xf1, 0x21, 0xe8, 0x88, 0x49, 0xe6,
	0x85, 0x84, 0xb5, 0x81, 0x00, 0x63, 0x88, 0xc2, 0xc5, 0x01, 0x15, 0x99, 0x0d, 0x5e, 0x2a, 0x8a,
	0xd3, 0x69, 0xe8, 0x63, 0x99, 0xc7, 0xe0, 0x04, 0xa5, 0x2c, 0xe9, 0x46, 0x79, 0xec, 0x27, 0xb9,
	0xeb, 0xc7, 0x29, 0x16, 0xb5, 0xd2, 0xd1, 0x01, 0x6c, 0x67, 0xac, 0x5d, 0x22, 0x77, 0x82, 0x27,
	0x71, 0x7a, 0x2d, 0xaa, 0xa6, 0xdb, 0xdf, 0xc2, 0x7e, 0x01, 0xe9, 0x32, 0xa4, 0xd9, 0xda, 0x44,
	0xbc, 0xc5, 0xc2, 0x17, 0x4d, 0xca, 0xf0, 0xe8, 0x0b, 0x98, 0xb0, 0xff, 0xd4, 0xe1, 0xa0, 0xf8,
	0x1e, 0x88, 0xea, 0x2a, 0x4b, 0x52, 0x6b, 0xbb, 0x46, 0xad, 0xed, 0x64, 0x13, 0x9a, 0xb0, 0xe7,
	0x47, 0x71, 0x1e, 0xb8, 0xac, 0x45, 0x02, 0x4c, 0xb2, 0xd0, 0x8b, 0x8a, 0x86, 0xfc, 0x06, 0xee,
	0xcd, 0x9f, 0xb8, 0x81, 0x97, 0x79, 0xec, 0xce, 0x1c, 0xd4, 0x47, 0x0a, 0x50, 0x35, 0x20, 0x6c,
	0x93, 0x79, 0x0f, 0x2a, 0xe7, 0x0b, 0xe6, 0x2b, 0xdb, 0xed, 0x63, 0x68, 0xf1, 0xfe, 0x74, 0x29,
	0xce, 0x18, 0x55, 0x3c, 0x58, 0x77, 0x65, 0xb0, 0x2f, 0x99, 0xc3, 0x10, 0x67, 0x32, 0x00, 0x03,
	0x4d, 0xbd, 0x28, 0xbb, 0xf2, 0x28, 0x76, 0xa7, 0x8c, 0x27, 0x3e, 0x35, 0x9b, 0x02, 0xf4, 0x21,
	0x1c, 0xf0, 0x48, 0x2e, 0x63, 0x38, 0x65, 0x31, 0xaa, 0xd3, 0x96, 0x38, 0x65, 0x75, 0x12, 0xa7,
	0xe5, 0xae, 0x9c, 0x85, 0x73, 0x30, 0x17, 0x42, 0x5d, 0x31, 0x19, 0x96, 0x03, 0xdb, 0x35, 0x64,
	0x8b, 0xed, 0x75, 0x31, 0x49, 0x7f, 0x68, 0x55, 0x53, 0x0c, 0x7d, 0x2f, 0x5a, 0x50, 0xb4, 0xcf,
	0x61, 0x5b, 0x10, 0xe4, 0x3f, 0xf3, 0xc8, 0x08, 0x97, 0x6d, 0x70, 0xa6, 0x20, 0x69, 0x36, 0x88,
	0xe0, 0x68, 0x20, 0x5d, 0x04, 0x1a, 0xab, 0x0f, 0x7b, 0xf3, 0x7b, 0x2b, 0x11, 0x7e, 0x5a, 0xb5,
	0xd5, 0x05, 0x8e, 0xf0, 0xa2, 0xb6, 0xea, 0xc0, 0x7e, 0xca, 0x8e, 0x79, 0x01, 0x52, 0xcc, 0x87,
	0x85, 0x89, 0x4b, 0x98, 0x88, 0x30, 0x2d, 0xfb, 0x1d, 0xe8, 0x94, 0xf0, 0x78, 0x19, 0xf2, 0x64,
	0xc8, 0x06, 0x32, 0xc9, 0x66, 0x22, 0xa5, 0x71, 0x54, 0x6a, 0xc6, 0x53, 0x38, 0x54, 0x1b, 0xaf,
	0x39, 0x2e, 0xf7, 0x60, 0x87, 0x8d, 0xf3, 0x77, 0xe1, 0x28, 0x4f, 0x85, 0x5e, 0xcb, 0xe2, 0xd8,
	0xa7, 0x60, 0x95, 0x7d, 0x14, 0x85, 0xac, 0xaa, 0x03, 0x61, 0xa3, 0x96, 0xad, 0xaf, 0x2a, 0xbc,
	0x75, 0xdb, 0xff, 0x87, 0xe0, 0x13, 0x78, 0x6d, 0x3e, 0xaa, 0x14, 0x1d, 0x35, 0xa3, 0x2f, 0xc3,
	0x56, 0x10, 0xd2, 0xb1, 0x7b, 0xfb, 0x64, 0xd8, 0xfd, 0xea, 0x0e, 0x5f, 0x10, 0x86, 0x80, 0xf8,
	0x58, 0x0a, 0x89, 0x74, 0x67, 0xcd, 0x5c, 0xe8, 0x84, 0x3b, 0x73, 0x97, 0x9f, 0x34, 0x78, 0x69,
	0xce, 0x69, 0xee, 0x59, 0xda, 0x87, 0x36, 0xfe, 0x9e, 0x1d, 0x13, 0x36, 0xcf, 0x6c, 0xb3, 0x51,
	0x7b, 0xab, 0xf4, 0xbb, 0x26, 0x49, 0xa1, 0x07, 0x6c, 0x33, 0x24, 0xb7, 0x9b, 0x46, 0xe9, 0x27,
	0x6a, 0x29, 0xdf, 0x29, 0xd6, 0x5b, 0x74, 0x9c, 0xcb, 0x51, 0xb4, 0x27, 0x15, 0xab, 0x75, 0xf4,
	0x6b, 0xb2, 0xea, 0xc0, 0x56, 0x58, 0xf8, 0x95, 0x03, 0xd0, 0x51, 0x0c, 0x40, 0x19, 0xdb, 0x4e,
	0xab, 0xbe, 0x7d, 0x9a, 0x04, 0x0b, 0xe5, 0x50, 0xa5, 0x1c, 0x8d, 0xa5, 0xca, 0xa1, 0x2b, 0x95,
	0x43, 0x50, 0xd2, 0xff, 0xb7, 0x05, 0xad, 0x22, 0x29, 0x45, 0x37, 0xd0, 0x2a, 0x9f, 0x1e, 0x64,
	0x2f, 0x7d, 0x97, 0x04, 0x30, 0xeb, 0xcd, 0x35, 0xde, 0x2e, 0xfb, 0xe4, 0xc7, 0xbf, 0xfe, 0xf9,
	0xa5, 0x61, 0xa3, 0xe3, 0xde, 0xad, 0x71, 0x6f, 0x7a, 0xe6, 0xbc, 0xd7, 0x2b, 0xdf, 0x88, 0xde,
	0x0b, 0x7e, 0xbd, 0x1b, 0x34, 0x81, 0xa6, 0x54, 0x4c, 0x74, 0xbc, 0x4a, 0x4c, 0xad, 0x4e, 0xc9,
	0xf5, 0x65, 0x4c, 0x46, 0x4f, 0x72, 0x42, 0x42, 0x52, 0xb5, 0xbb, 0xfd, 0x40, 0xa4, 0x3c, 0xb2,
	0x5e, 0x5d, 0x98, 0xf2, 0x5c, 0x3b, 0x45, 0x63, 0xf6, 0x9c, 0x72, 0xed, 0x41, 0xaf, 0xaf, 0x50,
	0xa5, 0xb5, 0x92, 0xd9, 0xcb, 0x93, 0x3d, 0x87, 0xa6, 0x14, 0x23, 0xe5, 0xdd, 0x6a, 0x3a, 0xb5,
	0x3c, 0x5d, 0x41, 0xe7, 0xe9, 0x6a, 0x3a, 0x59, 0x4a, 0xd9, 0x47, 0xca, 0x94, 0xb5, 0x16, 0x5b,
	0x2b, 0xa5, 0xbd, 0x3a, 0xa5, 0x0b, 0x1b, 0x7c, 0x42, 0xd0, 0x7e, 0x19, 0xee, 0xeb, 0x38, 0x0c,
	0xca, 0x1c, 0x2a, 0x9a, 0x67, 0xe7, 0xc9, 0x7e, 0x43, 0xe4, 0xe9, 0xa0, 0xc5, 0x4c, 0xa2, 0xdf,
	0x35, 0xd8, 0xa9, 0x89, 0x2c, 0x7a, 0xa4, 0x2a, 0x9e, 0x42, 0xb3, 0xad, 0x93, 0xd5, 0x86, 0x05,
	0x8e, 0x0f, 0x05, 0x8e, 0x33, 0xe4, 0x2c, 0xc2, 0xd1, 0xa5, 0xd2, 0xaf, 0x4b, 0x85, 0x63, 0xef,
	0x05, 0x17, 0x90, 0x1b, 0xf4, 0xab, 0x06, 0xdb, 0xb3, 0xf2, 0x8b, 0x1e, 0xaa, 0xda, 0xf8, 0xae,
	0x96, 0x5b, 0x8f, 0x56, 0xda, 0xad, 0x8b, 0xac, 0xac, 0x04, 0x5b, 0x73, 0xf7, 0xae, 0x54, 0x75,
	0xf4, 0x9b, 0x06, 0x5b, 0xa5, 0xcc, 0x50, 0x25, 0x2c, 0x85, 0x3c, 0x2b, 0x61, 0xa9, 0x84, 0xd0,
	0x3e, 0x17, 0xb0, 0x3e, 0x40, 0xfd, 0x25, 0xb0, 0x66, 0x85, 0xfe, 0xa6, 0x57, 0xe9, 0xe2, 0x55,
	0x53, 0xfc, 0x07, 0x79, 0xff, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x8f, 0xed, 0xc0, 0xd7,
	0x0c, 0x00, 0x00,
}
